#!/usr/bin/env python3

"""Generate the Frontier Move event learnset C table from canonical JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


def read_constants(path: Path, prefix: str) -> set[str]:
    return set(re.findall(rf"\b{prefix}[A-Z0-9_]+\b", path.read_text(encoding="utf-8")))


def render(document: dict, species_constants: set[str], move_constants: set[str]) -> str:
    species_moves = document.get("species")
    if not isinstance(species_moves, dict):
        raise ValueError("frontier_event_moves.json must contain a species object")

    lines = [
        "//",
        "// DO NOT MODIFY THIS FILE! It is generated by tools/frontier_move/generate_event_learnsets.py.",
        "// Source data: src/data/pokemon/frontier_event_moves.json",
        "//",
        "",
        "#ifndef GUARD_FRONTIER_EVENT_LEARNSETS_H",
        "#define GUARD_FRONTIER_EVENT_LEARNSETS_H",
        "",
    ]

    for species, moves in sorted(species_moves.items()):
        if species not in species_constants:
            raise ValueError(f"Unknown species constant: {species}")
        if not isinstance(moves, list) or not moves:
            raise ValueError(f"{species} must have a non-empty move list")
        if len(moves) != len(set(moves)):
            raise ValueError(f"{species} contains duplicate moves")

        lines.extend([
            f"static const u16 sFrontierEventLearnset_{species}[] =",
            "{",
        ])
        for move in sorted(moves):
            if move not in move_constants:
                raise ValueError(f"Unknown move constant for {species}: {move}")
            lines.append(f"    {move},")
        lines.extend(["    MOVE_UNAVAILABLE,", "};", ""])

    lines.extend([
        "static const u16 *const sFrontierEventLearnsets[NUM_SPECIES] =",
        "{",
    ])
    for species in sorted(species_moves):
        lines.append(f"    [{species}] = sFrontierEventLearnset_{species},")
    lines.extend(["};", "", "#endif // GUARD_FRONTIER_EVENT_LEARNSETS_H", ""])
    return "\n".join(lines)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    input_path = args.input or root / "src/data/pokemon/frontier_event_moves.json"
    output_path = args.output or root / "src/data/pokemon/frontier_event_learnsets.h"

    document = json.loads(input_path.read_text(encoding="utf-8"))
    species_constants = read_constants(root / "include/constants/species.h", "SPECIES_")
    move_constants = read_constants(root / "include/constants/moves.h", "MOVE_")
    content = render(document, species_constants, move_constants)

    if args.check:
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != content:
            print(f"{output_path} is out of date", file=sys.stderr)
            return 1
        print(f"{output_path} is up to date")
        return 0

    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

