CableClub_Text_WelcomeWhichCableClubService:
	.string "{JPN}つうしん ケーブル クラブに\nようこそ!\pどちらを ごりよう ですか?$"

CableClub_Text_WhichService:
	.string "{JPN}どちらを ごりよう ですか?$"

CableClub_Text_TradeUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\nポケモン こうかんが できます$"

CableClub_Text_BattleUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\nポケモン たいせんが できます$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "{JPN}ケーブルで つないだ おともだちと\nレコードコーナーが できます$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "{JPN}おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "{JPN}ダブルバトルでは 2ひき いじょうの\nポケモンが ひつようです$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "{JPN}こうかんでは 2ひき いじょうの\nてもちが ひつようです$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{JPN}{STR_VAR_1}のみを もっている\nポケモンは こうかん できません!$"

gText_PleaseWaitForLink::
	.string "{JPN}しょうしょう おまち ください\n……Bボタンで キャンセル$"

gText_ConfirmLinkWhenPlayersReady::
	.string "{JPN}そろったら Aボタンで すすむ\n……Bボタンで キャンセル$"

gText_ConfirmStartLinkWithXPlayers::
	.string "{JPN}{STR_VAR_1}にんで つうしんを はじめます\nAボタン…けってい Bボタン…もどる$"

gText_AwaitingLinkup::
	.string "{JPN}つうしんかいしを まっています\n……Bボタンで キャンセル$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "{JPN}はじめる まえに レポートを\nかきますが よろしいですか?$"

CableClub_Text_PleaseEnter:
	.string "{JPN}それでは へやへ どうぞ$"

CableClub_Text_DirectYouToYourRoom:
	.string "{JPN}それでは\nへやに ごあんないします$"

Text_SomeoneIsNotReadyToLink:
	.string "{JPN}おともだちの じゅんびが\nできて いない ようです\pじゅんびが できましたら\nまた おこしください$"

Text_LinkErrorPleaseReset:
	.string "{JPN}つうしんエラー です\nリセットして やりなおしてください$"

gText_LinkIncompatible::
	.string "{JPN}このゲームとは\nつうしん できません\pおなじ バージョンの\nゲームROMを つかってください$"

Text_PlayersMadeDifferentSelections:
	.string "{JPN}おたがいが えらんだ ものが\nちがっている ようです$"

CableClub_Text_PleaseVisitAgain:
	.string "{JPN}それでは また おこしください$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "{JPN}さんかしている にんずうが\nただしく ありません$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "{JPN}シングルバトルは {STR_VAR_1}にんで\nあそぶことは できません!$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "{JPN}ダブルバトルは {STR_VAR_1}にんでは\nあそぶことは できません!$"

CableClub_Text_NeedFourPlayers:
	.string "{JPN}さんか にんずうが 4にん いないと\nたいせん することが できません!$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "{JPN}もういちど にんずうを たしかめて\nはじめから やりなおして ください$"

Text_TerminateLinkConfirmation:
	.string "{JPN}へやからでると つうしんが\nおわりますが よろしいですか?$"

Text_TerminateLinkPleaseWait:
	.string "{JPN}つうしんを しゅうりょう します\nしばらく おまちください$"

CableClub_Text_TooBusyToNotice:
	.string "{JPN}とりこみちゅうの ようだ…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "{JPN}{STR_VAR_1}の トレーナーカードを\nみせてもらった!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "{JPN}{STR_VAR_1}の トレーナーカードを\nみせてもらった!\p…{STR_VAR_2}カードだ!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "{JPN}しょていの いちに ついて\nたいせんを はじめて ください$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "{JPN}しょていの いちに ついて\nこうかんを はじめて ください$"

RecordCorner_Text_ThanksForComing:
	.string "{JPN}ごりよう ありがとう ございました$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "{JPN}トレーナーカードの\nきろくを かきかえます!$"

CableClub_Text_HopeToSeeYouAgain:
	.string "{JPN}では また どうぞ!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "{JPN}おきゃくさま\nもうしわけ ありません\pとおい ちほうの かたと\nポケモンを こうかん することは\lいまは できません…$"

CableClub_Text_OtherTrainerNotReady:
	.string "{JPN}あいての じゅんびが\nできていません$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "{JPN}てもちに つれていけない\nポケモンが います$"

RecordCorner_Text_TakeSeatAndWait:
	.string "{JPN}しょていの いちに ついて\nおまち ください$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{JPN}{STR_VAR_1}さんから\n{STR_VAR_2}が おくられてきた!$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "ソーリー つうしんエラーやでー\p"
	.string "にほんの ルビサファと レコードを\n"
	.string "まぜられんでー\p"
	.string "ちな にほんの エメラルドと\n"
	.string "かいがいの ルビサファも\l"
	.string "レコード まぜらんよー$"

CableClub_Text_AdapterNotConnected:
	.string "{JPN}ワイヤレスアダプタが\nつながって いません$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "{JPN}さんか したい ひとは\nカウンターに おこしください$"

@ Unused
CableClub_Text_Hello:
	.string "{JPN}こんにちは!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "{JPN}しょうしょう おまちください$"

CableClub_Text_YouMayTradeHere::
	.string "{JPN}ともだちと ポケモンの\nこうかんが たのしめます$"

CableClub_Text_YouMayBattleHere::
	.string "{JPN}ともだちと ポケモンの\nたいせんが たのしめます$"

CableClub_Text_CanMakeBerryPowder::
	.string "{JPN}2にんから 5にんの ともだちと\nきのみで こなを つくります$"

CableClub_Text_CanMixRecords::
	.string "{JPN}2にんから 4にんの ともだちと\nレコードを まぜます$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "{JPN}ワイヤレス クラブでの\nあそびかたを せつめいします$"

CableClub_Text_CancelSelectedItem::
	.string "{JPN}やめます$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "{JPN}きのみを もって いないと\nきのみクラッシュは できません$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "{JPN}どちらの しょうぶに しますか?$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "{JPN}ひとつ まえに もどります$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "{JPN}ユニオンルームに はいるには\n2ひき いじょうの ポケモンを\lもって おこしください$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "{JPN}{STR_VAR_1}のみを もっている\nポケモンを おもちの かたは\lユニオンルームには はいれません…$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "{JPN}こちらは\nポケモン ワイヤレス クラブ\lユニオン ルームです\pワイヤレスアダプタが\nつながって いません\pまた おこしください$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "{JPN}あ……\nおきゃくさま!$"

CableClub_Text_PlayerIsWaiting:
	.string "{JPN}あら! いま {STR_VAR_1}さんも\nプレイちゅう みたいですね\lがんばって くださいね!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "{JPN}ぼくは ゲームの せつめいを\nしますよ!\lどの せつめいを ききますか?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "{JPN}「ミニポケモンでジャンプ」は\nツルの なわを Aボタンで\lタイミングよく とぶ ゲームです\pさんか できる ポケモンは\nたかさ 70センチくらい までの\lちいさい ポケモンに なります\pもぐっていたり とんでいたり する\nポケモンは ジャンプが\lじょうずに できないので\lざんねんながら さんか できません\pみんなの ジャンプの タイミングが\nピッタリ あえば\lよいことが ありますよ!$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "{JPN}「ドードリオのきのみどり」は\nドードリオの 3つの あたまに\lめいれいして うえから おちてくる\lきのみを おとさないように\lとりつづける ゲームです\pじゅうじボタンの\nうえ みぎ ひだりを つかいます\pこの ゲームを あそぶには\nドードリオが ひつようです$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "{JPN}ゲームを するなら\nおとなりの おじいさんに いってね$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "{JPN}やあ いらっしゃい\nワイヤレスつうしんの ゲームかな?\lちょっと まってね$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "{JPN}また おいでね$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "{JPN}ワイヤレスアダプタを つなげて\nあそびに おいで!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "{JPN}さて どの ゲームを\nやりたいのかな?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "{JPN}どの ポケモンを\nさんか させるのかな?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "{JPN}じゅんびが できたよ\nげんきに あそんで おいで!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "{JPN}きょうは かえるのかい?\nまた おいでね$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "{JPN}ゲームに さんかできる\nポケモンを もって いないんだね\pだれが さんか できるか\nせつめいを しようか?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "{JPN}「ミニポケモンでジャンプ」に\nさんか できる ポケモンは\lたかさ 70センチくらい までだよ\pじめんに もぐったり\nうかんでいる ポケモンは\lジャンプ できないから\lでられないんだよ$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "{JPN}「ドードリオのきのみどり」は\nドードリオ だけが\lさんか できる ゲームなんだよ$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "{JPN}もういちど はじめから\nやりなおして みて くれるかな?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "{JPN}ポケモン ワイヤレス クラブ\nダイレクト コーナーに ようこそ!\pこちらでは ともだちと ちょくせつ\nやりとり できます\pどの へやに はいりますか?$"

CableClub_Text_TradePokemon:
	.string "{JPN}こうかんを しますか?$"

CableClub_Text_PlayWhichBattleMode:
	.string "{JPN}どちらの たいせんを しますか?$"

CableClub_Text_AccessRecordCorner:
	.string "{JPN}レコードコーナーを しますか?$"

CableClub_Text_UseBerryCrush:
	.string "{JPN}きのみクラッシュを しますか?$"

CableClub_Text_ExplainBattleModes:
	.string "{JPN}たいせんには 3しゅるいの\nモードが あります\pシングルバトルは たたかいの ばに\nポケモンを 1ひきだして\lふたりで たいせんします\pダブルバトルは たたかいの ばに\nポケモンを 2ひきずつ だして\lふたりで たいせんします\pマルチバトルは たたかいの ばに\n4にんで ポケモンを 1ひきずつ\lだして 2たい2で たいせんします$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "{JPN}ふたりで はなしあって ひとりが\nリーダーに なってください\pもうひとりは グループにはいる を\nえらんでください$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "{JPN}4にんで はなしあって ひとりが\nグループリーダーに なってください\pほかの ひとは グループにはいる を\nえらんで ください$"

CableClub_Text_ChooseGroupLeader:
	.string "{JPN}みんなで はなしあって ひとりが\nグループリーダーに なってください\pほかの ひとは グループにはいる を\nえらんでください$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "{JPN}ポケモン ワイヤレス クラブ\nユニオン ルームに ようこそ!\pこちらでは みしらぬ ともだちと\nやりとり できます\pへやに はいりますか?$"

CableClub_Text_UnionRoomInfo:
	.string "{JPN}ユニオン ルーム は あなたの\nちかくで ユニオン ルームに\lはいっている ひとが あらわれます\pかんたんな あいさつをしたり\pレベル30までの ポケモン2ひきで\n1たい1の たいせん\p2にんから 5にんまで どうじに\nおしゃべりが できる チャット\pそして とうろくしき\nポケモン こうかんが たのしめます\pへやに はいりますか?$"

CableClub_Text_EnjoyUnionRoom:
	.string "{JPN}それでは ユニオン ルームで\nおたのしみ ください$"

CableClub_Text_FirstTimeRightThisWay:
	.string "{JPN}こんにちは!\pワイヤレス つうしんが\nはじめての かたですね?\pわたくし あんないやくの\nアオナと もうします\pポケモンセンター 2かいの\nごあんないを いたしますので\lこちらへ どうぞ!$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "{JPN}こちら 2かいには\nふたつの おへやが ございます\pひとつめは ひだりがわの おへや\nユニオン ルーム!\pあなたの ちかくで\nユニオン ルームに はいっている\lみしらぬ おともだちと\lいろいろな コミュニケーションが\lたのしめます!\pふたつめは みぎがわの おへや\nダイレクト コーナー!\pあなたの しっている おともだちと\nポケモンの こうかんや\lたいせん などを\lたのしむ ことが できます!\pもし ワイヤレスアダプタが\nつながって いない ばあいでも\pみぎがわの おへやで\nケーブル つうしんが たのしめます\pそれでは\pワイヤレス つうしんを\nたのしんで くださいね!$"

CableClub_Text_AskAboutLinking:
	.string "{JPN}こんにちは! {PLAYER}さん!\pポケモンセンター 2かいの\nあんないやく アオナです\pなにか つうしんで おこまりですか?$"

CableClub_Text_ExplainWirelessClub:
	.string "{JPN}ポケモン ワイヤレス クラブでの\nあそびかたを せつめい します!\pこちら 2かいには\nふたつの おへやが ございます\pひとつめは ひだりがわの おへや\nユニオン ルーム!\pあなたの ちかくで\nユニオン ルームに はいっている\lみしらぬ おともだちと\lいろいろな コミュニケーションが\lたのしめます!\pふたつめは みぎがわの おへや\nダイレクト コーナー!\pあなたの しっている おともだちと\nポケモンの こうかんや\lたいせん などを\lたのしむ ことが できます!\pもし ユニオン ルームや\nダイレクト コーナーで\lおともだちが みつからない ときは\pもうすこし おともだちと\nちかづいて みて ください\pまた ワイヤレスアダプタが\nつながって いない ばあいでも\pみぎがわの おへやで\nケーブル つうしんが たのしめます\pそれでは\pワイヤレス つうしんを\nたのしんで くださいね!$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "{JPN}ポケモン ワイヤレス クラブで\nおたのしみ ください$"
