MoveRelearner_Text_WouldLearnNewMoves:
	.string "{JPN}ぼく わざマニア\n"
	.string "どの しゅるいの わざに するんだい?$"

MoveRelearner_Text_LevelUpMoves:
	.string "{JPN}レベルアップ$"

MoveRelearner_Text_EggMoves:
	.string "{JPN}タマゴわざ$"

MoveRelearner_Text_TMMoves:
	.string "{JPN}わざマシン$"

MoveRelearner_Text_TutormoveMoves:
	.string "{JPN}おしえわざ$"

MoveRelearner_Text_SeeYa:
	.string "{JPN}やめる$"

MoveRelearner_Text_AnythingElse:
	.string "{JPN}どの しゅるいの わざに するんだい？$"

MoveRelearner_Text_ChoosePkmn:
	.string "{JPN}どの ポケモンに するんだい?$"

MoveRelearner_Text_HaveNoPkmn:
	.string "{JPN}ポケモンが いないよ$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "{JPN}えっ?\nタマゴに おしえられる わざは ないよ$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "{JPN}ごめんね……\pぼくが その ポケモンに\nおしえられる わざは ないみたいだよ$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "{JPN}レベルアップわざ$"

MoveRelearner_Text_EggMoveLWR::
	.string "{JPN}タマゴわざ$"

MoveRelearner_Text_TMMoveLWR::
	.string "{JPN}わざマシン$"

MoveRelearner_Text_TutorMoveLWR::
	.string "{JPN}おしえわざ$"

MoveRelearner_Text_MoveLWR::
	.string "{JPN}わざ$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "{JPN}どの {STR_VAR_3} にするんだい?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "{JPN}また おいで！$"
