//
// DO NOT MODIFY THIS FILE! It is generated by tools/frontier_move/generate_event_learnsets.py.
// Source data: src/data/pokemon/frontier_event_moves.json
//

#ifndef GUARD_FRONTIER_EVENT_LEARNSETS_H
#define GUARD_FRONTIER_EVENT_LEARNSETS_H

static const u16 sFrontierEventLearnset_SPECIES_ABSOL[] =
{
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_AERODACTYL[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ALCREMIE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_AMPHAROS[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ARBOK[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ARCEUS[] =
{
    MOVE_BLAST_BURN,
    MOVE_HYDRO_CANNON,
    MOVE_ROAR_OF_TIME,
    MOVE_SHADOW_FORCE,
    MOVE_SPACIAL_REND,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ARIADOS[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ARMAROUGE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ARTICUNO[] =
{
    MOVE_EXTRASENSORY,
    MOVE_HEAL_BELL,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_AUDINO[] =
{
    MOVE_PRESENT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BAGON[] =
{
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BALTOY[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BANETTE[] =
{
    MOVE_COTTON_GUARD,
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BAYLEEF[] =
{
    MOVE_FRENZY_PLANT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BEEDRILL[] =
{
    MOVE_BATON_PASS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BELDUM[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BELLSPROUT[] =
{
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BLASTOISE[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_FOLLOW_ME,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BLAZIKEN[] =
{
    MOVE_HIGH_JUMP_KICK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BLISSEY[] =
{
    MOVE_SWEET_SCENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BRELOOM[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BULBASAUR[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_FRENZY_PLANT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_BUTTERFREE[] =
{
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CACTURNE[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CARVANHA[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CELEBI[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CERULEDGE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHANSEY[] =
{
    MOVE_SWEET_SCENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHARCADET[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHARIZARD[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_HOLD_HANDS,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHARMANDER[] =
{
    MOVE_BLAST_BURN,
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHARMELEON[] =
{
    MOVE_BLAST_BURN,
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CHIKORITA[] =
{
    MOVE_FRENZY_PLANT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CLAYDOL[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CLOYSTER[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_COMFEY[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CORPHISH[] =
{
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CORSOLA[] =
{
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_COSMOEM[] =
{
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CRAWDAUNT[] =
{
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CROCONAW[] =
{
    MOVE_HYDRO_CANNON,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_CYNDAQUIL[] =
{
    MOVE_BLAST_BURN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DARKRAI[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_PHANTOM_FORCE,
    MOVE_ROAR_OF_TIME,
    MOVE_SPACIAL_REND,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DEERLING[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DELCATTY[] =
{
    MOVE_PAY_DAY,
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DELIBIRD[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DEOXYS_NORMAL[] =
{
    MOVE_COUNTER,
    MOVE_DETECT,
    MOVE_EXTREME_SPEED,
    MOVE_IRON_DEFENSE,
    MOVE_METEOR_MASH,
    MOVE_MIRROR_COAT,
    MOVE_SPIKES,
    MOVE_SUPERPOWER,
    MOVE_ZAP_CANNON,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DRAGONITE[] =
{
    MOVE_BARRIER,
    MOVE_HEAL_BELL,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_DROWZEE[] =
{
    MOVE_BELLY_DRUM,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EEVEE[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ELECTRODE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EMBOAR[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EMPOLEON[] =
{
    MOVE_SING,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ENTEI[] =
{
    MOVE_CRUSH_CLAW,
    MOVE_HOWL,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ESPEON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EXEGGCUTE[] =
{
    MOVE_SWEET_SCENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EXEGGUTOR[] =
{
    MOVE_REFRESH,
    MOVE_SWEET_SCENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EXEGGUTOR_ALOLA[] =
{
    MOVE_CELEBRATE,
    MOVE_SWEET_SCENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_EXPLOUD[] =
{
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FARFETCHD[] =
{
    MOVE_WISH,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FEAROW[] =
{
    MOVE_BATON_PASS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FLAAFFY[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FLABEBE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FLAREON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FLOETTE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FLORGES[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FORRETRESS[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_FROSLASS[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GALLADE[] =
{
    MOVE_SING,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GARDEVOIR[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GENESECT[] =
{
    MOVE_EXTREME_SPEED,
    MOVE_SHIFT_GEAR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GLACEON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GLALIE[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GOLDUCK[] =
{
    MOVE_CHARM,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GRENINJA[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GULPIN[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_GYARADOS[] =
{
    MOVE_CELEBRATE,
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HARIYAMA[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HEATRAN[] =
{
    MOVE_ERUPTION,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HITMONLEE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HOUNDOOM[] =
{
    MOVE_CHARM,
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HOUNDOUR[] =
{
    MOVE_CHARM,
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HO_OH[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_HYPNO[] =
{
    MOVE_BELLY_DRUM,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_IGGLYBUFF[] =
{
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_INKAY[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_IVYSAUR[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_FRENZY_PLANT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_JIGGLYPUFF[] =
{
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_JIRACHI[] =
{
    MOVE_DRACO_METEOR,
    MOVE_FOLLOW_ME,
    MOVE_HAPPY_HOUR,
    MOVE_HEART_STAMP,
    MOVE_MOONBLAST,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_JOLTEON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_JUMPLUFF[] =
{
    MOVE_FALSE_SWIPE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_KANGASKHAN[] =
{
    MOVE_SING,
    MOVE_WISH,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_KIRLIA[] =
{
    MOVE_SING,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_KLAWF[] =
{
    MOVE_BLOCK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_KLEAVOR[] =
{
    MOVE_MORNING_SUN,
    MOVE_RAZOR_WIND,
    MOVE_WING_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LATIAS[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LEAFEON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LEDIAN[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LEDYBA[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LICKILICKY[] =
{
    MOVE_HEAL_BELL,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LICKITUNG[] =
{
    MOVE_HEAL_BELL,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LOUDRED[] =
{
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LUCARIO[] =
{
    MOVE_HIGH_JUMP_KICK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LUGIA[] =
{
    MOVE_FEATHER_DANCE,
    MOVE_PSYCHO_BOOST,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LUNALA[] =
{
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_LYCANROC_DUSK[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGCARGO[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGIKARP[] =
{
    MOVE_CELEBRATE,
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGMAR[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGMORTAR[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGNETON[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAGNEZONE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAKUHITA[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MALAMAR[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MANDIBUZZ[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MANECTRIC[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAREEP[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAROWAK[] =
{
    MOVE_HEX,
    MOVE_SING,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MASQUERAIN[] =
{
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAUSHOLD[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MAWILE[] =
{
    MOVE_SING,
    MOVE_VISE_GRIP,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MELOETTA[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MEOWTH[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_PETAL_DANCE,
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_METAGROSS[] =
{
    MOVE_HOLD_BACK,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_METANG[] =
{
    MOVE_HOLD_BACK,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MEW[] =
{
    MOVE_FAKE_OUT,
    MOVE_FEINT_ATTACK,
    MOVE_HYPNOSIS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MEWTWO[] =
{
    MOVE_HEAL_PULSE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MIGHTYENA[] =
{
    MOVE_HEAL_BELL,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MILCERY[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MIMIKYU[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MINUN[] =
{
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MOLTRES[] =
{
    MOVE_EXTRASENSORY,
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MR_MIME[] =
{
    MOVE_FOLLOW_ME,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_MUNCHLAX[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_NINETALES_ALOLA[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_NUZLEAF[] =
{
    MOVE_BIDE,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ORTHWORM[] =
{
    MOVE_HEADBUTT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PARAS[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PARASECT[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PAWMI[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PAWMO[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PAWMOT[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PERSIAN[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_PETAL_DANCE,
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PHEROMOSA[] =
{
    MOVE_HIGH_JUMP_KICK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PICHU[] =
{
    MOVE_ENDEAVOR,
    MOVE_FOLLOW_ME,
    MOVE_PAIN_SPLIT,
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PIDGEOT[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PIDGEOTTO[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PIKACHU[] =
{
    MOVE_CELEBRATE,
    MOVE_EXTREME_SPEED,
    MOVE_FLY,
    MOVE_FOLLOW_ME,
    MOVE_HAPPY_HOUR,
    MOVE_HEART_STAMP,
    MOVE_HOLD_HANDS,
    MOVE_LAST_RESORT,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SWEET_SCENT,
    MOVE_TEETER_DANCE,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PINECO[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PIPLUP[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PLUSLE[] =
{
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POLITOED[] =
{
    MOVE_BUBBLE,
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POLIWAG[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POLIWHIRL[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POLIWRATH[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POLTEAGEIST[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_POOCHYENA[] =
{
    MOVE_HEAL_BELL,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PORYGON2[] =
{
    MOVE_SHARPEN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PORYGON_Z[] =
{
    MOVE_SHARPEN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PRINPLUP[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_PSYDUCK[] =
{
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_QUILAVA[] =
{
    MOVE_BLAST_BURN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RAICHU[] =
{
    MOVE_CELEBRATE,
    MOVE_EXTREME_SPEED,
    MOVE_FLY,
    MOVE_FOLLOW_ME,
    MOVE_HAPPY_HOUR,
    MOVE_HEART_STAMP,
    MOVE_HOLD_HANDS,
    MOVE_LAST_RESORT,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SWEET_SCENT,
    MOVE_TEETER_DANCE,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RAICHU_ALOLA[] =
{
    MOVE_CELEBRATE,
    MOVE_COUNTER,
    MOVE_EXTREME_SPEED,
    MOVE_FLASH,
    MOVE_FLY,
    MOVE_FOLLOW_ME,
    MOVE_HAPPY_HOUR,
    MOVE_HEART_STAMP,
    MOVE_HOLD_HANDS,
    MOVE_LAST_RESORT,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SWEET_SCENT,
    MOVE_TEETER_DANCE,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RALTS[] =
{
    MOVE_SING,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RATICATE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RAYQUAZA[] =
{
    MOVE_CELEBRATE,
    MOVE_V_CREATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_RESHIRAM[] =
{
    MOVE_MIST,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ROCKRUFF[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ROSELIA[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ROSERADE[] =
{
    MOVE_SWEET_KISS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ROTOM[] =
{
    MOVE_DISARMING_VOICE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SABLEYE[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_OCTAZOOKA,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SALAMENCE[] =
{
    MOVE_REFRESH,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SAMUROTT[] =
{
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SAWSBUCK[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SCIZOR[] =
{
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SCYTHER[] =
{
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SEALEO[] =
{
    MOVE_CHARM,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SEEDOT[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SERPERIOR[] =
{
    MOVE_AROMATHERAPY,
    MOVE_HOLD_BACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SERVINE[] =
{
    MOVE_AROMATHERAPY,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHARPEDO[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHAYMIN_LAND[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHELGON[] =
{
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHELLDER[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHIFTRY[] =
{
    MOVE_BIDE,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHROOMISH[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SHUPPET[] =
{
    MOVE_FEINT_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SINISTEA[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SKITTY[] =
{
    MOVE_PAY_DAY,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SMEARGLE[] =
{
    MOVE_DOUBLE_SLAP,
    MOVE_FALSE_SWIPE,
    MOVE_FLAMETHROWER,
    MOVE_FURY_SWIPES,
    MOVE_IRON_TAIL,
    MOVE_MEAN_LOOK,
    MOVE_ODOR_SLEUTH,
    MOVE_SEISMIC_TOSS,
    MOVE_SPORE,
    MOVE_TAIL_WHIP,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SNIVY[] =
{
    MOVE_AROMATHERAPY,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SNORLAX[] =
{
    MOVE_CELEBRATE,
    MOVE_HAPPY_HOUR,
    MOVE_HOLD_BACK,
    MOVE_ODOR_SLEUTH,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SNORUNT[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SOLGALEO[] =
{
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SPEAROW[] =
{
    MOVE_BATON_PASS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SPHEAL[] =
{
    MOVE_CHARM,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SPINARAK[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SPINDA[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SQUIRTLE[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_FOLLOW_ME,
    MOVE_HYDRO_CANNON,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_STARMIE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_STEENEE[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SUICUNE[] =
{
    MOVE_AQUA_RING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SURSKIT[] =
{
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SWALOT[] =
{
    MOVE_SING,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SWELLOW[] =
{
    MOVE_BATON_PASS,
    MOVE_FEATHER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_SYLVEON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TAILLOW[] =
{
    MOVE_FEATHER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TANDEMAUS[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TANGELA[] =
{
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TANGROWTH[] =
{
    MOVE_MORNING_SUN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TATSUGIRI[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TAUROS[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TEDDIURSA[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TOEDSCOOL[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TOEDSCRUEL[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TOTODILE[] =
{
    MOVE_HYDRO_CANNON,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_TSAREENA[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_UMBREON[] =
{
    MOVE_CELEBRATE,
    MOVE_FEINT_ATTACK,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_URSALUNA[] =
{
    MOVE_REFRESH,
    MOVE_RETURN,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_URSARING[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VAPOREON[] =
{
    MOVE_CELEBRATE,
    MOVE_SING,
    MOVE_TRUMP_CARD,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VENOMOTH[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VENUSAUR[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VICTINI[] =
{
    MOVE_BLUE_FLARE,
    MOVE_BOLT_STRIKE,
    MOVE_CELEBRATE,
    MOVE_FUSION_BOLT,
    MOVE_FUSION_FLARE,
    MOVE_GLACIATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VICTREEBEL[] =
{
    MOVE_MORNING_SUN,
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VIVILLON[] =
{
    MOVE_HOLD_HANDS,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VOLTORB[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_VULPIX_ALOLA[] =
{
    MOVE_CELEBRATE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WALREIN[] =
{
    MOVE_CHARM,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WARTORTLE[] =
{
    MOVE_BLOCK,
    MOVE_CELEBRATE,
    MOVE_FOLLOW_ME,
    MOVE_HYDRO_CANNON,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WEEPINBELL[] =
{
    MOVE_MORNING_SUN,
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WHISMUR[] =
{
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WIGGLYTUFF[] =
{
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WOBBUFFET[] =
{
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_WYNAUT[] =
{
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ZANGOOSE[] =
{
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ZAPDOS[] =
{
    MOVE_EXTRASENSORY,
    MOVE_UNAVAILABLE,
};

static const u16 sFrontierEventLearnset_SPECIES_ZOROARK_HISUI[] =
{
    MOVE_HAPPY_HOUR,
    MOVE_UNAVAILABLE,
};

static const u16 *const sFrontierEventLearnsets[NUM_SPECIES] =
{
    [SPECIES_ABSOL] = sFrontierEventLearnset_SPECIES_ABSOL,
    [SPECIES_AERODACTYL] = sFrontierEventLearnset_SPECIES_AERODACTYL,
    [SPECIES_ALCREMIE] = sFrontierEventLearnset_SPECIES_ALCREMIE,
    [SPECIES_AMPHAROS] = sFrontierEventLearnset_SPECIES_AMPHAROS,
    [SPECIES_ARBOK] = sFrontierEventLearnset_SPECIES_ARBOK,
    [SPECIES_ARCEUS] = sFrontierEventLearnset_SPECIES_ARCEUS,
    [SPECIES_ARIADOS] = sFrontierEventLearnset_SPECIES_ARIADOS,
    [SPECIES_ARMAROUGE] = sFrontierEventLearnset_SPECIES_ARMAROUGE,
    [SPECIES_ARTICUNO] = sFrontierEventLearnset_SPECIES_ARTICUNO,
    [SPECIES_AUDINO] = sFrontierEventLearnset_SPECIES_AUDINO,
    [SPECIES_BAGON] = sFrontierEventLearnset_SPECIES_BAGON,
    [SPECIES_BALTOY] = sFrontierEventLearnset_SPECIES_BALTOY,
    [SPECIES_BANETTE] = sFrontierEventLearnset_SPECIES_BANETTE,
    [SPECIES_BAYLEEF] = sFrontierEventLearnset_SPECIES_BAYLEEF,
    [SPECIES_BEEDRILL] = sFrontierEventLearnset_SPECIES_BEEDRILL,
    [SPECIES_BELDUM] = sFrontierEventLearnset_SPECIES_BELDUM,
    [SPECIES_BELLSPROUT] = sFrontierEventLearnset_SPECIES_BELLSPROUT,
    [SPECIES_BLASTOISE] = sFrontierEventLearnset_SPECIES_BLASTOISE,
    [SPECIES_BLAZIKEN] = sFrontierEventLearnset_SPECIES_BLAZIKEN,
    [SPECIES_BLISSEY] = sFrontierEventLearnset_SPECIES_BLISSEY,
    [SPECIES_BRELOOM] = sFrontierEventLearnset_SPECIES_BRELOOM,
    [SPECIES_BULBASAUR] = sFrontierEventLearnset_SPECIES_BULBASAUR,
    [SPECIES_BUTTERFREE] = sFrontierEventLearnset_SPECIES_BUTTERFREE,
    [SPECIES_CACTURNE] = sFrontierEventLearnset_SPECIES_CACTURNE,
    [SPECIES_CARVANHA] = sFrontierEventLearnset_SPECIES_CARVANHA,
    [SPECIES_CELEBI] = sFrontierEventLearnset_SPECIES_CELEBI,
    [SPECIES_CERULEDGE] = sFrontierEventLearnset_SPECIES_CERULEDGE,
    [SPECIES_CHANSEY] = sFrontierEventLearnset_SPECIES_CHANSEY,
    [SPECIES_CHARCADET] = sFrontierEventLearnset_SPECIES_CHARCADET,
    [SPECIES_CHARIZARD] = sFrontierEventLearnset_SPECIES_CHARIZARD,
    [SPECIES_CHARMANDER] = sFrontierEventLearnset_SPECIES_CHARMANDER,
    [SPECIES_CHARMELEON] = sFrontierEventLearnset_SPECIES_CHARMELEON,
    [SPECIES_CHIKORITA] = sFrontierEventLearnset_SPECIES_CHIKORITA,
    [SPECIES_CLAYDOL] = sFrontierEventLearnset_SPECIES_CLAYDOL,
    [SPECIES_CLOYSTER] = sFrontierEventLearnset_SPECIES_CLOYSTER,
    [SPECIES_COMFEY] = sFrontierEventLearnset_SPECIES_COMFEY,
    [SPECIES_CORPHISH] = sFrontierEventLearnset_SPECIES_CORPHISH,
    [SPECIES_CORSOLA] = sFrontierEventLearnset_SPECIES_CORSOLA,
    [SPECIES_COSMOEM] = sFrontierEventLearnset_SPECIES_COSMOEM,
    [SPECIES_CRAWDAUNT] = sFrontierEventLearnset_SPECIES_CRAWDAUNT,
    [SPECIES_CROCONAW] = sFrontierEventLearnset_SPECIES_CROCONAW,
    [SPECIES_CYNDAQUIL] = sFrontierEventLearnset_SPECIES_CYNDAQUIL,
    [SPECIES_DARKRAI] = sFrontierEventLearnset_SPECIES_DARKRAI,
    [SPECIES_DEERLING] = sFrontierEventLearnset_SPECIES_DEERLING,
    [SPECIES_DELCATTY] = sFrontierEventLearnset_SPECIES_DELCATTY,
    [SPECIES_DELIBIRD] = sFrontierEventLearnset_SPECIES_DELIBIRD,
    [SPECIES_DEOXYS_NORMAL] = sFrontierEventLearnset_SPECIES_DEOXYS_NORMAL,
    [SPECIES_DRAGONITE] = sFrontierEventLearnset_SPECIES_DRAGONITE,
    [SPECIES_DROWZEE] = sFrontierEventLearnset_SPECIES_DROWZEE,
    [SPECIES_EEVEE] = sFrontierEventLearnset_SPECIES_EEVEE,
    [SPECIES_ELECTRODE] = sFrontierEventLearnset_SPECIES_ELECTRODE,
    [SPECIES_EMBOAR] = sFrontierEventLearnset_SPECIES_EMBOAR,
    [SPECIES_EMPOLEON] = sFrontierEventLearnset_SPECIES_EMPOLEON,
    [SPECIES_ENTEI] = sFrontierEventLearnset_SPECIES_ENTEI,
    [SPECIES_ESPEON] = sFrontierEventLearnset_SPECIES_ESPEON,
    [SPECIES_EXEGGCUTE] = sFrontierEventLearnset_SPECIES_EXEGGCUTE,
    [SPECIES_EXEGGUTOR] = sFrontierEventLearnset_SPECIES_EXEGGUTOR,
    [SPECIES_EXEGGUTOR_ALOLA] = sFrontierEventLearnset_SPECIES_EXEGGUTOR_ALOLA,
    [SPECIES_EXPLOUD] = sFrontierEventLearnset_SPECIES_EXPLOUD,
    [SPECIES_FARFETCHD] = sFrontierEventLearnset_SPECIES_FARFETCHD,
    [SPECIES_FEAROW] = sFrontierEventLearnset_SPECIES_FEAROW,
    [SPECIES_FLAAFFY] = sFrontierEventLearnset_SPECIES_FLAAFFY,
    [SPECIES_FLABEBE] = sFrontierEventLearnset_SPECIES_FLABEBE,
    [SPECIES_FLAREON] = sFrontierEventLearnset_SPECIES_FLAREON,
    [SPECIES_FLOETTE] = sFrontierEventLearnset_SPECIES_FLOETTE,
    [SPECIES_FLORGES] = sFrontierEventLearnset_SPECIES_FLORGES,
    [SPECIES_FORRETRESS] = sFrontierEventLearnset_SPECIES_FORRETRESS,
    [SPECIES_FROSLASS] = sFrontierEventLearnset_SPECIES_FROSLASS,
    [SPECIES_GALLADE] = sFrontierEventLearnset_SPECIES_GALLADE,
    [SPECIES_GARDEVOIR] = sFrontierEventLearnset_SPECIES_GARDEVOIR,
    [SPECIES_GENESECT] = sFrontierEventLearnset_SPECIES_GENESECT,
    [SPECIES_GLACEON] = sFrontierEventLearnset_SPECIES_GLACEON,
    [SPECIES_GLALIE] = sFrontierEventLearnset_SPECIES_GLALIE,
    [SPECIES_GOLDUCK] = sFrontierEventLearnset_SPECIES_GOLDUCK,
    [SPECIES_GRENINJA] = sFrontierEventLearnset_SPECIES_GRENINJA,
    [SPECIES_GULPIN] = sFrontierEventLearnset_SPECIES_GULPIN,
    [SPECIES_GYARADOS] = sFrontierEventLearnset_SPECIES_GYARADOS,
    [SPECIES_HARIYAMA] = sFrontierEventLearnset_SPECIES_HARIYAMA,
    [SPECIES_HEATRAN] = sFrontierEventLearnset_SPECIES_HEATRAN,
    [SPECIES_HITMONLEE] = sFrontierEventLearnset_SPECIES_HITMONLEE,
    [SPECIES_HOUNDOOM] = sFrontierEventLearnset_SPECIES_HOUNDOOM,
    [SPECIES_HOUNDOUR] = sFrontierEventLearnset_SPECIES_HOUNDOUR,
    [SPECIES_HO_OH] = sFrontierEventLearnset_SPECIES_HO_OH,
    [SPECIES_HYPNO] = sFrontierEventLearnset_SPECIES_HYPNO,
    [SPECIES_IGGLYBUFF] = sFrontierEventLearnset_SPECIES_IGGLYBUFF,
    [SPECIES_INKAY] = sFrontierEventLearnset_SPECIES_INKAY,
    [SPECIES_IVYSAUR] = sFrontierEventLearnset_SPECIES_IVYSAUR,
    [SPECIES_JIGGLYPUFF] = sFrontierEventLearnset_SPECIES_JIGGLYPUFF,
    [SPECIES_JIRACHI] = sFrontierEventLearnset_SPECIES_JIRACHI,
    [SPECIES_JOLTEON] = sFrontierEventLearnset_SPECIES_JOLTEON,
    [SPECIES_JUMPLUFF] = sFrontierEventLearnset_SPECIES_JUMPLUFF,
    [SPECIES_KANGASKHAN] = sFrontierEventLearnset_SPECIES_KANGASKHAN,
    [SPECIES_KIRLIA] = sFrontierEventLearnset_SPECIES_KIRLIA,
    [SPECIES_KLAWF] = sFrontierEventLearnset_SPECIES_KLAWF,
    [SPECIES_KLEAVOR] = sFrontierEventLearnset_SPECIES_KLEAVOR,
    [SPECIES_LATIAS] = sFrontierEventLearnset_SPECIES_LATIAS,
    [SPECIES_LEAFEON] = sFrontierEventLearnset_SPECIES_LEAFEON,
    [SPECIES_LEDIAN] = sFrontierEventLearnset_SPECIES_LEDIAN,
    [SPECIES_LEDYBA] = sFrontierEventLearnset_SPECIES_LEDYBA,
    [SPECIES_LICKILICKY] = sFrontierEventLearnset_SPECIES_LICKILICKY,
    [SPECIES_LICKITUNG] = sFrontierEventLearnset_SPECIES_LICKITUNG,
    [SPECIES_LOUDRED] = sFrontierEventLearnset_SPECIES_LOUDRED,
    [SPECIES_LUCARIO] = sFrontierEventLearnset_SPECIES_LUCARIO,
    [SPECIES_LUGIA] = sFrontierEventLearnset_SPECIES_LUGIA,
    [SPECIES_LUNALA] = sFrontierEventLearnset_SPECIES_LUNALA,
    [SPECIES_LYCANROC_DUSK] = sFrontierEventLearnset_SPECIES_LYCANROC_DUSK,
    [SPECIES_MAGCARGO] = sFrontierEventLearnset_SPECIES_MAGCARGO,
    [SPECIES_MAGIKARP] = sFrontierEventLearnset_SPECIES_MAGIKARP,
    [SPECIES_MAGMAR] = sFrontierEventLearnset_SPECIES_MAGMAR,
    [SPECIES_MAGMORTAR] = sFrontierEventLearnset_SPECIES_MAGMORTAR,
    [SPECIES_MAGNETON] = sFrontierEventLearnset_SPECIES_MAGNETON,
    [SPECIES_MAGNEZONE] = sFrontierEventLearnset_SPECIES_MAGNEZONE,
    [SPECIES_MAKUHITA] = sFrontierEventLearnset_SPECIES_MAKUHITA,
    [SPECIES_MALAMAR] = sFrontierEventLearnset_SPECIES_MALAMAR,
    [SPECIES_MANDIBUZZ] = sFrontierEventLearnset_SPECIES_MANDIBUZZ,
    [SPECIES_MANECTRIC] = sFrontierEventLearnset_SPECIES_MANECTRIC,
    [SPECIES_MAREEP] = sFrontierEventLearnset_SPECIES_MAREEP,
    [SPECIES_MAROWAK] = sFrontierEventLearnset_SPECIES_MAROWAK,
    [SPECIES_MASQUERAIN] = sFrontierEventLearnset_SPECIES_MASQUERAIN,
    [SPECIES_MAUSHOLD] = sFrontierEventLearnset_SPECIES_MAUSHOLD,
    [SPECIES_MAWILE] = sFrontierEventLearnset_SPECIES_MAWILE,
    [SPECIES_MELOETTA] = sFrontierEventLearnset_SPECIES_MELOETTA,
    [SPECIES_MEOWTH] = sFrontierEventLearnset_SPECIES_MEOWTH,
    [SPECIES_METAGROSS] = sFrontierEventLearnset_SPECIES_METAGROSS,
    [SPECIES_METANG] = sFrontierEventLearnset_SPECIES_METANG,
    [SPECIES_MEW] = sFrontierEventLearnset_SPECIES_MEW,
    [SPECIES_MEWTWO] = sFrontierEventLearnset_SPECIES_MEWTWO,
    [SPECIES_MIGHTYENA] = sFrontierEventLearnset_SPECIES_MIGHTYENA,
    [SPECIES_MILCERY] = sFrontierEventLearnset_SPECIES_MILCERY,
    [SPECIES_MIMIKYU] = sFrontierEventLearnset_SPECIES_MIMIKYU,
    [SPECIES_MINUN] = sFrontierEventLearnset_SPECIES_MINUN,
    [SPECIES_MOLTRES] = sFrontierEventLearnset_SPECIES_MOLTRES,
    [SPECIES_MR_MIME] = sFrontierEventLearnset_SPECIES_MR_MIME,
    [SPECIES_MUNCHLAX] = sFrontierEventLearnset_SPECIES_MUNCHLAX,
    [SPECIES_NINETALES_ALOLA] = sFrontierEventLearnset_SPECIES_NINETALES_ALOLA,
    [SPECIES_NUZLEAF] = sFrontierEventLearnset_SPECIES_NUZLEAF,
    [SPECIES_ORTHWORM] = sFrontierEventLearnset_SPECIES_ORTHWORM,
    [SPECIES_PARAS] = sFrontierEventLearnset_SPECIES_PARAS,
    [SPECIES_PARASECT] = sFrontierEventLearnset_SPECIES_PARASECT,
    [SPECIES_PAWMI] = sFrontierEventLearnset_SPECIES_PAWMI,
    [SPECIES_PAWMO] = sFrontierEventLearnset_SPECIES_PAWMO,
    [SPECIES_PAWMOT] = sFrontierEventLearnset_SPECIES_PAWMOT,
    [SPECIES_PERSIAN] = sFrontierEventLearnset_SPECIES_PERSIAN,
    [SPECIES_PHEROMOSA] = sFrontierEventLearnset_SPECIES_PHEROMOSA,
    [SPECIES_PICHU] = sFrontierEventLearnset_SPECIES_PICHU,
    [SPECIES_PIDGEOT] = sFrontierEventLearnset_SPECIES_PIDGEOT,
    [SPECIES_PIDGEOTTO] = sFrontierEventLearnset_SPECIES_PIDGEOTTO,
    [SPECIES_PIKACHU] = sFrontierEventLearnset_SPECIES_PIKACHU,
    [SPECIES_PINECO] = sFrontierEventLearnset_SPECIES_PINECO,
    [SPECIES_PIPLUP] = sFrontierEventLearnset_SPECIES_PIPLUP,
    [SPECIES_PLUSLE] = sFrontierEventLearnset_SPECIES_PLUSLE,
    [SPECIES_POLITOED] = sFrontierEventLearnset_SPECIES_POLITOED,
    [SPECIES_POLIWAG] = sFrontierEventLearnset_SPECIES_POLIWAG,
    [SPECIES_POLIWHIRL] = sFrontierEventLearnset_SPECIES_POLIWHIRL,
    [SPECIES_POLIWRATH] = sFrontierEventLearnset_SPECIES_POLIWRATH,
    [SPECIES_POLTEAGEIST] = sFrontierEventLearnset_SPECIES_POLTEAGEIST,
    [SPECIES_POOCHYENA] = sFrontierEventLearnset_SPECIES_POOCHYENA,
    [SPECIES_PORYGON2] = sFrontierEventLearnset_SPECIES_PORYGON2,
    [SPECIES_PORYGON_Z] = sFrontierEventLearnset_SPECIES_PORYGON_Z,
    [SPECIES_PRINPLUP] = sFrontierEventLearnset_SPECIES_PRINPLUP,
    [SPECIES_PSYDUCK] = sFrontierEventLearnset_SPECIES_PSYDUCK,
    [SPECIES_QUILAVA] = sFrontierEventLearnset_SPECIES_QUILAVA,
    [SPECIES_RAICHU] = sFrontierEventLearnset_SPECIES_RAICHU,
    [SPECIES_RAICHU_ALOLA] = sFrontierEventLearnset_SPECIES_RAICHU_ALOLA,
    [SPECIES_RALTS] = sFrontierEventLearnset_SPECIES_RALTS,
    [SPECIES_RATICATE] = sFrontierEventLearnset_SPECIES_RATICATE,
    [SPECIES_RAYQUAZA] = sFrontierEventLearnset_SPECIES_RAYQUAZA,
    [SPECIES_RESHIRAM] = sFrontierEventLearnset_SPECIES_RESHIRAM,
    [SPECIES_ROCKRUFF] = sFrontierEventLearnset_SPECIES_ROCKRUFF,
    [SPECIES_ROSELIA] = sFrontierEventLearnset_SPECIES_ROSELIA,
    [SPECIES_ROSERADE] = sFrontierEventLearnset_SPECIES_ROSERADE,
    [SPECIES_ROTOM] = sFrontierEventLearnset_SPECIES_ROTOM,
    [SPECIES_SABLEYE] = sFrontierEventLearnset_SPECIES_SABLEYE,
    [SPECIES_SALAMENCE] = sFrontierEventLearnset_SPECIES_SALAMENCE,
    [SPECIES_SAMUROTT] = sFrontierEventLearnset_SPECIES_SAMUROTT,
    [SPECIES_SAWSBUCK] = sFrontierEventLearnset_SPECIES_SAWSBUCK,
    [SPECIES_SCIZOR] = sFrontierEventLearnset_SPECIES_SCIZOR,
    [SPECIES_SCYTHER] = sFrontierEventLearnset_SPECIES_SCYTHER,
    [SPECIES_SEALEO] = sFrontierEventLearnset_SPECIES_SEALEO,
    [SPECIES_SEEDOT] = sFrontierEventLearnset_SPECIES_SEEDOT,
    [SPECIES_SERPERIOR] = sFrontierEventLearnset_SPECIES_SERPERIOR,
    [SPECIES_SERVINE] = sFrontierEventLearnset_SPECIES_SERVINE,
    [SPECIES_SHARPEDO] = sFrontierEventLearnset_SPECIES_SHARPEDO,
    [SPECIES_SHAYMIN_LAND] = sFrontierEventLearnset_SPECIES_SHAYMIN_LAND,
    [SPECIES_SHELGON] = sFrontierEventLearnset_SPECIES_SHELGON,
    [SPECIES_SHELLDER] = sFrontierEventLearnset_SPECIES_SHELLDER,
    [SPECIES_SHIFTRY] = sFrontierEventLearnset_SPECIES_SHIFTRY,
    [SPECIES_SHROOMISH] = sFrontierEventLearnset_SPECIES_SHROOMISH,
    [SPECIES_SHUPPET] = sFrontierEventLearnset_SPECIES_SHUPPET,
    [SPECIES_SINISTEA] = sFrontierEventLearnset_SPECIES_SINISTEA,
    [SPECIES_SKITTY] = sFrontierEventLearnset_SPECIES_SKITTY,
    [SPECIES_SMEARGLE] = sFrontierEventLearnset_SPECIES_SMEARGLE,
    [SPECIES_SNIVY] = sFrontierEventLearnset_SPECIES_SNIVY,
    [SPECIES_SNORLAX] = sFrontierEventLearnset_SPECIES_SNORLAX,
    [SPECIES_SNORUNT] = sFrontierEventLearnset_SPECIES_SNORUNT,
    [SPECIES_SOLGALEO] = sFrontierEventLearnset_SPECIES_SOLGALEO,
    [SPECIES_SPEAROW] = sFrontierEventLearnset_SPECIES_SPEAROW,
    [SPECIES_SPHEAL] = sFrontierEventLearnset_SPECIES_SPHEAL,
    [SPECIES_SPINARAK] = sFrontierEventLearnset_SPECIES_SPINARAK,
    [SPECIES_SPINDA] = sFrontierEventLearnset_SPECIES_SPINDA,
    [SPECIES_SQUIRTLE] = sFrontierEventLearnset_SPECIES_SQUIRTLE,
    [SPECIES_STARMIE] = sFrontierEventLearnset_SPECIES_STARMIE,
    [SPECIES_STEENEE] = sFrontierEventLearnset_SPECIES_STEENEE,
    [SPECIES_SUICUNE] = sFrontierEventLearnset_SPECIES_SUICUNE,
    [SPECIES_SURSKIT] = sFrontierEventLearnset_SPECIES_SURSKIT,
    [SPECIES_SWALOT] = sFrontierEventLearnset_SPECIES_SWALOT,
    [SPECIES_SWELLOW] = sFrontierEventLearnset_SPECIES_SWELLOW,
    [SPECIES_SYLVEON] = sFrontierEventLearnset_SPECIES_SYLVEON,
    [SPECIES_TAILLOW] = sFrontierEventLearnset_SPECIES_TAILLOW,
    [SPECIES_TANDEMAUS] = sFrontierEventLearnset_SPECIES_TANDEMAUS,
    [SPECIES_TANGELA] = sFrontierEventLearnset_SPECIES_TANGELA,
    [SPECIES_TANGROWTH] = sFrontierEventLearnset_SPECIES_TANGROWTH,
    [SPECIES_TATSUGIRI] = sFrontierEventLearnset_SPECIES_TATSUGIRI,
    [SPECIES_TAUROS] = sFrontierEventLearnset_SPECIES_TAUROS,
    [SPECIES_TEDDIURSA] = sFrontierEventLearnset_SPECIES_TEDDIURSA,
    [SPECIES_TOEDSCOOL] = sFrontierEventLearnset_SPECIES_TOEDSCOOL,
    [SPECIES_TOEDSCRUEL] = sFrontierEventLearnset_SPECIES_TOEDSCRUEL,
    [SPECIES_TOTODILE] = sFrontierEventLearnset_SPECIES_TOTODILE,
    [SPECIES_TSAREENA] = sFrontierEventLearnset_SPECIES_TSAREENA,
    [SPECIES_UMBREON] = sFrontierEventLearnset_SPECIES_UMBREON,
    [SPECIES_URSALUNA] = sFrontierEventLearnset_SPECIES_URSALUNA,
    [SPECIES_URSARING] = sFrontierEventLearnset_SPECIES_URSARING,
    [SPECIES_VAPOREON] = sFrontierEventLearnset_SPECIES_VAPOREON,
    [SPECIES_VENOMOTH] = sFrontierEventLearnset_SPECIES_VENOMOTH,
    [SPECIES_VENUSAUR] = sFrontierEventLearnset_SPECIES_VENUSAUR,
    [SPECIES_VICTINI] = sFrontierEventLearnset_SPECIES_VICTINI,
    [SPECIES_VICTREEBEL] = sFrontierEventLearnset_SPECIES_VICTREEBEL,
    [SPECIES_VIVILLON] = sFrontierEventLearnset_SPECIES_VIVILLON,
    [SPECIES_VOLTORB] = sFrontierEventLearnset_SPECIES_VOLTORB,
    [SPECIES_VULPIX_ALOLA] = sFrontierEventLearnset_SPECIES_VULPIX_ALOLA,
    [SPECIES_WALREIN] = sFrontierEventLearnset_SPECIES_WALREIN,
    [SPECIES_WARTORTLE] = sFrontierEventLearnset_SPECIES_WARTORTLE,
    [SPECIES_WEEPINBELL] = sFrontierEventLearnset_SPECIES_WEEPINBELL,
    [SPECIES_WHISMUR] = sFrontierEventLearnset_SPECIES_WHISMUR,
    [SPECIES_WIGGLYTUFF] = sFrontierEventLearnset_SPECIES_WIGGLYTUFF,
    [SPECIES_WOBBUFFET] = sFrontierEventLearnset_SPECIES_WOBBUFFET,
    [SPECIES_WYNAUT] = sFrontierEventLearnset_SPECIES_WYNAUT,
    [SPECIES_ZANGOOSE] = sFrontierEventLearnset_SPECIES_ZANGOOSE,
    [SPECIES_ZAPDOS] = sFrontierEventLearnset_SPECIES_ZAPDOS,
    [SPECIES_ZOROARK_HISUI] = sFrontierEventLearnset_SPECIES_ZOROARK_HISUI,
};

#endif // GUARD_FRONTIER_EVENT_LEARNSETS_H
