#include "global.h"
#include "event_data.h"
#include "event_object_movement.h"
#include "field_message_box.h"
#include "field_screen_effect.h"
#include "main.h"
#include "malloc.h"
#include "map_name_popup.h"
#include "menu.h"
#include "m4a.h"
#include "overworld.h"
#include "pokemon.h"
#include "pokemon_storage_system.h"
#include "script.h"
#include "script_pokemon_util.h"
#include "sound.h"
#include "sprite.h"
#include "string_util.h"
#include "task.h"
#include "text.h"
#include "trainer_pokemon_sprites.h"
#include "constants/abilities.h"
#include "constants/flags.h"
#include "constants/items.h"
#include "constants/pokemon.h"
#include "constants/songs.h"
#include "constants/species.h"
#include "constants/vars.h"
#include "data.h"
#include "item.h"
#include "pokedex.h"

#define FRONTIER_CREATOR_FONT FONT_NORMAL

#define FRONTIER_CREATOR_LEVEL_50  50
#define FRONTIER_CREATOR_LEVEL_100 100
#define FRONTIER_CREATOR_DYNAMAX_LEVEL 10
#define FRONTIER_CREATOR_MAX_TOTAL_EVS 510
#define FRONTIER_CREATOR_MAX_PER_STAT_EVS 252
#define FRONTIER_CREATOR_MAX_IVS 31

#define FRONTIER_HUB_INITIAL_GIFT_LEVEL 100
#define FRONTIER_HUB_INITIAL_GIFT_DYNAMAX_LEVEL 10
#define FRONTIER_HUB_INITIAL_GIFT_IVS 31

#define FRONTIER_CREATOR_SPECIES_DIGITS 4
#define FRONTIER_CREATOR_NATURE_DIGITS  2
#define FRONTIER_CREATOR_ABILITY_DIGITS 1
#define FRONTIER_CREATOR_TYPE_DIGITS    2
#define FRONTIER_CREATOR_IV_DIGITS      2
#define FRONTIER_CREATOR_EV_DIGITS      3
#define FRONTIER_ITEM_GIVER_DIGITS      3
#define FRONTIER_CREATOR_PREVIEW_X      196
#define FRONTIER_CREATOR_PREVIEW_Y      40
#define FRONTIER_CREATOR_PREVIEW_PAL    14
#define FRONTIER_CREATOR_PREVIEW_NONE   MAX_SPRITES

#define tItemIndex data[1]

struct FrontierCreatorData
{
    enum Species species;
    u8 level;
    u8 nature;
    u8 abilityNum;
    u8 teraType;
    bool8 gmaxFactor;
    u8 ivs[NUM_STATS];
    u8 evs[NUM_STATS];
};

struct FrontierHubAutoItem
{
    enum Item itemId;
    u16 quantity;
};

struct FrontierHubInitialGiftMon
{
    enum Species species;
    enum Item itemId;
    enum Ability ability;
    u8 nature;
    enum Type teraType;
    bool8 gmaxFactor;
    u8 evs[NUM_STATS];
    enum Move moves[MAX_MON_MOVES];
};

static EWRAM_DATA struct FrontierCreatorData *sFrontierCreatorData = NULL;

#define tWindowId data[0]
#define tInput    data[1]
#define tDigit    data[2]
#define tStatId   data[3]
#define tPreviewSpriteId data[4]
#define tPreviewSpecies  data[5]

static void Task_FrontierCreator_SelectSpecies(u8 taskId);
static void Task_FrontierCreator_SelectLevel(u8 taskId);
static void Task_FrontierCreator_SelectNature(u8 taskId);
static void Task_FrontierCreator_SelectAbility(u8 taskId);
static void Task_FrontierCreator_SelectTeraType(u8 taskId);
static void Task_FrontierCreator_SelectGmax(u8 taskId);
static void Task_FrontierCreator_SelectIVs(u8 taskId);
static void Task_FrontierCreator_SelectEVs(u8 taskId);

static void FrontierCreator_DestroyAndReturn(u8 taskId);
static void FrontierCreator_CreateMonAndGive(void);
static void FrontierCreator_InitDefaultData(void);
static void FrontierCreator_DrawAbilityScreen(u8 taskId);

static void Task_FrontierItemGiver_SelectItem(u8 taskId);
static void FrontierItemGiver_DrawScreen(u8 taskId);
static u16 FrontierItemGiver_GetItemCount(void);
static void FrontierItemGiver_DestroyAndReturn(u8 taskId);
static void FrontierHub_GiveGimmickKeyItems(void);
static void FrontierHub_GiveAutoItems(void);
static void FrontierHub_TryGiveInitialParty(void);
static void FrontierHub_CreateInitialGiftMon(const struct FrontierHubInitialGiftMon *gift, struct Pokemon *mon);
static u8 FrontierHub_GetAbilityNum(enum Species species, enum Ability ability);

static enum Species FrontierCreator_GetFirstAllowedSpecies(void);
static enum Species FrontierCreator_GetNextAllowedSpecies(enum Species species, s16 delta);
static void FrontierCreator_HandleSpeciesInput(u8 taskId);
static void FrontierCreator_UpdateSpeciesPreview(u8 taskId, enum Species species, bool8 playCry);
static void FrontierCreator_DestroySpeciesPreview(u8 taskId);

static const struct WindowTemplate sFrontierCreatorWindowTemplate =
{
    .bg = 0,
    .tilemapLeft = 1,
    .tilemapTop = 1,
    .width = 28,
    .height = 8,
    .paletteNum = 15,
    .baseBlock = 1,
};

static const s32 sFrontierCreatorPowersOfTen[] =
{
    1,
    10,
    100,
    1000,
    10000,
};

static const u8 *const sFrontierCreatorStatNames[NUM_STATS] =
{
    COMPOUND_STRING("HP"),
    COMPOUND_STRING("こうげき"),
    COMPOUND_STRING("ぼうぎょ"),
    COMPOUND_STRING("すばやさ"),
    COMPOUND_STRING("とくこう"),
    COMPOUND_STRING("とくぼう"),
};

static const u8 *const sFrontierCreatorTypeNames[NUMBER_OF_MON_TYPES] =
{
    [TYPE_NONE] = COMPOUND_STRING("----"),
    [TYPE_NORMAL] = COMPOUND_STRING("ノーマル"),
    [TYPE_FIGHTING] = COMPOUND_STRING("かくとう"),
    [TYPE_FLYING] = COMPOUND_STRING("ひこう"),
    [TYPE_POISON] = COMPOUND_STRING("どく"),
    [TYPE_GROUND] = COMPOUND_STRING("じめん"),
    [TYPE_ROCK] = COMPOUND_STRING("いわ"),
    [TYPE_BUG] = COMPOUND_STRING("むし"),
    [TYPE_GHOST] = COMPOUND_STRING("ゴースト"),
    [TYPE_STEEL] = COMPOUND_STRING("はがね"),
    [TYPE_MYSTERY] = COMPOUND_STRING("----"),
    [TYPE_FIRE] = COMPOUND_STRING("ほのお"),
    [TYPE_WATER] = COMPOUND_STRING("みず"),
    [TYPE_GRASS] = COMPOUND_STRING("くさ"),
    [TYPE_ELECTRIC] = COMPOUND_STRING("でんき"),
    [TYPE_PSYCHIC] = COMPOUND_STRING("エスパー"),
    [TYPE_ICE] = COMPOUND_STRING("こおり"),
    [TYPE_DRAGON] = COMPOUND_STRING("ドラゴン"),
    [TYPE_DARK] = COMPOUND_STRING("あく"),
    [TYPE_FAIRY] = COMPOUND_STRING("フェアリー"),
    [TYPE_STELLAR] = COMPOUND_STRING("ステラ"),
};

static const struct FrontierHubInitialGiftMon sFrontierHubInitialGiftMons[] =
{
    {
        .species = SPECIES_PIKACHU_ORIGINAL,
        .itemId = ITEM_PIKASHUNIUM_Z,
        .ability = ABILITY_STATIC,
        .nature = NATURE_HARDY,
        .teraType = TYPE_ELECTRIC,
        .evs = { [STAT_SPEED] = 252, [STAT_SPATK] = 252 },
        .moves = { MOVE_THUNDERBOLT, MOVE_QUICK_ATTACK, MOVE_IRON_TAIL, MOVE_ELECTROWEB },
    },
    {
        .species = SPECIES_GENGAR,
        .itemId = ITEM_NONE,
        .ability = ABILITY_CURSED_BODY,
        .nature = NATURE_TIMID,
        .teraType = TYPE_FLYING,
        .gmaxFactor = TRUE,
        .evs = { [STAT_SPEED] = 252, [STAT_SPATK] = 252 },
        .moves = { MOVE_SHADOW_BALL, MOVE_DAZZLING_GLEAM, MOVE_SLUDGE_BOMB, MOVE_WILL_O_WISP },
    },
    {
        .species = SPECIES_SCEPTILE,
        .itemId = ITEM_SCEPTILITE,
        .ability = ABILITY_UNBURDEN,
        .nature = NATURE_ADAMANT,
        .teraType = TYPE_STEEL,
        .evs = { [STAT_ATK] = 252, [STAT_SPEED] = 252 },
        .moves = { MOVE_LEAF_BLADE, MOVE_AERIAL_ACE, MOVE_DRAGON_CLAW, MOVE_BRICK_BREAK },
    },
    {
        .species = SPECIES_LYCANROC_DUSK,
        .itemId = ITEM_NONE,
        .ability = ABILITY_TOUGH_CLAWS,
        .nature = NATURE_JOLLY,
        .teraType = TYPE_FIRE,
        .evs = { [STAT_ATK] = 252, [STAT_SPEED] = 252 },
        .moves = { MOVE_STONE_EDGE, MOVE_TERA_BLAST, MOVE_ACCELEROCK, MOVE_PSYCHIC_FANGS },
    },
};

static const u8 *const sFrontierCreatorNatureNames[NUM_NATURES + 1] =
{
    COMPOUND_STRING("がんばりや"),
    COMPOUND_STRING("さみしがり"),
    COMPOUND_STRING("ゆうかん"),
    COMPOUND_STRING("いじっぱり"),
    COMPOUND_STRING("やんちゃ"),
    COMPOUND_STRING("ずぶとい"),
    COMPOUND_STRING("すなお"),
    COMPOUND_STRING("のんき"),
    COMPOUND_STRING("わんぱく"),
    COMPOUND_STRING("のうてんき"),
    COMPOUND_STRING("おくびょう"),
    COMPOUND_STRING("せっかち"),
    COMPOUND_STRING("まじめ"),
    COMPOUND_STRING("ようき"),
    COMPOUND_STRING("むじゃき"),
    COMPOUND_STRING("ひかえめ"),
    COMPOUND_STRING("おっとり"),
    COMPOUND_STRING("れいせい"),
    COMPOUND_STRING("てれや"),
    COMPOUND_STRING("うっかりや"),
    COMPOUND_STRING("おだやか"),
    COMPOUND_STRING("おとなしい"),
    COMPOUND_STRING("なまいき"),
    COMPOUND_STRING("しんちょう"),
    COMPOUND_STRING("きまぐれ"),
    COMPOUND_STRING("ランダム"),
};

static const struct FrontierHubAutoItem sFrontierHubAutoItems[] =
{
    { ITEM_BERSERK_GENE, 999 }, // はかいのいでんし
    { ITEM_HEAT_ROCK, 999 }, // あついいわ
    { ITEM_HEAVY_DUTY_BOOTS, 999 }, // あつぞこブーツ
    { ITEM_LIFE_ORB, 999 }, // いのちのたま
    { ITEM_ELECTRIC_SEED, 999 }, // エレキシード
    { ITEM_BIG_ROOT, 999 }, // おおきなねっこ
    { ITEM_SHELL_BELL, 999 }, // かいがらのすず
    { ITEM_FLAME_ORB, 999 }, // かえんだま
    { ITEM_BLUNDER_POLICY, 999 }, // からぶりほけん
    { ITEM_FOCUS_SASH, 999 }, // きあいのタスキ
    { ITEM_GRASSY_SEED, 999 }, // グラスシード
    { ITEM_TERRAIN_EXTENDER, 999 }, // グランドコート
    { ITEM_IRON_BALL, 999 }, // くろいてっきゅう
    { ITEM_BLACK_SLUDGE, 999 }, // くろいヘドロ
    { ITEM_WIDE_LENS, 999 }, // こうかくレンズ
    { ITEM_CHOICE_SCARF, 999 }, // こだわりスカーフ
    { ITEM_CHOICE_BAND, 999 }, // こだわりハチマキ
    { ITEM_CHOICE_SPECS, 999 }, // こだわりメガネ
    { ITEM_ROCKY_HELMET, 999 }, // ゴツゴツメット
    { ITEM_PSYCHIC_SEED, 999 }, // サイコシード
    { ITEM_SMOOTH_ROCK, 999 }, // さらさらいわ
    { ITEM_DAMP_ROCK, 999 }, // しめったいわ
    { ITEM_WEAKNESS_POLICY, 999 }, // じゃくてんほけん
    { ITEM_WHITE_HERB, 999 }, // しろいハーブ
    { ITEM_EVIOLITE, 999 }, // しんかのきせき
    { ITEM_QUICK_CLAW, 999 }, // せんせいのツメ
    { ITEM_EJECT_PACK, 999 }, // だっしゅつパック
    { ITEM_EJECT_BUTTON, 999 }, // だっしゅつボタン
    { ITEM_EXPERT_BELT, 999 }, // たつじんのおび
    { ITEM_LEFTOVERS, 999 }, // たべのこし
    { ITEM_MUSCLE_BAND, 999 }, // ちからのハチマキ
    { ITEM_ICY_ROCK, 999 }, // つめたいいわ
    { ITEM_LIGHT_BALL, 999 }, // でんきだま
    { ITEM_TOXIC_ORB, 999 }, // どくどくだま
    { ITEM_ASSAULT_VEST, 999 }, // とつげきチョッキ
    { ITEM_THROAT_SPRAY, 999 }, // のどスプレー
    { ITEM_POWER_HERB, 999 }, // パワフルハーブ
    { ITEM_BRIGHT_POWDER, 999 }, // ひかりのこな
    { ITEM_LIGHT_CLAY, 999 }, // ひかりのねんど
    { ITEM_SCOPE_LENS, 999 }, // ピントレンズ
    { ITEM_AIR_BALLOON, 999 }, // ふうせん
    { ITEM_ZOOM_LENS, 999 }, // フォーカスレンズ
    { ITEM_PROTECTIVE_PADS, 999 }, // ぼうごパット
    { ITEM_SAFETY_GOGGLES, 999 }, // ぼうじんゴーグル
    { ITEM_MISTY_SEED, 999 }, // ミストシード
    { ITEM_METRONOME, 999 }, // メトロノーム
    { ITEM_MENTAL_HERB, 999 }, // メンタルハーブ
    { ITEM_ROOM_SERVICE, 999 }, // ルームサービス
    { ITEM_RED_CARD, 999 }, // レッドカード
    { ITEM_BOOSTER_ENERGY, 999 }, // ブーストエナジー
    { ITEM_CLEAR_AMULET, 999 }, // クリアチャーム
    { ITEM_COVERT_CLOAK, 999 }, // おんみつマント
    { ITEM_FOCUS_BAND, 999 }, // きあいのハチマキ
    { ITEM_KINGS_ROCK, 999 }, // おうじゃのしるし
    { ITEM_LAX_INCENSE, 999 }, // のんきのおこう
    { ITEM_LEEK, 999 }, // ながねぎ
    { ITEM_LOADED_DICE, 999 }, // いかさまダイス
    { ITEM_PUNCHING_GLOVE, 999 }, // パンチグローブ
    { ITEM_QUICK_POWDER, 999 }, // スピードパウダー
    { ITEM_THICK_CLUB, 999 }, // ふといホネ
    { ITEM_WISE_GLASSES, 999 }, // ものしりメガネ
    { ITEM_KEE_BERRY, 999 }, // アッキのみ
    { ITEM_IAPAPA_BERRY, 999 }, // イアのみ
    { ITEM_PASSHO_BERRY, 999 }, // イトケのみ
    { ITEM_CUSTAP_BERRY, 999 }, // イバンのみ
    { ITEM_WIKI_BERRY, 999 }, // ウイのみ
    { ITEM_PAYAPA_BERRY, 999 }, // ウタンのみ
    { ITEM_OCCA_BERRY, 999 }, // オッカのみ
    { ITEM_SITRUS_BERRY, 999 }, // オボンのみ
    { ITEM_CHESTO_BERRY, 999 }, // カゴのみ
    { ITEM_KASIB_BERRY, 999 }, // カシブのみ
    { ITEM_SALAC_BERRY, 999 }, // カムラのみ
    { ITEM_PERSIM_BERRY, 999 }, // キーのみ
    { ITEM_CHERI_BERRY, 999 }, // クラボのみ
    { ITEM_LANSAT_BERRY, 999 }, // サンのみ
    { ITEM_JABOCA_BERRY, 999 }, // ジャポのみ
    { ITEM_SHUCA_BERRY, 999 }, // シュカのみ
    { ITEM_APICOT_BERRY, 999 }, // ズアのみ
    { ITEM_STARF_BERRY, 999 }, // スターのみ
    { ITEM_WACAN_BERRY, 999 }, // ソクノのみ
    { ITEM_MARANGA_BERRY, 999 }, // タラプのみ
    { ITEM_TANGA_BERRY, 999 }, // タンガのみ
    { ITEM_LIECHI_BERRY, 999 }, // チイラのみ
    { ITEM_LUM_BERRY, 999 }, // ラムのみ
    { ITEM_ENIGMA_BERRY_E_READER, 999 }, // ナゾのみ
    { ITEM_COLBUR_BERRY, 999 }, // ナモのみ
    { ITEM_COBA_BERRY, 999 }, // バコウのみ
    { ITEM_HABAN_BERRY, 999 }, // ハバンのみ
    { ITEM_AGUAV_BERRY, 999 }, // バンジのみ
    { ITEM_KEBIA_BERRY, 999 }, // ビアーのみ
    { ITEM_FIGY_BERRY, 999 }, // フィラのみ
    { ITEM_CHILAN_BERRY, 999 }, // ホズのみ
    { ITEM_MICLE_BERRY, 999 }, // ミクルのみ
    { ITEM_PETAYA_BERRY, 999 }, // ヤタピのみ
    { ITEM_YACHE_BERRY, 999 }, // ヤチェのみ
    { ITEM_CHOPLE_BERRY, 999 }, // ヨプのみ
    { ITEM_CHARTI_BERRY, 999 }, // ヨロギのみ
    { ITEM_GANLON_BERRY, 999 }, // リュガのみ
    { ITEM_RINDO_BERRY, 999 }, // リンドのみ
    { ITEM_ROWAP_BERRY, 999 }, // レンブのみ
    { ITEM_ROSELI_BERRY, 999 }, // ロゼルのみ
    { ITEM_NONE, 0 },
};

static const enum Species sFrontierCreatorAllowedBaseSpecies[] =
{
    SPECIES_BULBASAUR,
    SPECIES_IVYSAUR,
    SPECIES_VENUSAUR,
    SPECIES_CHARMANDER,
    SPECIES_CHARMELEON,
    SPECIES_CHARIZARD,
    SPECIES_SQUIRTLE,
    SPECIES_WARTORTLE,
    SPECIES_BLASTOISE,
    SPECIES_CATERPIE,
    SPECIES_METAPOD,
    SPECIES_BUTTERFREE,
    SPECIES_WEEDLE,
    SPECIES_KAKUNA,
    SPECIES_BEEDRILL,
    SPECIES_PIDGEY,
    SPECIES_PIDGEOTTO,
    SPECIES_PIDGEOT,
    SPECIES_RATTATA,
    SPECIES_RATICATE,
    SPECIES_SPEAROW,
    SPECIES_FEAROW,
    SPECIES_EKANS,
    SPECIES_ARBOK,
    SPECIES_PIKACHU,
    SPECIES_RAICHU,
    SPECIES_SANDSHREW,
    SPECIES_SANDSLASH,
    SPECIES_NIDORAN_F,
    SPECIES_NIDORINA,
    SPECIES_NIDOQUEEN,
    SPECIES_NIDORAN_M,
    SPECIES_NIDORINO,
    SPECIES_NIDOKING,
    SPECIES_CLEFAIRY,
    SPECIES_CLEFABLE,
    SPECIES_VULPIX,
    SPECIES_NINETALES,
    SPECIES_JIGGLYPUFF,
    SPECIES_WIGGLYTUFF,
    SPECIES_ZUBAT,
    SPECIES_GOLBAT,
    SPECIES_ODDISH,
    SPECIES_GLOOM,
    SPECIES_VILEPLUME,
    SPECIES_PARAS,
    SPECIES_PARASECT,
    SPECIES_VENONAT,
    SPECIES_VENOMOTH,
    SPECIES_DIGLETT,
    SPECIES_DUGTRIO,
    SPECIES_MEOWTH,
    SPECIES_PERSIAN,
    SPECIES_PSYDUCK,
    SPECIES_GOLDUCK,
    SPECIES_MANKEY,
    SPECIES_PRIMEAPE,
    SPECIES_GROWLITHE,
    SPECIES_ARCANINE,
    SPECIES_POLIWAG,
    SPECIES_POLIWHIRL,
    SPECIES_POLIWRATH,
    SPECIES_ABRA,
    SPECIES_KADABRA,
    SPECIES_ALAKAZAM,
    SPECIES_MACHOP,
    SPECIES_MACHOKE,
    SPECIES_MACHAMP,
    SPECIES_BELLSPROUT,
    SPECIES_WEEPINBELL,
    SPECIES_VICTREEBEL,
    SPECIES_TENTACOOL,
    SPECIES_TENTACRUEL,
    SPECIES_GEODUDE,
    SPECIES_GRAVELER,
    SPECIES_GOLEM,
    SPECIES_PONYTA,
    SPECIES_RAPIDASH,
    SPECIES_SLOWPOKE,
    SPECIES_SLOWBRO,
    SPECIES_MAGNEMITE,
    SPECIES_MAGNETON,
    SPECIES_FARFETCHD,
    SPECIES_DODUO,
    SPECIES_DODRIO,
    SPECIES_SEEL,
    SPECIES_DEWGONG,
    SPECIES_GRIMER,
    SPECIES_MUK,
    SPECIES_SHELLDER,
    SPECIES_CLOYSTER,
    SPECIES_GASTLY,
    SPECIES_HAUNTER,
    SPECIES_GENGAR,
    SPECIES_ONIX,
    SPECIES_DROWZEE,
    SPECIES_HYPNO,
    SPECIES_KRABBY,
    SPECIES_KINGLER,
    SPECIES_VOLTORB,
    SPECIES_ELECTRODE,
    SPECIES_EXEGGCUTE,
    SPECIES_EXEGGUTOR,
    SPECIES_CUBONE,
    SPECIES_MAROWAK,
    SPECIES_HITMONLEE,
    SPECIES_HITMONCHAN,
    SPECIES_LICKITUNG,
    SPECIES_KOFFING,
    SPECIES_WEEZING,
    SPECIES_RHYHORN,
    SPECIES_RHYDON,
    SPECIES_CHANSEY,
    SPECIES_TANGELA,
    SPECIES_KANGASKHAN,
    SPECIES_HORSEA,
    SPECIES_SEADRA,
    SPECIES_GOLDEEN,
    SPECIES_SEAKING,
    SPECIES_STARYU,
    SPECIES_STARMIE,
    SPECIES_MR_MIME,
    SPECIES_SCYTHER,
    SPECIES_JYNX,
    SPECIES_ELECTABUZZ,
    SPECIES_MAGMAR,
    SPECIES_PINSIR,
    SPECIES_TAUROS,
    SPECIES_MAGIKARP,
    SPECIES_GYARADOS,
    SPECIES_LAPRAS,
    SPECIES_DITTO,
    SPECIES_EEVEE,
    SPECIES_VAPOREON,
    SPECIES_JOLTEON,
    SPECIES_FLAREON,
    SPECIES_PORYGON,
    SPECIES_OMANYTE,
    SPECIES_OMASTAR,
    SPECIES_KABUTO,
    SPECIES_KABUTOPS,
    SPECIES_AERODACTYL,
    SPECIES_SNORLAX,
    SPECIES_ARTICUNO,
    SPECIES_ZAPDOS,
    SPECIES_MOLTRES,
    SPECIES_DRATINI,
    SPECIES_DRAGONAIR,
    SPECIES_DRAGONITE,
    SPECIES_MEWTWO,
    SPECIES_MEW,
    SPECIES_CHIKORITA,
    SPECIES_BAYLEEF,
    SPECIES_MEGANIUM,
    SPECIES_CYNDAQUIL,
    SPECIES_QUILAVA,
    SPECIES_TYPHLOSION,
    SPECIES_TOTODILE,
    SPECIES_CROCONAW,
    SPECIES_FERALIGATR,
    SPECIES_SENTRET,
    SPECIES_FURRET,
    SPECIES_HOOTHOOT,
    SPECIES_NOCTOWL,
    SPECIES_LEDYBA,
    SPECIES_LEDIAN,
    SPECIES_SPINARAK,
    SPECIES_ARIADOS,
    SPECIES_CROBAT,
    SPECIES_CHINCHOU,
    SPECIES_LANTURN,
    SPECIES_PICHU,
    SPECIES_CLEFFA,
    SPECIES_IGGLYBUFF,
    SPECIES_TOGEPI,
    SPECIES_TOGETIC,
    SPECIES_NATU,
    SPECIES_XATU,
    SPECIES_MAREEP,
    SPECIES_FLAAFFY,
    SPECIES_AMPHAROS,
    SPECIES_BELLOSSOM,
    SPECIES_MARILL,
    SPECIES_AZUMARILL,
    SPECIES_SUDOWOODO,
    SPECIES_POLITOED,
    SPECIES_HOPPIP,
    SPECIES_SKIPLOOM,
    SPECIES_JUMPLUFF,
    SPECIES_AIPOM,
    SPECIES_SUNKERN,
    SPECIES_SUNFLORA,
    SPECIES_YANMA,
    SPECIES_WOOPER,
    SPECIES_QUAGSIRE,
    SPECIES_ESPEON,
    SPECIES_UMBREON,
    SPECIES_MURKROW,
    SPECIES_SLOWKING,
    SPECIES_MISDREAVUS,
    SPECIES_UNOWN,
    SPECIES_WOBBUFFET,
    SPECIES_GIRAFARIG,
    SPECIES_PINECO,
    SPECIES_FORRETRESS,
    SPECIES_DUNSPARCE,
    SPECIES_GLIGAR,
    SPECIES_STEELIX,
    SPECIES_SNUBBULL,
    SPECIES_GRANBULL,
    SPECIES_QWILFISH,
    SPECIES_SCIZOR,
    SPECIES_SHUCKLE,
    SPECIES_HERACROSS,
    SPECIES_SNEASEL,
    SPECIES_TEDDIURSA,
    SPECIES_URSARING,
    SPECIES_SLUGMA,
    SPECIES_MAGCARGO,
    SPECIES_SWINUB,
    SPECIES_PILOSWINE,
    SPECIES_CORSOLA,
    SPECIES_REMORAID,
    SPECIES_OCTILLERY,
    SPECIES_DELIBIRD,
    SPECIES_MANTINE,
    SPECIES_SKARMORY,
    SPECIES_HOUNDOUR,
    SPECIES_HOUNDOOM,
    SPECIES_KINGDRA,
    SPECIES_PHANPY,
    SPECIES_DONPHAN,
    SPECIES_PORYGON2,
    SPECIES_STANTLER,
    SPECIES_SMEARGLE,
    SPECIES_TYROGUE,
    SPECIES_HITMONTOP,
    SPECIES_SMOOCHUM,
    SPECIES_ELEKID,
    SPECIES_MAGBY,
    SPECIES_MILTANK,
    SPECIES_BLISSEY,
    SPECIES_RAIKOU,
    SPECIES_ENTEI,
    SPECIES_SUICUNE,
    SPECIES_LARVITAR,
    SPECIES_PUPITAR,
    SPECIES_TYRANITAR,
    SPECIES_LUGIA,
    SPECIES_HO_OH,
    SPECIES_CELEBI,
    SPECIES_TREECKO,
    SPECIES_GROVYLE,
    SPECIES_SCEPTILE,
    SPECIES_TORCHIC,
    SPECIES_COMBUSKEN,
    SPECIES_BLAZIKEN,
    SPECIES_MUDKIP,
    SPECIES_MARSHTOMP,
    SPECIES_SWAMPERT,
    SPECIES_POOCHYENA,
    SPECIES_MIGHTYENA,
    SPECIES_ZIGZAGOON,
    SPECIES_LINOONE,
    SPECIES_WURMPLE,
    SPECIES_SILCOON,
    SPECIES_BEAUTIFLY,
    SPECIES_CASCOON,
    SPECIES_DUSTOX,
    SPECIES_LOTAD,
    SPECIES_LOMBRE,
    SPECIES_LUDICOLO,
    SPECIES_SEEDOT,
    SPECIES_NUZLEAF,
    SPECIES_SHIFTRY,
    SPECIES_TAILLOW,
    SPECIES_SWELLOW,
    SPECIES_WINGULL,
    SPECIES_PELIPPER,
    SPECIES_RALTS,
    SPECIES_KIRLIA,
    SPECIES_GARDEVOIR,
    SPECIES_SURSKIT,
    SPECIES_MASQUERAIN,
    SPECIES_SHROOMISH,
    SPECIES_BRELOOM,
    SPECIES_SLAKOTH,
    SPECIES_VIGOROTH,
    SPECIES_SLAKING,
    SPECIES_NINCADA,
    SPECIES_NINJASK,
    SPECIES_SHEDINJA,
    SPECIES_WHISMUR,
    SPECIES_LOUDRED,
    SPECIES_EXPLOUD,
    SPECIES_MAKUHITA,
    SPECIES_HARIYAMA,
    SPECIES_AZURILL,
    SPECIES_NOSEPASS,
    SPECIES_SKITTY,
    SPECIES_DELCATTY,
    SPECIES_SABLEYE,
    SPECIES_MAWILE,
    SPECIES_ARON,
    SPECIES_LAIRON,
    SPECIES_AGGRON,
    SPECIES_MEDITITE,
    SPECIES_MEDICHAM,
    SPECIES_ELECTRIKE,
    SPECIES_MANECTRIC,
    SPECIES_PLUSLE,
    SPECIES_MINUN,
    SPECIES_VOLBEAT,
    SPECIES_ILLUMISE,
    SPECIES_ROSELIA,
    SPECIES_GULPIN,
    SPECIES_SWALOT,
    SPECIES_CARVANHA,
    SPECIES_SHARPEDO,
    SPECIES_WAILMER,
    SPECIES_WAILORD,
    SPECIES_NUMEL,
    SPECIES_CAMERUPT,
    SPECIES_TORKOAL,
    SPECIES_SPOINK,
    SPECIES_GRUMPIG,
    SPECIES_SPINDA,
    SPECIES_TRAPINCH,
    SPECIES_VIBRAVA,
    SPECIES_FLYGON,
    SPECIES_CACNEA,
    SPECIES_CACTURNE,
    SPECIES_SWABLU,
    SPECIES_ALTARIA,
    SPECIES_ZANGOOSE,
    SPECIES_SEVIPER,
    SPECIES_LUNATONE,
    SPECIES_SOLROCK,
    SPECIES_BARBOACH,
    SPECIES_WHISCASH,
    SPECIES_CORPHISH,
    SPECIES_CRAWDAUNT,
    SPECIES_BALTOY,
    SPECIES_CLAYDOL,
    SPECIES_LILEEP,
    SPECIES_CRADILY,
    SPECIES_ANORITH,
    SPECIES_ARMALDO,
    SPECIES_FEEBAS,
    SPECIES_MILOTIC,
    SPECIES_CASTFORM_NORMAL,
    SPECIES_CASTFORM,
    SPECIES_KECLEON,
    SPECIES_SHUPPET,
    SPECIES_BANETTE,
    SPECIES_DUSKULL,
    SPECIES_DUSCLOPS,
    SPECIES_TROPIUS,
    SPECIES_CHIMECHO,
    SPECIES_ABSOL,
    SPECIES_WYNAUT,
    SPECIES_SNORUNT,
    SPECIES_GLALIE,
    SPECIES_SPHEAL,
    SPECIES_SEALEO,
    SPECIES_WALREIN,
    SPECIES_CLAMPERL,
    SPECIES_HUNTAIL,
    SPECIES_GOREBYSS,
    SPECIES_RELICANTH,
    SPECIES_LUVDISC,
    SPECIES_BAGON,
    SPECIES_SHELGON,
    SPECIES_SALAMENCE,
    SPECIES_BELDUM,
    SPECIES_METANG,
    SPECIES_METAGROSS,
    SPECIES_REGIROCK,
    SPECIES_REGICE,
    SPECIES_REGISTEEL,
    SPECIES_LATIAS,
    SPECIES_LATIOS,
    SPECIES_KYOGRE,
    SPECIES_GROUDON,
    SPECIES_RAYQUAZA,
    SPECIES_JIRACHI,
    SPECIES_DEOXYS_NORMAL,
    SPECIES_DEOXYS,
    SPECIES_TURTWIG,
    SPECIES_GROTLE,
    SPECIES_TORTERRA,
    SPECIES_CHIMCHAR,
    SPECIES_MONFERNO,
    SPECIES_INFERNAPE,
    SPECIES_PIPLUP,
    SPECIES_PRINPLUP,
    SPECIES_EMPOLEON,
    SPECIES_STARLY,
    SPECIES_STARAVIA,
    SPECIES_STARAPTOR,
    SPECIES_BIDOOF,
    SPECIES_BIBAREL,
    SPECIES_KRICKETOT,
    SPECIES_KRICKETUNE,
    SPECIES_SHINX,
    SPECIES_LUXIO,
    SPECIES_LUXRAY,
    SPECIES_BUDEW,
    SPECIES_ROSERADE,
    SPECIES_CRANIDOS,
    SPECIES_RAMPARDOS,
    SPECIES_SHIELDON,
    SPECIES_BASTIODON,
    SPECIES_BURMY_PLANT,
    SPECIES_BURMY,
    SPECIES_WORMADAM_PLANT,
    SPECIES_WORMADAM,
    SPECIES_MOTHIM_PLANT,
    SPECIES_MOTHIM,
    SPECIES_COMBEE,
    SPECIES_VESPIQUEN,
    SPECIES_PACHIRISU,
    SPECIES_BUIZEL,
    SPECIES_FLOATZEL,
    SPECIES_CHERUBI,
    SPECIES_CHERRIM_OVERCAST,
    SPECIES_CHERRIM,
    SPECIES_SHELLOS_WEST,
    SPECIES_SHELLOS,
    SPECIES_GASTRODON_WEST,
    SPECIES_GASTRODON,
    SPECIES_AMBIPOM,
    SPECIES_DRIFLOON,
    SPECIES_DRIFBLIM,
    SPECIES_BUNEARY,
    SPECIES_LOPUNNY,
    SPECIES_MISMAGIUS,
    SPECIES_HONCHKROW,
    SPECIES_GLAMEOW,
    SPECIES_PURUGLY,
    SPECIES_CHINGLING,
    SPECIES_STUNKY,
    SPECIES_SKUNTANK,
    SPECIES_BRONZOR,
    SPECIES_BRONZONG,
    SPECIES_BONSLY,
    SPECIES_MIME_JR,
    SPECIES_HAPPINY,
    SPECIES_CHATOT,
    SPECIES_SPIRITOMB,
    SPECIES_GIBLE,
    SPECIES_GABITE,
    SPECIES_GARCHOMP,
    SPECIES_MUNCHLAX,
    SPECIES_RIOLU,
    SPECIES_LUCARIO,
    SPECIES_HIPPOPOTAS,
    SPECIES_HIPPOWDON,
    SPECIES_SKORUPI,
    SPECIES_DRAPION,
    SPECIES_CROAGUNK,
    SPECIES_TOXICROAK,
    SPECIES_CARNIVINE,
    SPECIES_FINNEON,
    SPECIES_LUMINEON,
    SPECIES_MANTYKE,
    SPECIES_SNOVER,
    SPECIES_ABOMASNOW,
    SPECIES_WEAVILE,
    SPECIES_MAGNEZONE,
    SPECIES_LICKILICKY,
    SPECIES_RHYPERIOR,
    SPECIES_TANGROWTH,
    SPECIES_ELECTIVIRE,
    SPECIES_MAGMORTAR,
    SPECIES_TOGEKISS,
    SPECIES_YANMEGA,
    SPECIES_LEAFEON,
    SPECIES_GLACEON,
    SPECIES_GLISCOR,
    SPECIES_MAMOSWINE,
    SPECIES_PORYGON_Z,
    SPECIES_GALLADE,
    SPECIES_PROBOPASS,
    SPECIES_DUSKNOIR,
    SPECIES_FROSLASS,
    SPECIES_ROTOM,
    SPECIES_UXIE,
    SPECIES_MESPRIT,
    SPECIES_AZELF,
    SPECIES_DIALGA,
    SPECIES_PALKIA,
    SPECIES_HEATRAN,
    SPECIES_REGIGIGAS,
    SPECIES_GIRATINA_ALTERED,
    SPECIES_GIRATINA,
    SPECIES_CRESSELIA,
    SPECIES_PHIONE,
    SPECIES_MANAPHY,
    SPECIES_DARKRAI,
    SPECIES_SHAYMIN_LAND,
    SPECIES_SHAYMIN,
    SPECIES_ARCEUS_NORMAL,
    SPECIES_ARCEUS,
    SPECIES_VICTINI,
    SPECIES_SNIVY,
    SPECIES_SERVINE,
    SPECIES_SERPERIOR,
    SPECIES_TEPIG,
    SPECIES_PIGNITE,
    SPECIES_EMBOAR,
    SPECIES_OSHAWOTT,
    SPECIES_DEWOTT,
    SPECIES_SAMUROTT,
    SPECIES_PATRAT,
    SPECIES_WATCHOG,
    SPECIES_LILLIPUP,
    SPECIES_HERDIER,
    SPECIES_STOUTLAND,
    SPECIES_PURRLOIN,
    SPECIES_LIEPARD,
    SPECIES_PANSAGE,
    SPECIES_SIMISAGE,
    SPECIES_PANSEAR,
    SPECIES_SIMISEAR,
    SPECIES_PANPOUR,
    SPECIES_SIMIPOUR,
    SPECIES_MUNNA,
    SPECIES_MUSHARNA,
    SPECIES_PIDOVE,
    SPECIES_TRANQUILL,
    SPECIES_UNFEZANT,
    SPECIES_BLITZLE,
    SPECIES_ZEBSTRIKA,
    SPECIES_ROGGENROLA,
    SPECIES_BOLDORE,
    SPECIES_GIGALITH,
    SPECIES_WOOBAT,
    SPECIES_SWOOBAT,
    SPECIES_DRILBUR,
    SPECIES_EXCADRILL,
    SPECIES_AUDINO,
    SPECIES_TIMBURR,
    SPECIES_GURDURR,
    SPECIES_CONKELDURR,
    SPECIES_TYMPOLE,
    SPECIES_PALPITOAD,
    SPECIES_SEISMITOAD,
    SPECIES_THROH,
    SPECIES_SAWK,
    SPECIES_SEWADDLE,
    SPECIES_SWADLOON,
    SPECIES_LEAVANNY,
    SPECIES_VENIPEDE,
    SPECIES_WHIRLIPEDE,
    SPECIES_SCOLIPEDE,
    SPECIES_COTTONEE,
    SPECIES_WHIMSICOTT,
    SPECIES_PETILIL,
    SPECIES_LILLIGANT,
    SPECIES_BASCULIN_RED_STRIPED,
    SPECIES_BASCULIN,
    SPECIES_SANDILE,
    SPECIES_KROKOROK,
    SPECIES_KROOKODILE,
    SPECIES_DARUMAKA,
    SPECIES_DARMANITAN_STANDARD,
    SPECIES_DARMANITAN,
    SPECIES_MARACTUS,
    SPECIES_DWEBBLE,
    SPECIES_CRUSTLE,
    SPECIES_SCRAGGY,
    SPECIES_SCRAFTY,
    SPECIES_SIGILYPH,
    SPECIES_YAMASK,
    SPECIES_COFAGRIGUS,
    SPECIES_TIRTOUGA,
    SPECIES_CARRACOSTA,
    SPECIES_ARCHEN,
    SPECIES_ARCHEOPS,
    SPECIES_TRUBBISH,
    SPECIES_GARBODOR,
    SPECIES_ZORUA,
    SPECIES_ZOROARK,
    SPECIES_MINCCINO,
    SPECIES_CINCCINO,
    SPECIES_GOTHITA,
    SPECIES_GOTHORITA,
    SPECIES_GOTHITELLE,
    SPECIES_SOLOSIS,
    SPECIES_DUOSION,
    SPECIES_REUNICLUS,
    SPECIES_DUCKLETT,
    SPECIES_SWANNA,
    SPECIES_VANILLITE,
    SPECIES_VANILLISH,
    SPECIES_VANILLUXE,
    SPECIES_DEERLING_SPRING,
    SPECIES_DEERLING,
    SPECIES_SAWSBUCK_SPRING,
    SPECIES_SAWSBUCK,
    SPECIES_EMOLGA,
    SPECIES_KARRABLAST,
    SPECIES_ESCAVALIER,
    SPECIES_FOONGUS,
    SPECIES_AMOONGUSS,
    SPECIES_FRILLISH,
    SPECIES_JELLICENT,
    SPECIES_ALOMOMOLA,
    SPECIES_JOLTIK,
    SPECIES_GALVANTULA,
    SPECIES_FERROSEED,
    SPECIES_FERROTHORN,
    SPECIES_KLINK,
    SPECIES_KLANG,
    SPECIES_KLINKLANG,
    SPECIES_TYNAMO,
    SPECIES_EELEKTRIK,
    SPECIES_EELEKTROSS,
    SPECIES_ELGYEM,
    SPECIES_BEHEEYEM,
    SPECIES_LITWICK,
    SPECIES_LAMPENT,
    SPECIES_CHANDELURE,
    SPECIES_AXEW,
    SPECIES_FRAXURE,
    SPECIES_HAXORUS,
    SPECIES_CUBCHOO,
    SPECIES_BEARTIC,
    SPECIES_CRYOGONAL,
    SPECIES_SHELMET,
    SPECIES_ACCELGOR,
    SPECIES_STUNFISK,
    SPECIES_MIENFOO,
    SPECIES_MIENSHAO,
    SPECIES_DRUDDIGON,
    SPECIES_GOLETT,
    SPECIES_GOLURK,
    SPECIES_PAWNIARD,
    SPECIES_BISHARP,
    SPECIES_BOUFFALANT,
    SPECIES_RUFFLET,
    SPECIES_BRAVIARY,
    SPECIES_VULLABY,
    SPECIES_MANDIBUZZ,
    SPECIES_HEATMOR,
    SPECIES_DURANT,
    SPECIES_DEINO,
    SPECIES_ZWEILOUS,
    SPECIES_HYDREIGON,
    SPECIES_LARVESTA,
    SPECIES_VOLCARONA,
    SPECIES_COBALION,
    SPECIES_TERRAKION,
    SPECIES_VIRIZION,
    SPECIES_TORNADUS_INCARNATE,
    SPECIES_TORNADUS,
    SPECIES_THUNDURUS_INCARNATE,
    SPECIES_THUNDURUS,
    SPECIES_RESHIRAM,
    SPECIES_ZEKROM,
    SPECIES_LANDORUS_INCARNATE,
    SPECIES_LANDORUS,
    SPECIES_KYUREM,
    SPECIES_KELDEO_ORDINARY,
    SPECIES_KELDEO,
    SPECIES_MELOETTA_ARIA,
    SPECIES_MELOETTA,
    SPECIES_GENESECT,
    SPECIES_CHESPIN,
    SPECIES_QUILLADIN,
    SPECIES_CHESNAUGHT,
    SPECIES_FENNEKIN,
    SPECIES_BRAIXEN,
    SPECIES_DELPHOX,
    SPECIES_FROAKIE,
    SPECIES_FROGADIER,
    SPECIES_GRENINJA,
    SPECIES_BUNNELBY,
    SPECIES_DIGGERSBY,
    SPECIES_FLETCHLING,
    SPECIES_FLETCHINDER,
    SPECIES_TALONFLAME,
    SPECIES_SCATTERBUG_ICY_SNOW,
    SPECIES_SCATTERBUG,
    SPECIES_SPEWPA_ICY_SNOW,
    SPECIES_SPEWPA,
    SPECIES_VIVILLON_ICY_SNOW,
    SPECIES_VIVILLON,
    SPECIES_LITLEO,
    SPECIES_PYROAR,
    SPECIES_FLABEBE_RED,
    SPECIES_FLABEBE,
    SPECIES_FLOETTE_RED,
    SPECIES_FLOETTE,
    SPECIES_FLORGES_RED,
    SPECIES_FLORGES,
    SPECIES_SKIDDO,
    SPECIES_GOGOAT,
    SPECIES_PANCHAM,
    SPECIES_PANGORO,
    SPECIES_FURFROU_NATURAL,
    SPECIES_FURFROU,
    SPECIES_ESPURR,
    SPECIES_MEOWSTIC_M,
    SPECIES_MEOWSTIC,
    SPECIES_HONEDGE,
    SPECIES_DOUBLADE,
    SPECIES_AEGISLASH_SHIELD,
    SPECIES_AEGISLASH,
    SPECIES_SPRITZEE,
    SPECIES_AROMATISSE,
    SPECIES_SWIRLIX,
    SPECIES_SLURPUFF,
    SPECIES_INKAY,
    SPECIES_MALAMAR,
    SPECIES_BINACLE,
    SPECIES_BARBARACLE,
    SPECIES_SKRELP,
    SPECIES_DRAGALGE,
    SPECIES_CLAUNCHER,
    SPECIES_CLAWITZER,
    SPECIES_HELIOPTILE,
    SPECIES_HELIOLISK,
    SPECIES_TYRUNT,
    SPECIES_TYRANTRUM,
    SPECIES_AMAURA,
    SPECIES_AURORUS,
    SPECIES_SYLVEON,
    SPECIES_HAWLUCHA,
    SPECIES_DEDENNE,
    SPECIES_CARBINK,
    SPECIES_GOOMY,
    SPECIES_SLIGGOO,
    SPECIES_GOODRA,
    SPECIES_KLEFKI,
    SPECIES_PHANTUMP,
    SPECIES_TREVENANT,
    SPECIES_PUMPKABOO_AVERAGE,
    SPECIES_PUMPKABOO,
    SPECIES_GOURGEIST_AVERAGE,
    SPECIES_GOURGEIST,
    SPECIES_BERGMITE,
    SPECIES_AVALUGG,
    SPECIES_NOIBAT,
    SPECIES_NOIVERN,
    SPECIES_XERNEAS_NEUTRAL,
    SPECIES_XERNEAS,
    SPECIES_YVELTAL,
    SPECIES_ZYGARDE_50,
    SPECIES_ZYGARDE,
    SPECIES_DIANCIE,
    SPECIES_HOOPA_CONFINED,
    SPECIES_HOOPA,
    SPECIES_VOLCANION,
    SPECIES_ROWLET,
    SPECIES_DARTRIX,
    SPECIES_DECIDUEYE,
    SPECIES_LITTEN,
    SPECIES_TORRACAT,
    SPECIES_INCINEROAR,
    SPECIES_POPPLIO,
    SPECIES_BRIONNE,
    SPECIES_PRIMARINA,
    SPECIES_PIKIPEK,
    SPECIES_TRUMBEAK,
    SPECIES_TOUCANNON,
    SPECIES_YUNGOOS,
    SPECIES_GUMSHOOS,
    SPECIES_GRUBBIN,
    SPECIES_CHARJABUG,
    SPECIES_VIKAVOLT,
    SPECIES_CRABRAWLER,
    SPECIES_CRABOMINABLE,
    SPECIES_ORICORIO_BAILE,
    SPECIES_ORICORIO,
    SPECIES_CUTIEFLY,
    SPECIES_RIBOMBEE,
    SPECIES_ROCKRUFF,
    SPECIES_LYCANROC_MIDDAY,
    SPECIES_LYCANROC,
    SPECIES_WISHIWASHI_SOLO,
    SPECIES_WISHIWASHI,
    SPECIES_MAREANIE,
    SPECIES_TOXAPEX,
    SPECIES_MUDBRAY,
    SPECIES_MUDSDALE,
    SPECIES_DEWPIDER,
    SPECIES_ARAQUANID,
    SPECIES_FOMANTIS,
    SPECIES_LURANTIS,
    SPECIES_MORELULL,
    SPECIES_SHIINOTIC,
    SPECIES_SALANDIT,
    SPECIES_SALAZZLE,
    SPECIES_STUFFUL,
    SPECIES_BEWEAR,
    SPECIES_BOUNSWEET,
    SPECIES_STEENEE,
    SPECIES_TSAREENA,
    SPECIES_COMFEY,
    SPECIES_ORANGURU,
    SPECIES_PASSIMIAN,
    SPECIES_WIMPOD,
    SPECIES_GOLISOPOD,
    SPECIES_SANDYGAST,
    SPECIES_PALOSSAND,
    SPECIES_PYUKUMUKU,
    SPECIES_TYPE_NULL,
    SPECIES_SILVALLY_NORMAL,
    SPECIES_SILVALLY,
    SPECIES_MINIOR_METEOR_RED,
    SPECIES_MINIOR_METEOR,
    SPECIES_MINIOR,
    SPECIES_MINIOR_RED,
    SPECIES_KOMALA,
    SPECIES_TURTONATOR,
    SPECIES_TOGEDEMARU,
    SPECIES_MIMIKYU_DISGUISED,
    SPECIES_MIMIKYU,
    SPECIES_BRUXISH,
    SPECIES_DRAMPA,
    SPECIES_DHELMISE,
    SPECIES_JANGMO_O,
    SPECIES_HAKAMO_O,
    SPECIES_KOMMO_O,
    SPECIES_TAPU_KOKO,
    SPECIES_TAPU_LELE,
    SPECIES_TAPU_BULU,
    SPECIES_TAPU_FINI,
    SPECIES_COSMOG,
    SPECIES_COSMOEM,
    SPECIES_SOLGALEO,
    SPECIES_LUNALA,
    SPECIES_NIHILEGO,
    SPECIES_BUZZWOLE,
    SPECIES_PHEROMOSA,
    SPECIES_XURKITREE,
    SPECIES_CELESTEELA,
    SPECIES_KARTANA,
    SPECIES_GUZZLORD,
    SPECIES_NECROZMA,
    SPECIES_MAGEARNA,
    SPECIES_MARSHADOW,
    SPECIES_POIPOLE,
    SPECIES_NAGANADEL,
    SPECIES_STAKATAKA,
    SPECIES_BLACEPHALON,
    SPECIES_ZERAORA,
    SPECIES_MELTAN,
    SPECIES_MELMETAL,
    SPECIES_GROOKEY,
    SPECIES_THWACKEY,
    SPECIES_RILLABOOM,
    SPECIES_SCORBUNNY,
    SPECIES_RABOOT,
    SPECIES_CINDERACE,
    SPECIES_SOBBLE,
    SPECIES_DRIZZILE,
    SPECIES_INTELEON,
    SPECIES_SKWOVET,
    SPECIES_GREEDENT,
    SPECIES_ROOKIDEE,
    SPECIES_CORVISQUIRE,
    SPECIES_CORVIKNIGHT,
    SPECIES_BLIPBUG,
    SPECIES_DOTTLER,
    SPECIES_ORBEETLE,
    SPECIES_NICKIT,
    SPECIES_THIEVUL,
    SPECIES_GOSSIFLEUR,
    SPECIES_ELDEGOSS,
    SPECIES_WOOLOO,
    SPECIES_DUBWOOL,
    SPECIES_CHEWTLE,
    SPECIES_DREDNAW,
    SPECIES_YAMPER,
    SPECIES_BOLTUND,
    SPECIES_ROLYCOLY,
    SPECIES_CARKOL,
    SPECIES_COALOSSAL,
    SPECIES_APPLIN,
    SPECIES_FLAPPLE,
    SPECIES_APPLETUN,
    SPECIES_SILICOBRA,
    SPECIES_SANDACONDA,
    SPECIES_CRAMORANT,
    SPECIES_ARROKUDA,
    SPECIES_BARRASKEWDA,
    SPECIES_TOXEL,
    SPECIES_TOXTRICITY_AMPED,
    SPECIES_TOXTRICITY,
    SPECIES_SIZZLIPEDE,
    SPECIES_CENTISKORCH,
    SPECIES_CLOBBOPUS,
    SPECIES_GRAPPLOCT,
    SPECIES_SINISTEA_PHONY,
    SPECIES_SINISTEA,
    SPECIES_POLTEAGEIST_PHONY,
    SPECIES_POLTEAGEIST,
    SPECIES_HATENNA,
    SPECIES_HATTREM,
    SPECIES_HATTERENE,
    SPECIES_IMPIDIMP,
    SPECIES_MORGREM,
    SPECIES_GRIMMSNARL,
    SPECIES_OBSTAGOON,
    SPECIES_PERRSERKER,
    SPECIES_CURSOLA,
    SPECIES_SIRFETCHD,
    SPECIES_MR_RIME,
    SPECIES_RUNERIGUS,
    SPECIES_MILCERY,
    SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY,
    SPECIES_ALCREMIE,
    SPECIES_ALCREMIE_VANILLA_CREAM,
    SPECIES_FALINKS,
    SPECIES_PINCURCHIN,
    SPECIES_SNOM,
    SPECIES_FROSMOTH,
    SPECIES_STONJOURNER,
    SPECIES_EISCUE_ICE,
    SPECIES_EISCUE,
    SPECIES_INDEEDEE_M,
    SPECIES_INDEEDEE,
    SPECIES_MORPEKO_FULL_BELLY,
    SPECIES_MORPEKO,
    SPECIES_CUFANT,
    SPECIES_COPPERAJAH,
    SPECIES_DRACOZOLT,
    SPECIES_ARCTOZOLT,
    SPECIES_DRACOVISH,
    SPECIES_ARCTOVISH,
    SPECIES_DURALUDON,
    SPECIES_DREEPY,
    SPECIES_DRAKLOAK,
    SPECIES_DRAGAPULT,
    SPECIES_ZACIAN,
    SPECIES_ZAMAZENTA,
    SPECIES_ETERNATUS,
    SPECIES_KUBFU,
    SPECIES_URSHIFU_SINGLE_STRIKE,
    SPECIES_URSHIFU,
    SPECIES_ZARUDE,
    SPECIES_REGIELEKI,
    SPECIES_REGIDRAGO,
    SPECIES_GLASTRIER,
    SPECIES_SPECTRIER,
    SPECIES_CALYREX,
    SPECIES_WYRDEER,
    SPECIES_KLEAVOR,
    SPECIES_URSALUNA,
    SPECIES_BASCULEGION_M,
    SPECIES_BASCULEGION,
    SPECIES_SNEASLER,
    SPECIES_OVERQWIL,
    SPECIES_ENAMORUS_INCARNATE,
    SPECIES_ENAMORUS,
    SPECIES_RATTATA_ALOLA,
    SPECIES_RATICATE_ALOLA,
    SPECIES_RAICHU_ALOLA,
    SPECIES_SANDSHREW_ALOLA,
    SPECIES_SANDSLASH_ALOLA,
    SPECIES_VULPIX_ALOLA,
    SPECIES_NINETALES_ALOLA,
    SPECIES_DIGLETT_ALOLA,
    SPECIES_DUGTRIO_ALOLA,
    SPECIES_MEOWTH_ALOLA,
    SPECIES_PERSIAN_ALOLA,
    SPECIES_GEODUDE_ALOLA,
    SPECIES_GRAVELER_ALOLA,
    SPECIES_GOLEM_ALOLA,
    SPECIES_GRIMER_ALOLA,
    SPECIES_MUK_ALOLA,
    SPECIES_EXEGGUTOR_ALOLA,
    SPECIES_MAROWAK_ALOLA,
    SPECIES_MEOWTH_GALAR,
    SPECIES_PONYTA_GALAR,
    SPECIES_RAPIDASH_GALAR,
    SPECIES_SLOWPOKE_GALAR,
    SPECIES_SLOWBRO_GALAR,
    SPECIES_FARFETCHD_GALAR,
    SPECIES_WEEZING_GALAR,
    SPECIES_MR_MIME_GALAR,
    SPECIES_ARTICUNO_GALAR,
    SPECIES_ZAPDOS_GALAR,
    SPECIES_MOLTRES_GALAR,
    SPECIES_SLOWKING_GALAR,
    SPECIES_CORSOLA_GALAR,
    SPECIES_ZIGZAGOON_GALAR,
    SPECIES_LINOONE_GALAR,
    SPECIES_DARUMAKA_GALAR,
    SPECIES_DARMANITAN_GALAR_STANDARD,
    SPECIES_DARMANITAN_GALAR,
    SPECIES_YAMASK_GALAR,
    SPECIES_STUNFISK_GALAR,
    SPECIES_GROWLITHE_HISUI,
    SPECIES_ARCANINE_HISUI,
    SPECIES_VOLTORB_HISUI,
    SPECIES_ELECTRODE_HISUI,
    SPECIES_TYPHLOSION_HISUI,
    SPECIES_QWILFISH_HISUI,
    SPECIES_SNEASEL_HISUI,
    SPECIES_SAMUROTT_HISUI,
    SPECIES_LILLIGANT_HISUI,
    SPECIES_ZORUA_HISUI,
    SPECIES_ZOROARK_HISUI,
    SPECIES_BRAVIARY_HISUI,
    SPECIES_SLIGGOO_HISUI,
    SPECIES_GOODRA_HISUI,
    SPECIES_AVALUGG_HISUI,
    SPECIES_DECIDUEYE_HISUI,
    SPECIES_PIKACHU_COSPLAY,
    SPECIES_PIKACHU_ROCK_STAR,
    SPECIES_PIKACHU_BELLE,
    SPECIES_PIKACHU_POP_STAR,
    SPECIES_PIKACHU_PHD,
    SPECIES_PIKACHU_LIBRE,
    SPECIES_PIKACHU_ORIGINAL,
    SPECIES_PIKACHU_HOENN,
    SPECIES_PIKACHU_SINNOH,
    SPECIES_PIKACHU_UNOVA,
    SPECIES_PIKACHU_KALOS,
    SPECIES_PIKACHU_ALOLA,
    SPECIES_PIKACHU_PARTNER,
    SPECIES_PIKACHU_WORLD,
    SPECIES_PICHU_SPIKY_EARED,
    SPECIES_UNOWN_B,
    SPECIES_UNOWN_C,
    SPECIES_UNOWN_D,
    SPECIES_UNOWN_E,
    SPECIES_UNOWN_F,
    SPECIES_UNOWN_G,
    SPECIES_UNOWN_H,
    SPECIES_UNOWN_I,
    SPECIES_UNOWN_J,
    SPECIES_UNOWN_K,
    SPECIES_UNOWN_L,
    SPECIES_UNOWN_M,
    SPECIES_UNOWN_N,
    SPECIES_UNOWN_O,
    SPECIES_UNOWN_P,
    SPECIES_UNOWN_Q,
    SPECIES_UNOWN_R,
    SPECIES_UNOWN_S,
    SPECIES_UNOWN_T,
    SPECIES_UNOWN_U,
    SPECIES_UNOWN_V,
    SPECIES_UNOWN_W,
    SPECIES_UNOWN_X,
    SPECIES_UNOWN_Y,
    SPECIES_UNOWN_Z,
    SPECIES_UNOWN_EXCLAMATION,
    SPECIES_UNOWN_QUESTION,
    SPECIES_DEOXYS_ATTACK,
    SPECIES_DEOXYS_DEFENSE,
    SPECIES_DEOXYS_SPEED,
    SPECIES_BURMY_SANDY,
    SPECIES_BURMY_TRASH,
    SPECIES_WORMADAM_SANDY,
    SPECIES_WORMADAM_TRASH,
    SPECIES_SHELLOS_EAST,
    SPECIES_GASTRODON_EAST,
    SPECIES_ROTOM_HEAT,
    SPECIES_ROTOM_WASH,
    SPECIES_ROTOM_FROST,
    SPECIES_ROTOM_FAN,
    SPECIES_ROTOM_MOW,
    SPECIES_BASCULIN_BLUE_STRIPED,
    SPECIES_BASCULIN_WHITE_STRIPED,
    SPECIES_DEERLING_SUMMER,
    SPECIES_DEERLING_AUTUMN,
    SPECIES_DEERLING_WINTER,
    SPECIES_SAWSBUCK_SUMMER,
    SPECIES_SAWSBUCK_AUTUMN,
    SPECIES_SAWSBUCK_WINTER,
    SPECIES_GRENINJA_BOND,
    SPECIES_GRENINJA_BATTLE_BOND,
    SPECIES_VIVILLON_POLAR,
    SPECIES_VIVILLON_TUNDRA,
    SPECIES_VIVILLON_CONTINENTAL,
    SPECIES_VIVILLON_GARDEN,
    SPECIES_VIVILLON_ELEGANT,
    SPECIES_VIVILLON_MEADOW,
    SPECIES_VIVILLON_MODERN,
    SPECIES_VIVILLON_MARINE,
    SPECIES_VIVILLON_ARCHIPELAGO,
    SPECIES_VIVILLON_HIGH_PLAINS,
    SPECIES_VIVILLON_SANDSTORM,
    SPECIES_VIVILLON_RIVER,
    SPECIES_VIVILLON_MONSOON,
    SPECIES_VIVILLON_SAVANNA,
    SPECIES_VIVILLON_SUN,
    SPECIES_VIVILLON_OCEAN,
    SPECIES_VIVILLON_JUNGLE,
    SPECIES_VIVILLON_FANCY,
    SPECIES_VIVILLON_POKEBALL,
    SPECIES_FLABEBE_YELLOW,
    SPECIES_FLABEBE_ORANGE,
    SPECIES_FLABEBE_BLUE,
    SPECIES_FLABEBE_WHITE,
    SPECIES_FLOETTE_YELLOW,
    SPECIES_FLOETTE_ORANGE,
    SPECIES_FLOETTE_BLUE,
    SPECIES_FLOETTE_WHITE,
    SPECIES_FLOETTE_ETERNAL,
    SPECIES_FLORGES_YELLOW,
    SPECIES_FLORGES_ORANGE,
    SPECIES_FLORGES_BLUE,
    SPECIES_FLORGES_WHITE,
    SPECIES_FURFROU_HEART,
    SPECIES_FURFROU_STAR,
    SPECIES_FURFROU_DIAMOND,
    SPECIES_FURFROU_DEBUTANTE,
    SPECIES_FURFROU_MATRON,
    SPECIES_FURFROU_DANDY,
    SPECIES_FURFROU_LA_REINE,
    SPECIES_FURFROU_KABUKI,
    SPECIES_FURFROU_PHARAOH,
    SPECIES_MEOWSTIC_F,
    SPECIES_PUMPKABOO_SMALL,
    SPECIES_PUMPKABOO_LARGE,
    SPECIES_PUMPKABOO_SUPER,
    SPECIES_GOURGEIST_SMALL,
    SPECIES_GOURGEIST_LARGE,
    SPECIES_GOURGEIST_SUPER,
    SPECIES_XERNEAS_ACTIVE,
    SPECIES_ZYGARDE_10_AURA_BREAK,
    SPECIES_ZYGARDE_10,
    SPECIES_ZYGARDE_10_POWER_CONSTRUCT,
    SPECIES_ZYGARDE_50_POWER_CONSTRUCT,
    SPECIES_ORICORIO_POM_POM,
    SPECIES_ORICORIO_PAU,
    SPECIES_ORICORIO_SENSU,
    SPECIES_ROCKRUFF_OWN_TEMPO,
    SPECIES_LYCANROC_MIDNIGHT,
    SPECIES_LYCANROC_DUSK,
    SPECIES_MINIOR_METEOR_ORANGE,
    SPECIES_MINIOR_METEOR_YELLOW,
    SPECIES_MINIOR_METEOR_GREEN,
    SPECIES_MINIOR_METEOR_BLUE,
    SPECIES_MINIOR_METEOR_INDIGO,
    SPECIES_MINIOR_METEOR_VIOLET,
    SPECIES_MINIOR_ORANGE,
    SPECIES_MINIOR_YELLOW,
    SPECIES_MINIOR_GREEN,
    SPECIES_MINIOR_BLUE,
    SPECIES_MINIOR_INDIGO,
    SPECIES_MINIOR_VIOLET,
    SPECIES_MAGEARNA_ORIGINAL,
    SPECIES_TOXTRICITY_LOW_KEY,
    SPECIES_SINISTEA_ANTIQUE,
    SPECIES_POLTEAGEIST_ANTIQUE,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_RUBY_CREAM,
    SPECIES_ALCREMIE_MATCHA_CREAM,
    SPECIES_ALCREMIE_MINT_CREAM,
    SPECIES_ALCREMIE_LEMON_CREAM,
    SPECIES_ALCREMIE_SALTED_CREAM,
    SPECIES_ALCREMIE_RUBY_SWIRL,
    SPECIES_ALCREMIE_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_RAINBOW_SWIRL,
    SPECIES_INDEEDEE_F,
    SPECIES_URSHIFU_RAPID_STRIKE,
    SPECIES_ZARUDE_DADA,
    SPECIES_BASCULEGION_F,
    SPECIES_ALCREMIE_BERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_BERRY,
    SPECIES_ALCREMIE_BERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_BERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_BERRY_MINT_CREAM,
    SPECIES_ALCREMIE_BERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_BERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_BERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_LOVE_VANILLA_CREAM,
    SPECIES_ALCREMIE_LOVE,
    SPECIES_ALCREMIE_LOVE_RUBY_CREAM,
    SPECIES_ALCREMIE_LOVE_MATCHA_CREAM,
    SPECIES_ALCREMIE_LOVE_MINT_CREAM,
    SPECIES_ALCREMIE_LOVE_LEMON_CREAM,
    SPECIES_ALCREMIE_LOVE_SALTED_CREAM,
    SPECIES_ALCREMIE_LOVE_RUBY_SWIRL,
    SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_STAR_VANILLA_CREAM,
    SPECIES_ALCREMIE_STAR,
    SPECIES_ALCREMIE_STAR_RUBY_CREAM,
    SPECIES_ALCREMIE_STAR_MATCHA_CREAM,
    SPECIES_ALCREMIE_STAR_MINT_CREAM,
    SPECIES_ALCREMIE_STAR_LEMON_CREAM,
    SPECIES_ALCREMIE_STAR_SALTED_CREAM,
    SPECIES_ALCREMIE_STAR_RUBY_SWIRL,
    SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM,
    SPECIES_ALCREMIE_CLOVER,
    SPECIES_ALCREMIE_CLOVER_RUBY_CREAM,
    SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM,
    SPECIES_ALCREMIE_CLOVER_MINT_CREAM,
    SPECIES_ALCREMIE_CLOVER_LEMON_CREAM,
    SPECIES_ALCREMIE_CLOVER_SALTED_CREAM,
    SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL,
    SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM,
    SPECIES_ALCREMIE_FLOWER,
    SPECIES_ALCREMIE_FLOWER_RUBY_CREAM,
    SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM,
    SPECIES_ALCREMIE_FLOWER_MINT_CREAM,
    SPECIES_ALCREMIE_FLOWER_LEMON_CREAM,
    SPECIES_ALCREMIE_FLOWER_SALTED_CREAM,
    SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL,
    SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM,
    SPECIES_ALCREMIE_RIBBON,
    SPECIES_ALCREMIE_RIBBON_RUBY_CREAM,
    SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM,
    SPECIES_ALCREMIE_RIBBON_MINT_CREAM,
    SPECIES_ALCREMIE_RIBBON_LEMON_CREAM,
    SPECIES_ALCREMIE_RIBBON_SALTED_CREAM,
    SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL,
    SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL,
    SPECIES_SPRIGATITO,
    SPECIES_FLORAGATO,
    SPECIES_MEOWSCARADA,
    SPECIES_FUECOCO,
    SPECIES_CROCALOR,
    SPECIES_SKELEDIRGE,
    SPECIES_QUAXLY,
    SPECIES_QUAXWELL,
    SPECIES_QUAQUAVAL,
    SPECIES_LECHONK,
    SPECIES_OINKOLOGNE_M,
    SPECIES_OINKOLOGNE,
    SPECIES_OINKOLOGNE_F,
    SPECIES_TAROUNTULA,
    SPECIES_SPIDOPS,
    SPECIES_NYMBLE,
    SPECIES_LOKIX,
    SPECIES_PAWMI,
    SPECIES_PAWMO,
    SPECIES_PAWMOT,
    SPECIES_TANDEMAUS,
    SPECIES_MAUSHOLD_THREE,
    SPECIES_MAUSHOLD,
    SPECIES_MAUSHOLD_FOUR,
    SPECIES_FIDOUGH,
    SPECIES_DACHSBUN,
    SPECIES_SMOLIV,
    SPECIES_DOLLIV,
    SPECIES_ARBOLIVA,
    SPECIES_SQUAWKABILLY_GREEN,
    SPECIES_SQUAWKABILLY,
    SPECIES_SQUAWKABILLY_BLUE,
    SPECIES_SQUAWKABILLY_YELLOW,
    SPECIES_SQUAWKABILLY_WHITE,
    SPECIES_NACLI,
    SPECIES_NACLSTACK,
    SPECIES_GARGANACL,
    SPECIES_CHARCADET,
    SPECIES_ARMAROUGE,
    SPECIES_CERULEDGE,
    SPECIES_TADBULB,
    SPECIES_BELLIBOLT,
    SPECIES_WATTREL,
    SPECIES_KILOWATTREL,
    SPECIES_MASCHIFF,
    SPECIES_MABOSSTIFF,
    SPECIES_SHROODLE,
    SPECIES_GRAFAIAI,
    SPECIES_BRAMBLIN,
    SPECIES_BRAMBLEGHAST,
    SPECIES_TOEDSCOOL,
    SPECIES_TOEDSCRUEL,
    SPECIES_KLAWF,
    SPECIES_CAPSAKID,
    SPECIES_SCOVILLAIN,
    SPECIES_RELLOR,
    SPECIES_RABSCA,
    SPECIES_FLITTLE,
    SPECIES_ESPATHRA,
    SPECIES_TINKATINK,
    SPECIES_TINKATUFF,
    SPECIES_TINKATON,
    SPECIES_WIGLETT,
    SPECIES_WUGTRIO,
    SPECIES_BOMBIRDIER,
    SPECIES_FINIZEN,
    SPECIES_PALAFIN_ZERO,
    SPECIES_PALAFIN,
    SPECIES_VAROOM,
    SPECIES_REVAVROOM,
    SPECIES_CYCLIZAR,
    SPECIES_ORTHWORM,
    SPECIES_GLIMMET,
    SPECIES_GLIMMORA,
    SPECIES_GREAVARD,
    SPECIES_HOUNDSTONE,
    SPECIES_FLAMIGO,
    SPECIES_CETODDLE,
    SPECIES_CETITAN,
    SPECIES_VELUZA,
    SPECIES_DONDOZO,
    SPECIES_TATSUGIRI_CURLY,
    SPECIES_TATSUGIRI,
    SPECIES_TATSUGIRI_DROOPY,
    SPECIES_TATSUGIRI_STRETCHY,
    SPECIES_ANNIHILAPE,
    SPECIES_CLODSIRE,
    SPECIES_FARIGIRAF,
    SPECIES_DUDUNSPARCE_TWO_SEGMENT,
    SPECIES_DUDUNSPARCE,
    SPECIES_DUDUNSPARCE_THREE_SEGMENT,
    SPECIES_KINGAMBIT,
    SPECIES_GREAT_TUSK,
    SPECIES_SCREAM_TAIL,
    SPECIES_BRUTE_BONNET,
    SPECIES_FLUTTER_MANE,
    SPECIES_SLITHER_WING,
    SPECIES_SANDY_SHOCKS,
    SPECIES_IRON_TREADS,
    SPECIES_IRON_BUNDLE,
    SPECIES_IRON_HANDS,
    SPECIES_IRON_JUGULIS,
    SPECIES_IRON_MOTH,
    SPECIES_IRON_THORNS,
    SPECIES_FRIGIBAX,
    SPECIES_ARCTIBAX,
    SPECIES_BAXCALIBUR,
    SPECIES_GIMMIGHOUL_CHEST,
    SPECIES_GIMMIGHOUL,
    SPECIES_GIMMIGHOUL_ROAMING,
    SPECIES_GHOLDENGO,
    SPECIES_WO_CHIEN,
    SPECIES_CHIEN_PAO,
    SPECIES_TING_LU,
    SPECIES_CHI_YU,
    SPECIES_ROARING_MOON,
    SPECIES_IRON_VALIANT,
    SPECIES_KORAIDON,
    SPECIES_MIRAIDON,
    SPECIES_TAUROS_PALDEA_COMBAT,
    SPECIES_TAUROS_PALDEA_BLAZE,
    SPECIES_TAUROS_PALDEA_AQUA,
    SPECIES_WOOPER_PALDEA,
    SPECIES_WALKING_WAKE,
    SPECIES_IRON_LEAVES,
    SPECIES_DIPPLIN,
    SPECIES_POLTCHAGEIST_COUNTERFEIT,
    SPECIES_POLTCHAGEIST,
    SPECIES_POLTCHAGEIST_ARTISAN,
    SPECIES_SINISTCHA_UNREMARKABLE,
    SPECIES_SINISTCHA,
    SPECIES_SINISTCHA_MASTERPIECE,
    SPECIES_OKIDOGI,
    SPECIES_MUNKIDORI,
    SPECIES_FEZANDIPITI,
    SPECIES_OGERPON_TEAL,
    SPECIES_OGERPON,
    SPECIES_URSALUNA_BLOODMOON,
    SPECIES_ARCHALUDON,
    SPECIES_HYDRAPPLE,
    SPECIES_GOUGING_FIRE,
    SPECIES_RAGING_BOLT,
    SPECIES_IRON_BOULDER,
    SPECIES_IRON_CROWN,
    SPECIES_TERAPAGOS_NORMAL,
    SPECIES_PECHARUNT,
    SPECIES_LUGIA_SHADOW,
    SPECIES_MOTHIM_SANDY,
    SPECIES_MOTHIM_TRASH,
    SPECIES_SCATTERBUG_POLAR,
    SPECIES_SCATTERBUG_TUNDRA,
    SPECIES_SCATTERBUG_CONTINENTAL,
    SPECIES_SCATTERBUG_GARDEN,
    SPECIES_SCATTERBUG_ELEGANT,
    SPECIES_SCATTERBUG_MEADOW,
    SPECIES_SCATTERBUG_MODERN,
    SPECIES_SCATTERBUG_MARINE,
    SPECIES_SCATTERBUG_ARCHIPELAGO,
    SPECIES_SCATTERBUG_HIGH_PLAINS,
    SPECIES_SCATTERBUG_SANDSTORM,
    SPECIES_SCATTERBUG_RIVER,
    SPECIES_SCATTERBUG_MONSOON,
    SPECIES_SCATTERBUG_SAVANNA,
    SPECIES_SCATTERBUG_SUN,
    SPECIES_SCATTERBUG_OCEAN,
    SPECIES_SCATTERBUG_JUNGLE,
    SPECIES_SCATTERBUG_FANCY,
    SPECIES_SCATTERBUG_POKEBALL,
    SPECIES_SPEWPA_POLAR,
    SPECIES_SPEWPA_TUNDRA,
    SPECIES_SPEWPA_CONTINENTAL,
    SPECIES_SPEWPA_GARDEN,
    SPECIES_SPEWPA_ELEGANT,
    SPECIES_SPEWPA_MEADOW,
    SPECIES_SPEWPA_MODERN,
    SPECIES_SPEWPA_MARINE,
    SPECIES_SPEWPA_ARCHIPELAGO,
    SPECIES_SPEWPA_HIGH_PLAINS,
    SPECIES_SPEWPA_SANDSTORM,
    SPECIES_SPEWPA_RIVER,
    SPECIES_SPEWPA_MONSOON,
    SPECIES_SPEWPA_SAVANNA,
    SPECIES_SPEWPA_SUN,
    SPECIES_SPEWPA_OCEAN,
    SPECIES_SPEWPA_JUNGLE,
    SPECIES_SPEWPA_FANCY,
    SPECIES_SPEWPA_POKEBALL,
    SPECIES_NONE,
};

static const u8 *FrontierCreator_GetTypeName(u32 type)
{
    if (type >= NUMBER_OF_MON_TYPES)
        return COMPOUND_STRING("----");

    if (sFrontierCreatorTypeNames[type] == NULL)
        return COMPOUND_STRING("----");

    return sFrontierCreatorTypeNames[type];
}

static const u8 sFrontierCreatorText_Controls[] = _("{CLEAR_TO 90}\n{A_BUTTON}けってい {B_BUTTON}やめる");

static const u16 sFrontierCreatorGmaxCapableSpecies[] =
{
    SPECIES_VENUSAUR,
    SPECIES_CHARIZARD,
    SPECIES_BLASTOISE,
    SPECIES_BUTTERFREE,
    SPECIES_PIKACHU,
    SPECIES_MEOWTH,
    SPECIES_MACHAMP,
    SPECIES_GENGAR,
    SPECIES_KINGLER,
    SPECIES_LAPRAS,
    SPECIES_EEVEE,
    SPECIES_SNORLAX,
    SPECIES_GARBODOR,
    SPECIES_MELMETAL,
    SPECIES_RILLABOOM,
    SPECIES_CINDERACE,
    SPECIES_INTELEON,
    SPECIES_CORVIKNIGHT,
    SPECIES_ORBEETLE,
    SPECIES_DREDNAW,
    SPECIES_COALOSSAL,
    SPECIES_FLAPPLE,
    SPECIES_APPLETUN,
    SPECIES_SANDACONDA,
    SPECIES_CENTISKORCH,
    SPECIES_HATTERENE,
    SPECIES_GRIMMSNARL,
    SPECIES_ALCREMIE,
    SPECIES_COPPERAJAH,
    SPECIES_DURALUDON,
    SPECIES_NONE,
};

static const enum Item sFrontierHubGiveItems[] =
{
    // 種族専用アイテム
    ITEM_LIGHT_BALL,
    ITEM_LEEK,
    ITEM_THICK_CLUB,
    ITEM_LUCKY_PUNCH,
    ITEM_METAL_POWDER,
    ITEM_QUICK_POWDER,
    ITEM_DEEP_SEA_SCALE,
    ITEM_DEEP_SEA_TOOTH,

    // ドライブ
    ITEM_DOUSE_DRIVE,
    ITEM_SHOCK_DRIVE,
    ITEM_BURN_DRIVE,
    ITEM_CHILL_DRIVE,

    // メモリ
    ITEM_BUG_MEMORY,
    ITEM_DARK_MEMORY,
    ITEM_DRAGON_MEMORY,
    ITEM_ELECTRIC_MEMORY,
    ITEM_FAIRY_MEMORY,
    ITEM_FIGHTING_MEMORY,
    ITEM_FIRE_MEMORY,
    ITEM_FLYING_MEMORY,
    ITEM_GHOST_MEMORY,
    ITEM_GRASS_MEMORY,
    ITEM_GROUND_MEMORY,
    ITEM_ICE_MEMORY,
    ITEM_POISON_MEMORY,
    ITEM_PSYCHIC_MEMORY,
    ITEM_ROCK_MEMORY,
    ITEM_STEEL_MEMORY,
    ITEM_WATER_MEMORY,

    // メガストーン
    ITEM_ABOMASITE,
    ITEM_ABSOLITE,
    ITEM_AERODACTYLITE,
    ITEM_AGGRONITE,
    ITEM_ALAKAZITE,
    ITEM_ALTARIANITE,
    ITEM_AMPHAROSITE,
    ITEM_AUDINITE,
    ITEM_BANETTITE,
    ITEM_BARBARACITE,
    ITEM_BAXCALIBRITE,
    ITEM_BEEDRILLITE,
    ITEM_BLACK_AUGURITE,
    ITEM_BLASTOISINITE,
    ITEM_BLAZIKENITE,
    ITEM_CAMERUPTITE,
    ITEM_CHANDELURITE,
    ITEM_CHARIZARDITE_X,
    ITEM_CHARIZARDITE_Y,
    ITEM_CHESNAUGHTITE,
    ITEM_CHIMECHITE,
    ITEM_CLEFABLITE,
    ITEM_CRABOMINITE,
    ITEM_DARKRANITE,
    ITEM_DELPHOXITE,
    ITEM_DIANCITE,
    ITEM_DRAGALGITE,
    ITEM_DRAGONINITE,
    ITEM_DRAMPANITE,
    ITEM_EELEKTROSSITE,
    ITEM_EMBOARITE,
    ITEM_EVIOLITE,
    ITEM_EXCADRITE,
    ITEM_FALINKSITE,
    ITEM_FERALIGITE,
    ITEM_FLOETTITE,
    ITEM_FROSLASSITE,
    ITEM_GALLADITE,
    ITEM_GARCHOMPITE,
    ITEM_GARDEVOIRITE,
    ITEM_GENGARITE,
    ITEM_GLALITITE,
    ITEM_GLIMMORANITE,
    ITEM_GOLISOPITE,
    ITEM_GOLURKITE,
    ITEM_GRENINJITE,
    ITEM_GYARADOSITE,
    ITEM_HAWLUCHANITE,
    ITEM_HEATRANITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_KANGASKHANITE,
    ITEM_LATIASITE,
    ITEM_LATIOSITE,
    ITEM_LOPUNNITE,
    ITEM_LUCARIONITE,
    ITEM_MAGEARNITE,
    ITEM_MALAMARITE,
    ITEM_MANECTITE,
    ITEM_MAWILITE,
    ITEM_MEDICHAMITE,
    ITEM_MEGANIUMITE,
    ITEM_MEOWSTICITE,
    ITEM_METAGROSSITE,
    ITEM_METEORITE,
    ITEM_MEWTWONITE_X,
    ITEM_MEWTWONITE_Y,
    ITEM_PIDGEOTITE,
    ITEM_PINSIRITE,
    ITEM_PYROARITE,
    ITEM_RAICHUNITE_X,
    ITEM_RAICHUNITE_Y,
    ITEM_SABLENITE,
    ITEM_SALAMENCITE,
    ITEM_SCEPTILITE,
    ITEM_SCIZORITE,
    ITEM_SCOLIPITE,
    ITEM_SCOVILLAINITE,
    ITEM_SCRAFTINITE,
    ITEM_SHARPEDONITE,
    ITEM_SKARMORITE,
    ITEM_SLOWBRONITE,
    ITEM_STARAPTITE,
    ITEM_STARMINITE,
    ITEM_STEELIXITE,
    ITEM_SWAMPERTITE,
    ITEM_TATSUGIRINITE,
    ITEM_TYRANITARITE,
    ITEM_VENUSAURITE,
    ITEM_VICTREEBELITE,
    ITEM_ZERAORITE,
    ITEM_ZYGARDITE,

    // Zクリスタル
    ITEM_ABSOLITE_Z,
    ITEM_ALORAICHIUM_Z,
    ITEM_BUGINIUM_Z,
    ITEM_DARKINIUM_Z,
    ITEM_DECIDIUM_Z,
    ITEM_DRAGONIUM_Z,
    ITEM_EEVIUM_Z,
    ITEM_ELECTRIUM_Z,
    ITEM_FAIRIUM_Z,
    ITEM_FIGHTINIUM_Z,
    ITEM_FIRIUM_Z,
    ITEM_FLYINIUM_Z,
    ITEM_GARCHOMPITE_Z,
    ITEM_GHOSTIUM_Z,
    ITEM_GRASSIUM_Z,
    ITEM_GROUNDIUM_Z,
    ITEM_ICIUM_Z,
    ITEM_INCINIUM_Z,
    ITEM_KOMMONIUM_Z,
    ITEM_LUCARIONITE_Z,
    ITEM_LUNALIUM_Z,
    ITEM_LYCANIUM_Z,
    ITEM_MARSHADIUM_Z,
    ITEM_MEWNIUM_Z,
    ITEM_MIMIKIUM_Z,
    ITEM_NORMALIUM_Z,
    ITEM_PIKANIUM_Z,
    ITEM_PIKASHUNIUM_Z,
    ITEM_POISONIUM_Z,
    ITEM_PRIMARIUM_Z,
    ITEM_PSYCHIUM_Z,
    ITEM_ROCKIUM_Z,
    ITEM_SNORLIUM_Z,
    ITEM_SOLGANIUM_Z,
    ITEM_STEELIUM_Z,
    ITEM_TAPUNIUM_Z,
    ITEM_ULTRANECROZIUM_Z,
    ITEM_WATERIUM_Z,
    ITEM_Z_POWER_RING,

    // プレート
    ITEM_DRACO_PLATE,
    ITEM_DREAD_PLATE,
    ITEM_EARTH_PLATE,
    ITEM_FIST_PLATE,
    ITEM_FLAME_PLATE,
    ITEM_ICICLE_PLATE,
    ITEM_INSECT_PLATE,
    ITEM_IRON_PLATE,
    ITEM_MEADOW_PLATE,
    ITEM_MIND_PLATE,
    ITEM_PIXIE_PLATE,
    ITEM_SKY_PLATE,
    ITEM_SPLASH_PLATE,
    ITEM_SPOOKY_PLATE,
    ITEM_STONE_PLATE,
    ITEM_TOXIC_PLATE,
    ITEM_ZAP_PLATE,

    // ジュエル
    ITEM_BUG_GEM,
    ITEM_DARK_GEM,
    ITEM_DRAGON_GEM,
    ITEM_ELECTRIC_GEM,
    ITEM_FAIRY_GEM,
    ITEM_FIGHTING_GEM,
    ITEM_FIRE_GEM,
    ITEM_FLYING_GEM,
    ITEM_GHOST_GEM,
    ITEM_GRASS_GEM,
    ITEM_GROUND_GEM,
    ITEM_ICE_GEM,
    ITEM_NORMAL_GEM,
    ITEM_POISON_GEM,
    ITEM_PSYCHIC_GEM,
    ITEM_ROCK_GEM,
    ITEM_STEEL_GEM,
    ITEM_WATER_GEM,

    // 伝説専用アイテム
    ITEM_ADAMANT_CRYSTAL,
    ITEM_ADAMANT_ORB,
    ITEM_BLUE_ORB,
    ITEM_GRISEOUS_CORE,
    ITEM_GRISEOUS_ORB,
    ITEM_LUSTROUS_GLOBE,
    ITEM_LUSTROUS_ORB,
    ITEM_RED_ORB,
    ITEM_RUSTED_SHIELD,
    ITEM_RUSTED_SWORD,
    ITEM_SOUL_DEW,

    // オーガポンのめん
    ITEM_CORNERSTONE_MASK,
    ITEM_HEARTHFLAME_MASK,
    ITEM_WELLSPRING_MASK,

    ITEM_NONE,
};

static u16 FrontierItemGiver_GetItemCount(void)
{
    u16 count = 0;

    while (sFrontierHubGiveItems[count] != ITEM_NONE)
        count++;

    return count;
}

static bool32 FrontierCreator_CanGmax(enum Species species)
{
    u32 i;

    for (i = 0; sFrontierCreatorGmaxCapableSpecies[i] != SPECIES_NONE; i++)
    {
        if (sFrontierCreatorGmaxCapableSpecies[i] == species)
            return TRUE;
    }

    return FALSE;
}

static bool32 FrontierCreator_IsAllowedBaseSpecies(enum Species species)
{
    u32 i;

    for (i = 0; sFrontierCreatorAllowedBaseSpecies[i] != SPECIES_NONE; i++)
    {
        if (sFrontierCreatorAllowedBaseSpecies[i] == species)
            return TRUE;
    }

    return FALSE;
}

static bool32 FrontierCreator_IsBannedSpecies(enum Species species)
{
    if (species == SPECIES_NONE || species >= NUM_SPECIES)
        return TRUE;

#ifdef SPECIES_CUSTOM_START
    if (species >= SPECIES_CUSTOM_START)
        return TRUE;
#endif

    if (species == SPECIES_PIKACHU_STARTER || species == SPECIES_EEVEE_STARTER)
        return TRUE;

    if (!FrontierCreator_IsAllowedBaseSpecies(species))
        return TRUE;

    if (!IsSpeciesEnabled(species))
        return TRUE;

    return FALSE;
}

static void FrontierCreator_InitDefaultData(void)
{
    u32 i;

    sFrontierCreatorData->species = SPECIES_BULBASAUR;
    sFrontierCreatorData->level = 50;
    sFrontierCreatorData->abilityNum = 0;
    sFrontierCreatorData->nature = NATURE_HARDY;
    sFrontierCreatorData->teraType = TYPE_NORMAL;

    for (i = 0; i < NUM_STATS; i++)
    {
        sFrontierCreatorData->ivs[i] = 31;
        sFrontierCreatorData->evs[i] = 0;
    }
}

static void FrontierCreator_ClearWindow(u8 windowId)
{
    FillWindowPixelBuffer(windowId, PIXEL_FILL(1));
}

static void FrontierCreator_PrintWindow(u8 windowId)
{
    AddTextPrinterParameterized(windowId, FRONTIER_CREATOR_FONT, gStringVar4, 0, 0, 0, NULL);
    CopyWindowToVram(windowId, COPYWIN_FULL);
}

static void FrontierCreator_DrawNatureScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;
    u8 nature = gTasks[taskId].tInput;

    if (nature > NUM_NATURES)
        nature = NUM_NATURES;

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("せいかくを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("No."));
    ConvertIntToDecimalStringN(gStringVar1, nature, STR_CONV_MODE_LEADING_ZEROS, 2);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("せいかく: "));
    StringAppend(gStringVar4, sFrontierCreatorNatureNames[nature]);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("けた: "));
    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tDigit, STR_CONV_MODE_LEADING_ZEROS, 1);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう {LEFT_ARROW}{RIGHT_ARROW}けた"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_DrawTeraTypeScreen(u8 taskId);

static void FrontierCreator_DrawBooleanScreen(u8 windowId, const u8 *title, bool32 value)
{
    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, title);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("せってい: "));
    if (value)
        StringAppend(gStringVar4, COMPOUND_STRING("オン"));
    else
        StringAppend(gStringVar4, COMPOUND_STRING("オフ"));

    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));
    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}きりかえ"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_HandleNumericInput(u8 taskId, s32 min, s32 max, u8 digits)
{
    s32 value = gTasks[taskId].tInput;

    if (JOY_NEW(DPAD_UP))
    {
        value += sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        if (value > max)
            value = max;
    }

    if (JOY_NEW(DPAD_DOWN))
    {
        value -= sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        if (value < min)
            value = min;
    }

    if (JOY_NEW(DPAD_LEFT))
    {
        if (gTasks[taskId].tDigit > 0)
            gTasks[taskId].tDigit--;
    }

    if (JOY_NEW(DPAD_RIGHT))
    {
        if (gTasks[taskId].tDigit < digits - 1)
            gTasks[taskId].tDigit++;
    }

    gTasks[taskId].tInput = value;
}

static void FrontierCreator_HandleSpeciesInput(u8 taskId)
{
    s32 oldValue = gTasks[taskId].tInput;
    s32 value = oldValue;
    s16 direction = 1;

    if (JOY_NEW(DPAD_UP))
    {
        value += sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        direction = 1;
    }

    if (JOY_NEW(DPAD_DOWN))
    {
        value -= sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        direction = -1;
    }

    if (JOY_NEW(DPAD_LEFT))
    {
        if (gTasks[taskId].tDigit > 0)
            gTasks[taskId].tDigit--;
    }

    if (JOY_NEW(DPAD_RIGHT))
    {
        if (gTasks[taskId].tDigit < FRONTIER_CREATOR_SPECIES_DIGITS - 1)
            gTasks[taskId].tDigit++;
    }

    if (value < SPECIES_BULBASAUR)
        value = NUM_SPECIES - 1;

    if (value >= NUM_SPECIES)
        value = SPECIES_BULBASAUR;

    if (value != oldValue && FrontierCreator_IsBannedSpecies(value))
        value = FrontierCreator_GetNextAllowedSpecies(value, direction);

    gTasks[taskId].tInput = value;
}

static void FrontierCreator_DestroySpeciesPreview(u8 taskId)
{
    StopCry();

    if (gTasks[taskId].tPreviewSpriteId != FRONTIER_CREATOR_PREVIEW_NONE)
    {
        FreeAndDestroyMonPicSprite(gTasks[taskId].tPreviewSpriteId);
        gTasks[taskId].tPreviewSpriteId = FRONTIER_CREATOR_PREVIEW_NONE;
    }

    gTasks[taskId].tPreviewSpecies = SPECIES_NONE;
}

static void FrontierCreator_UpdateSpeciesPreview(u8 taskId, enum Species species, bool8 playCry)
{
    u16 spriteId;

    if (gTasks[taskId].tPreviewSpriteId != FRONTIER_CREATOR_PREVIEW_NONE
     && gTasks[taskId].tPreviewSpecies == species)
        return;

    FrontierCreator_DestroySpeciesPreview(taskId);

    spriteId = CreateMonPicSprite(
        species,
        FALSE,
        0,
        TRUE,
        FRONTIER_CREATOR_PREVIEW_X,
        FRONTIER_CREATOR_PREVIEW_Y,
        FRONTIER_CREATOR_PREVIEW_PAL,
        TAG_NONE);

    if (spriteId == 0xFFFF)
        return;

    gTasks[taskId].tPreviewSpriteId = spriteId;
    gTasks[taskId].tPreviewSpecies = species;

    if (playCry)
        PlayCry_Normal(species, 0);
}

static u16 FrontierCreator_GetEVTotalExcept(u8 statId)
{
    u16 total = 0;
    u32 i;

    for (i = 0; i < NUM_STATS; i++)
    {
        if (i != statId)
            total += sFrontierCreatorData->evs[i];
    }

    return total;
}


static u16 FrontierCreator_GetMaxEVForStat(u8 statId)
{
    u16 totalExcept = FrontierCreator_GetEVTotalExcept(statId);
    u16 remaining;

    if (totalExcept >= FRONTIER_CREATOR_MAX_TOTAL_EVS)
        return 0;

    remaining = FRONTIER_CREATOR_MAX_TOTAL_EVS - totalExcept;

    if (remaining > FRONTIER_CREATOR_MAX_PER_STAT_EVS)
        return FRONTIER_CREATOR_MAX_PER_STAT_EVS;

    return remaining;
}

static void FrontierCreator_DrawSpeciesScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;
    enum Species species = gTasks[taskId].tInput;

    if (FrontierCreator_IsBannedSpecies(species))
    {
        species = FrontierCreator_GetNextAllowedSpecies(species, 1);
        gTasks[taskId].tInput = species;
    }

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("しゅるいを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("No."));
    ConvertIntToDecimalStringN(gStringVar1, species, STR_CONV_MODE_LEADING_ZEROS, 4);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("なまえ: "));
    StringAppend(gStringVar4, GetSpeciesName(species));
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("このしゅるいは OK{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("けた: 10 "));
    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tDigit, STR_CONV_MODE_LEADING_ZEROS, 1);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう {LEFT_ARROW}{RIGHT_ARROW}けた"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_DrawLevelScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("レベルを えらぶ{CLEAR_TO 90}\n"));
    StringAppend(gStringVar4, COMPOUND_STRING("レベル: "));

    ConvertIntToDecimalStringN(gStringVar1, sFrontierCreatorData->level, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW} 50/100"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_DrawAbilityScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;
    u8 slot = gTasks[taskId].tInput;
    enum Ability ability = GetSpeciesAbility(sFrontierCreatorData->species, slot);

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("とくせいを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("スロット: "));
    ConvertIntToDecimalStringN(gStringVar1, slot, STR_CONV_MODE_LEADING_ZEROS, 1);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("とくせい: "));
    if (ability == ABILITY_NONE)
        StringAppend(gStringVar4, COMPOUND_STRING("----"));
    else
         StringAppend(gStringVar4, gAbilitiesInfo[ability].name);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    if (ability == ABILITY_NONE)
        StringAppend(gStringVar4, COMPOUND_STRING("これは えらべません{CLEAR_TO 90}\n"));
    else
        StringAppend(gStringVar4, COMPOUND_STRING("このとくせいは OK{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}
static void FrontierCreator_DrawTeraTypeScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;
    u32 type = gTasks[taskId].tInput;

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("テラスタイプを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("No."));
    ConvertIntToDecimalStringN(gStringVar1, type, STR_CONV_MODE_LEADING_ZEROS, 2);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("タイプ: "));
    StringAppend(gStringVar4, FrontierCreator_GetTypeName(type));
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    if (type == TYPE_NONE || type == TYPE_MYSTERY)
        StringAppend(gStringVar4, COMPOUND_STRING("これは えらべません{CLEAR_TO 90}\n"));
    else
        StringAppend(gStringVar4, COMPOUND_STRING("このタイプは OK{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("けた: "));
    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tDigit, STR_CONV_MODE_LEADING_ZEROS, 1);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう {LEFT_ARROW}{RIGHT_ARROW}けた"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_DrawIVScreen(u8 taskId)
{
    u8 statId = gTasks[taskId].tStatId;
    u8 windowId = gTasks[taskId].tWindowId;

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("こたいちを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, sFrontierCreatorStatNames[statId]);
    StringAppend(gStringVar4, COMPOUND_STRING(": "));

    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tInput, STR_CONV_MODE_LEADING_ZEROS, 2);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING(" / 31{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("けた: 10 "));
    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tDigit, STR_CONV_MODE_LEADING_ZEROS, 1);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう {LEFT_ARROW}{RIGHT_ARROW}けた"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierCreator_DrawEVScreen(u8 taskId)
{
    u8 statId = gTasks[taskId].tStatId;
    u8 windowId = gTasks[taskId].tWindowId;
    u16 max = FrontierCreator_GetMaxEVForStat(statId);
    u16 totalExcept = FrontierCreator_GetEVTotalExcept(statId);

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("きそポイントを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, sFrontierCreatorStatNames[statId]);
    StringAppend(gStringVar4, COMPOUND_STRING(": "));

    ConvertIntToDecimalStringN(gStringVar1, gTasks[taskId].tInput, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);

    StringAppend(gStringVar4, COMPOUND_STRING(" / "));
    ConvertIntToDecimalStringN(gStringVar1, max, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("ほかのごうけい: "));
    ConvertIntToDecimalStringN(gStringVar1, totalExcept, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("ごうけい: "));
    ConvertIntToDecimalStringN(gStringVar1, totalExcept + gTasks[taskId].tInput, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING(" / 510{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}へんこう {LEFT_ARROW}{RIGHT_ARROW}けた"));
    StringAppend(gStringVar4, sFrontierCreatorText_Controls);

    FrontierCreator_PrintWindow(windowId);
}

static enum Species FrontierCreator_GetFirstAllowedSpecies(void)
{
    enum Species species;

    for (species = SPECIES_BULBASAUR; species < NUM_SPECIES; species++)
    {
        if (!FrontierCreator_IsBannedSpecies(species))
            return species;
    }

    return SPECIES_BULBASAUR;
}

static enum Species FrontierCreator_GetNextAllowedSpecies(enum Species species, s16 delta)
{
    u32 guard = 0;

    do
    {
        species += delta;

        if (species <= SPECIES_NONE)
            species = NUM_SPECIES - 1;
        else if (species >= NUM_SPECIES)
            species = SPECIES_BULBASAUR;

        guard++;
        if (guard > NUM_SPECIES)
            return FrontierCreator_GetFirstAllowedSpecies();
    }
    while (FrontierCreator_IsBannedSpecies(species));

    return species;
}

static void FrontierCreator_CreateMonAndGive(void)
{
    struct Pokemon mon;
    u32 personality;
    u8 dmaxLevel = FRONTIER_CREATOR_DYNAMAX_LEVEL;
    u8 gmaxFactor = sFrontierCreatorData->gmaxFactor;
    u32 teraType = sFrontierCreatorData->teraType;
    u8 abilityNum = sFrontierCreatorData->abilityNum;
    u8 isShiny = FALSE;
    u32 i;
    u8 ivVal;
    u8 evVal;

    if (!FrontierCreator_CanGmax(sFrontierCreatorData->species))
        gmaxFactor = FALSE;

    personality = GetMonPersonality(
        sFrontierCreatorData->species,
        MON_GENDER_RANDOM,
        sFrontierCreatorData->nature,
        RANDOM_UNOWN_LETTER
    );

    CreateMon(
        &mon,
        sFrontierCreatorData->species,
        sFrontierCreatorData->level,
        personality,
        OTID_STRUCT_PLAYER_ID
    );

    SetMonData(&mon, MON_DATA_IS_SHINY, &isShiny);
    SetMonData(&mon, MON_DATA_GIGANTAMAX_FACTOR, &gmaxFactor);
    SetMonData(&mon, MON_DATA_DYNAMAX_LEVEL, &dmaxLevel);

    if (teraType == TYPE_NONE || teraType == TYPE_MYSTERY || teraType >= NUMBER_OF_MON_TYPES)
        teraType = GetTeraTypeFromPersonality(&mon);

    SetMonData(&mon, MON_DATA_TERA_TYPE, &teraType);

    for (i = 0; i < NUM_STATS; i++)
    {
        ivVal = sFrontierCreatorData->ivs[i];
        SetMonData(&mon, MON_DATA_HP_IV + i, &ivVal);
    }

    for (i = 0; i < NUM_STATS; i++)
    {
        evVal = sFrontierCreatorData->evs[i];
        SetMonData(&mon, MON_DATA_HP_EV + i, &evVal);
    }

    GiveMonInitialMoveset(&mon);

    SetMonData(&mon, MON_DATA_ABILITY_NUM, &abilityNum);

    CalculateMonStats(&mon);

    GiveScriptedMonToPlayer(&mon, PARTY_SIZE);
    FlagSet(FLAG_SYS_POKEMON_GET);

    gSpecialVar_Result = TRUE;
}

static void FrontierCreator_DestroyAndReturn(u8 taskId)
{
    FrontierCreator_DestroySpeciesPreview(taskId);
    ClearStdWindowAndFrame(gTasks[taskId].tWindowId, TRUE);
    RemoveWindow(gTasks[taskId].tWindowId);
    DestroyTask(taskId);

    if (sFrontierCreatorData != NULL)
    {
        Free(sFrontierCreatorData);
        sFrontierCreatorData = NULL;
    }

    ScriptContext_Enable();
    UnfreezeObjectEvents();
    UnlockPlayerFieldControls();
}

static void Task_FrontierCreator_SelectSpecies(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        enum Species oldSpecies = gTasks[taskId].tInput;

        PlaySE(SE_SELECT);
        FrontierCreator_HandleSpeciesInput(taskId);
        FrontierCreator_DrawSpeciesScreen(taskId);

        if (gTasks[taskId].tInput != oldSpecies)
            FrontierCreator_UpdateSpeciesPreview(taskId, gTasks[taskId].tInput, TRUE);
    }

    if (JOY_NEW(A_BUTTON))
    {
        if (FrontierCreator_IsBannedSpecies(gTasks[taskId].tInput))
        {
            PlaySE(SE_PC_OFF);
            gTasks[taskId].tInput = FrontierCreator_GetFirstAllowedSpecies();
            FrontierCreator_DrawSpeciesScreen(taskId);
            FrontierCreator_UpdateSpeciesPreview(taskId, gTasks[taskId].tInput, FALSE);
            return;
        }

        PlaySE(SE_SELECT);
        sFrontierCreatorData->species = gTasks[taskId].tInput;

        FrontierCreator_DestroySpeciesPreview(taskId);
        FrontierCreator_DrawLevelScreen(taskId);
        gTasks[taskId].func = Task_FrontierCreator_SelectLevel;
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectLevel(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);

        if (sFrontierCreatorData->level == FRONTIER_CREATOR_LEVEL_50)
            sFrontierCreatorData->level = FRONTIER_CREATOR_LEVEL_100;
        else
            sFrontierCreatorData->level = FRONTIER_CREATOR_LEVEL_50;

        FrontierCreator_DrawLevelScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        PlaySE(SE_SELECT);
        gTasks[taskId].tInput = NUM_NATURES;
        gTasks[taskId].tDigit = 0;

        FrontierCreator_DrawNatureScreen(taskId);
        gTasks[taskId].func = Task_FrontierCreator_SelectNature;
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectNature(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        FrontierCreator_HandleNumericInput(taskId, 0, NUM_NATURES, FRONTIER_CREATOR_NATURE_DIGITS);
        FrontierCreator_DrawNatureScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        PlaySE(SE_SELECT);

        if (gTasks[taskId].tInput >= NUM_NATURES)
            sFrontierCreatorData->nature = NATURE_RANDOM;
        else
            sFrontierCreatorData->nature = gTasks[taskId].tInput;

        gTasks[taskId].tInput = 0;
        gTasks[taskId].tDigit = 0;

        FrontierCreator_DrawAbilityScreen(taskId);
        gTasks[taskId].func = Task_FrontierCreator_SelectAbility;
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectAbility(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        FrontierCreator_HandleNumericInput(taskId, 0, NUM_ABILITY_SLOTS - 1, FRONTIER_CREATOR_ABILITY_DIGITS);
        FrontierCreator_DrawAbilityScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        if (GetSpeciesAbility(sFrontierCreatorData->species, gTasks[taskId].tInput) == ABILITY_NONE)
        {
            PlaySE(SE_PC_OFF);
            return;
        }

        PlaySE(SE_SELECT);
        sFrontierCreatorData->abilityNum = gTasks[taskId].tInput;
        gTasks[taskId].tInput = TYPE_NORMAL;
        gTasks[taskId].tDigit = 0;

        FrontierCreator_DrawTeraTypeScreen(taskId);
        gTasks[taskId].func = Task_FrontierCreator_SelectTeraType;
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectTeraType(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        FrontierCreator_HandleNumericInput(taskId, 0, NUMBER_OF_MON_TYPES - 1, FRONTIER_CREATOR_TYPE_DIGITS);
        FrontierCreator_DrawTeraTypeScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        if (gTasks[taskId].tInput == TYPE_NONE || gTasks[taskId].tInput == TYPE_MYSTERY)
        {
            PlaySE(SE_PC_OFF);
            return;
        }

        PlaySE(SE_SELECT);
        sFrontierCreatorData->teraType = gTasks[taskId].tInput;

        if (FrontierCreator_CanGmax(sFrontierCreatorData->species))
        {
            gTasks[taskId].tInput = FALSE;
            FrontierCreator_DrawBooleanScreen(
                gTasks[taskId].tWindowId,
                COMPOUND_STRING("キョダイマックス"),
                gTasks[taskId].tInput
            );
            gTasks[taskId].func = Task_FrontierCreator_SelectGmax;
        }
        else
        {
            sFrontierCreatorData->gmaxFactor = FALSE;
            gTasks[taskId].tStatId = 0;
            gTasks[taskId].tInput = FRONTIER_CREATOR_MAX_IVS;
            gTasks[taskId].tDigit = 0;
            FrontierCreator_DrawIVScreen(taskId);
            gTasks[taskId].func = Task_FrontierCreator_SelectIVs;
        }
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectGmax(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        gTasks[taskId].tInput = !gTasks[taskId].tInput;
        FrontierCreator_DrawBooleanScreen(
            gTasks[taskId].tWindowId,
            COMPOUND_STRING("キョダイマックス"),
            gTasks[taskId].tInput
        );
    }

    if (JOY_NEW(A_BUTTON))
    {
        PlaySE(SE_SELECT);
        sFrontierCreatorData->gmaxFactor = gTasks[taskId].tInput;

        gTasks[taskId].tStatId = 0;
        gTasks[taskId].tInput = FRONTIER_CREATOR_MAX_IVS;
        gTasks[taskId].tDigit = 0;
        FrontierCreator_DrawIVScreen(taskId);
        gTasks[taskId].func = Task_FrontierCreator_SelectIVs;
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectIVs(u8 taskId)
{
    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        FrontierCreator_HandleNumericInput(taskId, 0, FRONTIER_CREATOR_MAX_IVS, FRONTIER_CREATOR_IV_DIGITS);
        FrontierCreator_DrawIVScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        PlaySE(SE_SELECT);
        sFrontierCreatorData->ivs[gTasks[taskId].tStatId] = gTasks[taskId].tInput;

        if (gTasks[taskId].tStatId < NUM_STATS - 1)
        {
            gTasks[taskId].tStatId++;
            gTasks[taskId].tInput = FRONTIER_CREATOR_MAX_IVS;
            gTasks[taskId].tDigit = 0;
            FrontierCreator_DrawIVScreen(taskId);
        }
        else
        {
            gTasks[taskId].tStatId = 0;
            gTasks[taskId].tInput = 0;
            gTasks[taskId].tDigit = 0;
            FrontierCreator_DrawEVScreen(taskId);
            gTasks[taskId].func = Task_FrontierCreator_SelectEVs;
        }
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void Task_FrontierCreator_SelectEVs(u8 taskId)
{
    u16 max = FrontierCreator_GetMaxEVForStat(gTasks[taskId].tStatId);

    if (gTasks[taskId].tInput > max)
        gTasks[taskId].tInput = max;

    if (JOY_NEW(DPAD_ANY))
    {
        PlaySE(SE_SELECT);
        FrontierCreator_HandleNumericInput(taskId, 0, max, FRONTIER_CREATOR_EV_DIGITS);
        FrontierCreator_DrawEVScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        PlaySE(SE_SELECT);
        sFrontierCreatorData->evs[gTasks[taskId].tStatId] = gTasks[taskId].tInput;

        if (gTasks[taskId].tStatId < NUM_STATS - 1)
        {
            gTasks[taskId].tStatId++;
            gTasks[taskId].tInput = 0;
            gTasks[taskId].tDigit = 0;
            FrontierCreator_DrawEVScreen(taskId);
        }
        else
        {
            FrontierCreator_CreateMonAndGive();
            PlaySE(MUS_LEVEL_UP);
            FrontierCreator_DestroyAndReturn(taskId);
        }
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierCreator_DestroyAndReturn(taskId);
    }
}

static void FrontierHub_TryAddItem(enum Item itemId)
{
    if (itemId == ITEM_NONE)
        return;

    if (!CheckBagHasItem(itemId, 1) && CheckBagHasSpace(itemId, 1))
        AddBagItem(itemId, 1);
}

static void FrontierHub_GiveAllKeyItems(void)
{
    enum Item itemId;

    for (itemId = ITEM_NONE + 1; itemId < ITEMS_COUNT; itemId++)
    {
        if (GetItemPocket(itemId) == POCKET_KEY_ITEMS)
            FrontierHub_TryAddItem(itemId);
    }
}

static void FrontierHub_GiveAutoItems(void)
{
    u32 i;

    for (i = 0; sFrontierHubAutoItems[i].itemId != ITEM_NONE; i++)
    {
        if (!CheckBagHasItem(sFrontierHubAutoItems[i].itemId, 1)
         && CheckBagHasSpace(sFrontierHubAutoItems[i].itemId, sFrontierHubAutoItems[i].quantity))
            AddBagItem(sFrontierHubAutoItems[i].itemId, sFrontierHubAutoItems[i].quantity);
    }
}

static void FrontierHub_GiveGimmickKeyItems(void)
{
    FrontierHub_TryAddItem(ITEM_MEGA_RING);
    FrontierHub_TryAddItem(ITEM_Z_POWER_RING);
    FrontierHub_TryAddItem(ITEM_DYNAMAX_BAND);
    FrontierHub_TryAddItem(ITEM_TERA_ORB);
}

static void FrontierItemGiver_DrawScreen(u8 taskId)
{
    u8 windowId = gTasks[taskId].tWindowId;
    u16 itemCount = FrontierItemGiver_GetItemCount();
    u16 index = gTasks[taskId].tInput;
    enum Item itemId;

    if (itemCount == 0)
        index = 0;
    else if (index >= itemCount)
        index = itemCount - 1;

    itemId = sFrontierHubGiveItems[index];

    FrontierCreator_ClearWindow(windowId);

    StringCopy(gStringVar4, COMPOUND_STRING("どうぐを えらぶ{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("No."));
    ConvertIntToDecimalStringN(gStringVar1, index + 1, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);

    StringAppend(gStringVar4, COMPOUND_STRING(" / "));
    ConvertIntToDecimalStringN(gStringVar1, itemCount, STR_CONV_MODE_LEADING_ZEROS, 3);
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("なまえ: "));
    StringAppend(gStringVar4, gItemsInfo[itemId].name);
    StringAppend(gStringVar4, COMPOUND_STRING("{CLEAR_TO 90}\n"));

    if (CheckBagHasItem(itemId, 1))
        StringAppend(gStringVar4, COMPOUND_STRING("もう もっています{CLEAR_TO 90}\n"));
    else if (!CheckBagHasSpace(itemId, 1))
        StringAppend(gStringVar4, COMPOUND_STRING("バッグが いっぱいです{CLEAR_TO 90}\n"));
    else
        StringAppend(gStringVar4, COMPOUND_STRING("このどうぐを もらえます{CLEAR_TO 90}\n"));

    StringAppend(gStringVar4, COMPOUND_STRING("{UP_ARROW}{DOWN_ARROW}えらぶ {LEFT_ARROW}{RIGHT_ARROW}けた:"));
    ConvertIntToDecimalStringN(
        gStringVar1,
        sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit],
        STR_CONV_MODE_LEFT_ALIGN,
        FRONTIER_ITEM_GIVER_DIGITS
    );
    StringAppend(gStringVar4, gStringVar1);
    StringAppend(gStringVar4, COMPOUND_STRING("\n{A_BUTTON}もらう {B_BUTTON}やめる"));

    FrontierCreator_PrintWindow(windowId);
}

static void FrontierItemGiver_DestroyAndReturn(u8 taskId)
{
    ClearStdWindowAndFrame(gTasks[taskId].tWindowId, TRUE);
    RemoveWindow(gTasks[taskId].tWindowId);
    DestroyTask(taskId);

    ScriptContext_Enable();
    UnfreezeObjectEvents();
    UnlockPlayerFieldControls();
}

static void Task_FrontierItemGiver_SelectItem(u8 taskId)
{
    u16 itemCount = FrontierItemGiver_GetItemCount();
    enum Item itemId;
    s32 index;

    if (itemCount == 0)
    {
        gSpecialVar_Result = FALSE;
        FrontierItemGiver_DestroyAndReturn(taskId);
        return;
    }

    if (JOY_NEW(DPAD_UP))
    {
        PlaySE(SE_SELECT);
        index = gTasks[taskId].tInput - sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        index %= itemCount;
        if (index < 0)
            index += itemCount;
        gTasks[taskId].tInput = index;
        FrontierItemGiver_DrawScreen(taskId);
    }
    else if (JOY_NEW(DPAD_DOWN))
    {
        PlaySE(SE_SELECT);
        index = gTasks[taskId].tInput + sFrontierCreatorPowersOfTen[gTasks[taskId].tDigit];
        gTasks[taskId].tInput = index % itemCount;
        FrontierItemGiver_DrawScreen(taskId);
    }
    else if (JOY_NEW(DPAD_LEFT))
    {
        PlaySE(SE_SELECT);
        if (gTasks[taskId].tDigit > 0)
            gTasks[taskId].tDigit--;
        FrontierItemGiver_DrawScreen(taskId);
    }
    else if (JOY_NEW(DPAD_RIGHT))
    {
        PlaySE(SE_SELECT);
        if (gTasks[taskId].tDigit < FRONTIER_ITEM_GIVER_DIGITS - 1)
            gTasks[taskId].tDigit++;
        FrontierItemGiver_DrawScreen(taskId);
    }

    if (JOY_NEW(A_BUTTON))
    {
        itemId = sFrontierHubGiveItems[gTasks[taskId].tInput];

        if (CheckBagHasItem(itemId, 1))
        {
            PlaySE(SE_PC_OFF);
            FrontierItemGiver_DrawScreen(taskId);
            return;
        }

        if (!CheckBagHasSpace(itemId, 1))
        {
            PlaySE(SE_PC_OFF);
            FrontierItemGiver_DrawScreen(taskId);
            return;
        }

        AddBagItem(itemId, 1);
        PlaySE(SE_SELECT);
        gSpecialVar_Result = TRUE;
        FrontierItemGiver_DrawScreen(taskId);
    }
    else if (JOY_NEW(B_BUTTON))
    {
        PlaySE(SE_SELECT);
        gSpecialVar_Result = FALSE;
        FrontierItemGiver_DestroyAndReturn(taskId);
    }
}

void Special_SetFrontierAiNormal(void)
{
    VarSet(VAR_FRONTIER_AI_LEVEL, 0);
}

void Special_SetFrontierAiHard(void)
{
    VarSet(VAR_FRONTIER_AI_LEVEL, 1);
}

void Special_SetFrontierAiStrongest(void)
{
    VarSet(VAR_FRONTIER_AI_LEVEL, 2);
}

void Special_SetFrontierAllowBannedSpecies(void)
{
    FlagSet(FLAG_FRONTIER_ALLOW_BANNED_SPECIES);
}

void Special_ClearFrontierAllowBannedSpecies(void)
{
    FlagClear(FLAG_FRONTIER_ALLOW_BANNED_SPECIES);
}

void Special_GetFrontierAllowBannedSpecies(void)
{
    gSpecialVar_Result = FlagGet(FLAG_FRONTIER_ALLOW_BANNED_SPECIES);
}

void Special_SetupFrontierHubState(void)
{
    u32 i;
    FlagSet(FLAG_BADGE01_GET);
    FlagSet(FLAG_BADGE02_GET);
    FlagSet(FLAG_BADGE03_GET);
    FlagSet(FLAG_BADGE04_GET);
    FlagSet(FLAG_BADGE05_GET);
    FlagSet(FLAG_BADGE06_GET);
    FlagSet(FLAG_BADGE07_GET);
    FlagSet(FLAG_BADGE08_GET);

    FlagSet(FLAG_SYS_GAME_CLEAR);
    FlagSet(FLAG_SYS_FRONTIER_PASS);
    FlagSet(FLAG_SYS_POKEDEX_GET);
    FlagSet(FLAG_SYS_POKENAV_GET);
    FlagSet(FLAG_SYS_B_DASH);
    FlagSet(FLAG_EXPANSION_DYNAMAX_BATTLE);
    FlagSet(FLAG_EXPANSION_TERA_ORB_CHARGED);
    FlagSet(FLAG_EXPANSION_TERA_ORB_NO_COST);
    EnableNationalPokedex();

    GetSetPokedexFlag(SpeciesToNationalPokedexNum(SPECIES_BULBASAUR), FLAG_SET_SEEN);
    GetSetPokedexFlag(SpeciesToNationalPokedexNum(SPECIES_BULBASAUR), FLAG_SET_CAUGHT);

    for (i = 0; i < ARRAY_COUNT(gBadgeFlags); i++)
        FlagSet(gBadgeFlags[i]);

    FrontierHub_GiveGimmickKeyItems();
    FrontierHub_GiveAllKeyItems();
    FrontierHub_GiveAutoItems();
    FrontierHub_TryGiveInitialParty();
}

static void FrontierHub_TryGiveInitialParty(void)
{
    u32 i;
    bool8 allGiven = TRUE;
    struct Pokemon mon;

    if (FlagGet(FLAG_RECEIVED_ULTRA_FRONTIE_HUB_INITIAL_PARTY))
    {
        gSpecialVar_Result = FALSE;
        return;
    }

    for (i = 0; i < ARRAY_COUNT(sFrontierHubInitialGiftMons); i++)
    {
        FrontierHub_CreateInitialGiftMon(&sFrontierHubInitialGiftMons[i], &mon);
        if (GiveScriptedMonToPlayer(&mon, PARTY_SIZE) == MON_CANT_GIVE)
            allGiven = FALSE;
    }

    if (allGiven)
    {
        FlagSet(FLAG_RECEIVED_ULTRA_FRONTIE_HUB_INITIAL_PARTY);
        FlagSet(FLAG_SYS_POKEMON_GET);
    }

    gSpecialVar_Result = allGiven;
}

static void FrontierHub_CreateInitialGiftMon(const struct FrontierHubInitialGiftMon *gift, struct Pokemon *mon)
{
    u32 i;
    u32 data;
    u32 personality;
    u8 abilityNum;
    enum Item itemId;
    enum Type teraType;
    enum PokeBall ball;

    personality = GetMonPersonality(gift->species, MON_MALE, gift->nature, RANDOM_UNOWN_LETTER);
    CreateMonWithIVs(mon, gift->species, FRONTIER_HUB_INITIAL_GIFT_LEVEL, personality, OTID_STRUCT_PLAYER_ID, FRONTIER_HUB_INITIAL_GIFT_IVS);

    for (i = 0; i < MAX_MON_MOVES; i++)
        SetMonMoveSlot(mon, gift->moves[i], i);

    for (i = 0; i < NUM_STATS; i++)
        SetMonData(mon, MON_DATA_HP_EV + i, &gift->evs[i]);

    abilityNum = FrontierHub_GetAbilityNum(gift->species, gift->ability);
    SetMonData(mon, MON_DATA_ABILITY_NUM, &abilityNum);

    itemId = gift->itemId;
    SetMonData(mon, MON_DATA_HELD_ITEM, &itemId);

    data = FRONTIER_HUB_INITIAL_GIFT_DYNAMAX_LEVEL;
    SetMonData(mon, MON_DATA_DYNAMAX_LEVEL, &data);

    data = gift->gmaxFactor;
    SetMonData(mon, MON_DATA_GIGANTAMAX_FACTOR, &data);

    teraType = gift->teraType;
    SetMonData(mon, MON_DATA_TERA_TYPE, &teraType);

    ball = BALL_POKE;
    SetMonData(mon, MON_DATA_POKEBALL, &ball);

    CalculateMonStats(mon);
}

static u8 FrontierHub_GetAbilityNum(enum Species species, enum Ability ability)
{
    u32 i;

    for (i = 0; i < NUM_ABILITY_SLOTS; i++)
    {
        if (gSpeciesInfo[species].abilities[i] == ability)
            return i;
    }

    return 0;
}

void Special_OpenFrontierItemGiver(void)
{
    u8 taskId;
    u8 windowId;

    if (FrontierItemGiver_GetItemCount() == 0)
    {
        gSpecialVar_Result = FALSE;
        return;
    }

    LockPlayerFieldControls();
    FreezeObjectEvents();
    HideMapNamePopUpWindow();
    LoadMessageBoxAndBorderGfx();

    windowId = AddWindow(&sFrontierCreatorWindowTemplate);
    DrawStdWindowFrame(windowId, FALSE);
    CopyWindowToVram(windowId, COPYWIN_FULL);

    taskId = CreateTask(Task_FrontierItemGiver_SelectItem, 3);
    gTasks[taskId].tWindowId = windowId;
    gTasks[taskId].tInput = 0;
    gTasks[taskId].tDigit = 0;
    gTasks[taskId].tStatId = 0;

    FrontierItemGiver_DrawScreen(taskId);
}

void Special_OpenFrontierPokemonCreator(void)
{
    u8 taskId;
    u8 windowId;

    if (sFrontierCreatorData != NULL)
    {
        gSpecialVar_Result = FALSE;
        return;
    }

    sFrontierCreatorData = AllocZeroed(sizeof(*sFrontierCreatorData));
    if (sFrontierCreatorData == NULL)
    {
        gSpecialVar_Result = FALSE;
        return;
    }

    FrontierCreator_InitDefaultData();
    sFrontierCreatorData->species = FrontierCreator_GetFirstAllowedSpecies();

    LockPlayerFieldControls();
    FreezeObjectEvents();
    HideMapNamePopUpWindow();
    LoadMessageBoxAndBorderGfx();

    windowId = AddWindow(&sFrontierCreatorWindowTemplate);
    DrawStdWindowFrame(windowId, FALSE);
    CopyWindowToVram(windowId, COPYWIN_FULL);

    taskId = CreateTask(Task_FrontierCreator_SelectSpecies, 3);
    gTasks[taskId].tWindowId = windowId;
    gTasks[taskId].tInput = sFrontierCreatorData->species;
    gTasks[taskId].tDigit = 0;
    gTasks[taskId].tStatId = 0;
    gTasks[taskId].tPreviewSpriteId = FRONTIER_CREATOR_PREVIEW_NONE;
    gTasks[taskId].tPreviewSpecies = SPECIES_NONE;

    FrontierCreator_DrawSpeciesScreen(taskId);
    FrontierCreator_UpdateSpeciesPreview(taskId, gTasks[taskId].tInput, FALSE);
}

#undef tWindowId
#undef tInput
#undef tDigit
#undef tStatId
#undef tPreviewSpriteId
#undef tPreviewSpecies
