#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("{JPN}くん");
const u8 gText_ExpandedPlaceholder_Chan[] = _("{JPN}ちゃん");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("{JPN}サファイア");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("{JPN}ルビー");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("{JPN}エメラルド");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("{JPN}アクアだん");
const u8 gText_ExpandedPlaceholder_Magma[] = _("{JPN}マグマだん");
const u8 gText_ExpandedPlaceholder_Archie[] = _("{JPN}アオギリ");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("{JPN}マツブサ");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("{JPN}カイオーガ");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("{JPN}グラードン");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("{JPN}ユウキ");
const u8 gText_ExpandedPlaceholder_May[] = _("{JPN}ハルカ");
const u8 gText_ExpandedPlaceholder_Red[] = _("{JPN}レッド");
const u8 gText_ExpandedPlaceholder_Green[] = _("{JPN}グリーン");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("{JPN}タマゴ");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("{JPN}ポケモン");
const u8 gText_Player[] = _("{JPN}しゅじんこう"); // Unused
const u8 gText_Pokedex[] = _("{JPN}ポケモンずかん"); // Unused
const u8 gText_Time[] = _("{JPN}プレイじかん");
const u8 gText_Badges[] = _("{JPN}もっているバッジ"); // Unused
const u8 gText_AButton[] = _("{JPN}エーボタン"); // Unused
const u8 gText_BButton[] = _("{JPN}ビーボタン"); // Unused
const u8 gText_RButton[] = _("{JPN}アールボタン"); // Unused
const u8 gText_LButton[] = _("{JPN}エルボタン"); // Unused
const u8 gText_Start[] = _("{JPN}スタートボタン"); // Unused
const u8 gText_Select[] = _("{JPN}セレクトボタン"); // Unused
const u8 gText_ControlPad[] = _("{JPN}じゅうじボタン"); // Unused
const u8 gText_LButtonRButton[] = _("{JPN}Lボタン Rボタン"); // Unused
const u8 gText_Controls[] = _("{JPN} そうさ せつめい"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{JPN}{DPAD_UPDOWN}えらぶ {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{JPN}{A_BUTTON}つぎ");
ALIGNED(4) const u8 gText_NextBack[] = _("{JPN}{A_BUTTON}つぎ {B_BUTTON}もどる");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{JPN}{DPAD_UPDOWN}えらぶ {A_BUTTON}つぎ {B_BUTTON}やめる");
ALIGNED(4) const u8 gText_PickCancel[] = _("{JPN}{DPAD_UPDOWN}えらぶ {A_BUTTON}{B_BUTTON}やめる");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{JPN}{A_BUTTON}おわる");
const u8 gText_Boy[] = _("{JPN}おとこ");
const u8 gText_Girl[] = _("{JPN}おんな");
const u8 gText_ThisIsAPokemon[] = _("{JPN}ポケットモンスター\n……すなわち ポケモン{PAUSE 96}$");
const u8 gText_5MarksPokemon[] = _("{JPN}????? ポケモン");
const u8 gText_UnkHeight[] = _("{JPN}{CLEAR_TO 12}??'??");
const u8 gText_UnkHeightMetric[] = _("{JPN}???.? m");
const u8 gText_UnkHeightCentimeters[] = _("{JPN}????? cm");
const u8 gText_UnkWeight[] = _("{JPN}????.? kg");
const u8 gText_UnkWeightMetric[] = _("{JPN}???.? kg");
const u8 gText_EmptyPkmnCategory[] = _("{JPN}                       ポケモン"); // Unused
const u8 gText_EmptyHeight[] = _("{JPN}   ． m");
const u8 gText_EmptyWeight[] = _("{JPN}   ． kg"); // Unused
const u8 gText_EmptyPokedexInfo1 [] = _("{JPN}の"); // Unused
const u8 gText_CryOf[] = _("{JPN}なきごえ");
const u8 gText_EmptyPokedexInfo2[] = _("{JPN}と"); // Unused
const u8 gText_SizeComparedTo[] = _("{JPN}おおきさくらべ");
const u8 gText_PokedexRegistration[] = _("{JPN}ポケモンずかんの とうろく かんりょう!");
const u8 gText_HTHeight[] = _("{JPN}たかさ");
const u8 gText_WTWeight[] = _("{JPN}おもさ");
const u8 gText_SearchingPleaseWait[] = _("{JPN}けんさくを しています……");
const u8 gText_SearchCompleted[] = _("{JPN}けんさくが しゅうりょう しました!");
const u8 gText_NoMatchingPkmnWereFound[] = _("{JPN}がいとう する ポケモンは いませんでした……");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("{JPN}じょうけんを していして\nポケモンの けんさくを します");
const u8 gText_SwitchPokedexListings[] = _("{JPN}ずかんリストの ならびを きりかえます");
const u8 gText_ReturnToPokedex[] = _("{JPN}ずかんに もどります");
const u8 gText_SelectPokedexMode[] = _("{JPN}ずかんモードを してい します");
const u8 gText_SelectPokedexListingMode[] = _("{JPN}ずかんの ならびを してい します");
const u8 gText_ListByFirstLetter[] = _("{JPN}なまえの さいしょの もじを してい します\n /みつけたポケモンのみ");
const u8 gText_ListByBodyColor[] = _("{JPN}からだの いろを してい します\n /みつけたポケモンのみ");
const u8 gText_ListByType[] = _("{JPN}タイプを してい します\n /つかまえたポケモンのみ");
const u8 gText_ExecuteSearchSwitch[] = _("{JPN}けんさく/きりかえを じっこうします");
const u8 gText_DexHoennTitle[] = _("{JPN}ホウエン ずかん");
const u8 gText_DexNatTitle[] = _("{JPN}ぜんこく ずかん");
const u8 gText_DexSortNumericalTitle[] = _("{JPN}ばんごう じゅん");
const u8 gText_DexSortAtoZTitle[] = _("{JPN}ごじゅうおん じゅん");
const u8 gText_DexSortHeaviestTitle[] = _("{JPN}おもい じゅん");
const u8 gText_DexSortLightestTitle[] = _("{JPN}かるい じゅん");
const u8 gText_DexSortTallestTitle[] = _("{JPN}たかい じゅん");
const u8 gText_DexSortSmallestTitle[] = _("{JPN}ひくい じゅん");
const u8 gText_DexSearchAlphaABC[] = _("{JPN}あいうえお");
const u8 gText_DexSearchAlphaDEF[] = _("{JPN}かきくけこ");
const u8 gText_DexSearchAlphaGHI[] = _("{JPN}さしすせそ");
const u8 gText_DexSearchAlphaJKL[] = _("{JPN}たちつてと");
const u8 gText_DexSearchAlphaMNO[] = _("{JPN}なにぬねの");
const u8 gText_DexSearchAlphaPQR[] = _("{JPN}はひふへほ");
const u8 gText_DexSearchAlphaSTU[] = _("{JPN}まみむめも");
const u8 gText_DexSearchAlphaVWX[] = _("{JPN}らりるれろ");
const u8 gText_DexSearchAlphaYZ[] = _("{JPN}やゆよわをん");
const u8 gText_DexSearchColorRed[] = _("{JPN}あか");
const u8 gText_DexSearchColorBlue[] = _("{JPN}あお");
const u8 gText_DexSearchColorYellow[] = _("{JPN}きいろ");
const u8 gText_DexSearchColorGreen[] = _("{JPN}みどり");
const u8 gText_DexSearchColorBlack[] = _("{JPN}くろ");
const u8 gText_DexSearchColorBrown[] = _("{JPN}ちゃいろ");
const u8 gText_DexSearchColorPurple[] = _("{JPN}むらさき");
const u8 gText_DexSearchColorGray[] = _("{JPN}はいいろ");
const u8 gText_DexSearchColorWhite[] = _("{JPN}しろ");
const u8 gText_DexSearchColorPink[] = _("{JPN}ピンク");
const u8 gText_DexHoennDescription[] = _("{JPN}ホウエンちほう ばん ポケモンずかん");
const u8 gText_DexNatDescription[] = _("{JPN}ぜんこく ばん ポケモンずかん");
const u8 gText_DexSortNumericalDescription[] = _("{JPN}ポケモンを\nばんごうじゅんで ひょうじ します");
const u8 gText_DexSortAtoZDescription[] = _("{JPN}みつけたポケモンの なまえを\nごじゅうおんじゅんで ひょうじ します");
const u8 gText_DexSortHeaviestDescription[] = _("{JPN}つかまえたポケモンを\nおもい じゅんばんで ひょうじ します");
const u8 gText_DexSortLightestDescription[] = _("{JPN}つかまえたポケモンを\nかるい じゅんばんで ひょうじ します");
const u8 gText_DexSortTallestDescription[] = _("{JPN}つかまえたポケモンを\nしんちょうのたかい じゅんばんで ひょうじ します");
const u8 gText_DexSortSmallestDescription[] = _("{JPN}つかまえたポケモンを\nしんちょうのひくい じゅんばんで ひょうじ します");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("{JPN}してい しない");
const u8 gText_DexSearchTypeNone[] = _("{JPN}なし");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(""); // Unused
const u8 gText_WelcomeToHOF[] = _("{JPN}でんどういり おめでとう!");
const u8 gText_HOFDexRating[] = _("{JPN}みつけた ポケモン {STR_VAR_1}!\nつかまえた ポケモン {STR_VAR_2}!\p\nオダマキはかせの\nポケモンずかん ひょうか!\pオダマキどれどれ\p\n");
const u8 gText_HOFDexSaving[] = _("{JPN}ここまでの レポートを かきしるしています!\nでんげんを きらないでください");
const u8 gText_HOFCorrupted[] = _("{JPN}でんどういりの きろくが こわれています!");
const u8 gText_HOFNumber[] = _("{JPN}{STR_VAR_1}かい でんどういり!");
const u8 gText_LeagueChamp[] = _("{JPN}リーグ チャンピオン! おめでとう!");
const u8 gText_Number[] = _("{JPN}No. ");
const u8 gText_Level[] = _("{JPN}Lv. ");
const u8 gText_IdNumberSlash[] = _("{JPN}IDNo. /"); // Unused
const u8 gText_Name[] = _("{JPN}なまえ");
const u8 gText_IDNumber[] = _("{JPN}IDNo.");
const u8 gText_BirchInTrouble[] = _("{JPN}オダマキはかせが ピンチだ!\nポケモンを だして たすけてあげよう!");
const u8 gText_ConfirmStarterChoice[] = _("{JPN}このポケモンにしますか?");
const u8 gText_Pokemon4[] = _("{JPN}ポケモン"); // Unused
const u8 gText_FlyToWhere[] = _("{JPN}どこへ とびますか?");
const u8 gMenuText_Use[] = _("{JPN}つかう");
const u8 gMenuText_Toss[] = _("{JPN}すてる");
const u8 gMenuText_Register[] = _("{JPN}とうろく");
const u8 gMenuText_Give[] = _("{JPN}もたせる");
const u8 gMenuText_Confirm[] = _("{JPN}けってい");
const u8 gText_Cancel[] = _("{JPN}もどる");
const u8 gText_Cancel2[] = _("{JPN}やめる");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("{JPN}なし");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{ENG}{LV}{AUTO}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("{JPN}まえに もどります!");
const u8 gText_WhatWouldYouLike[] = _("{JPN}なにを しますか?");
const u8 gMenuText_Give2[] = _("{JPN}あげる");
const u8 gText_xVar1[] = _("{JPN}×{STR_VAR_1}");
const u8 gText_Berry2[] = _("{JPN}のみ"); // Unused
const u8 gText_Coins[] = _("{JPN}{STR_VAR_1}まい");
const u8 gText_CloseBag[] = _("{JPN}バッグをとじる");
const u8 gText_Var1IsSelected[] = _("{JPN}{STR_VAR_1}を\nどうしますか?");
const u8 gText_CantWriteMail[] = _("{JPN}ここで メールを\nかくことは できません!");
const u8 gText_NoPokemon[] = _("{JPN}ポケモンが いませんよ!");
const u8 gText_MoveVar1Where[] = _("{JPN}{STR_VAR_1}を\nどこに いれますか?");
const u8 gText_Var1CantBeHeld[] = _("{JPN}{STR_VAR_1}を\nもたせることは できません!");
const u8 gText_TossHowManyVar1s[] = _("{JPN}{STR_VAR_1}を\nいくつ すてますか?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{JPN}{STR_VAR_1}を\n{STR_VAR_2}コ すてました");
const u8 gText_ConfirmTossItems[] = _("{JPN}{STR_VAR_1}を\n{STR_VAR_2}コ すてても\nよろしいですか?");
const u8 gText_DadsAdvice[] = _("{JPN}おとうさんの ことば……\n{PLAYER}! こういうものには\lつかいどきが あるんだ!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{JPN}{PLAYER}は\n{STR_VAR_2}を つかった!{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("{JPN}まだ まえに つかった スプレーの\nこうかが のこってます!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("{JPN}まだ まえに つかった コロンの\nこうかが のこってます!{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("{JPN}ボックスが いっぱい です{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("{JPN}フィールド");
const u8 gText_TheBattle[] = _("{JPN}せんとう");
const u8 gText_ThePokemonList[] = _("{JPN}ポケモンリスト");
const u8 gText_TheShop[] = _("{JPN}ショップ");
const u8 gText_ThePC[] = _("{JPN}パソコン");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("{JPN}{STR_VAR_1}へ\nもどります");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING("{JPN} ど う ぐ  "),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("{JPN}モンスターボール"),
    [POCKET_TM_HM]      = COMPOUND_STRING("{JPN} わざマシン  "),
    [POCKET_BERRIES]    = COMPOUND_STRING("{JPN} き の み  "),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("{JPN}たいせつなもの ")
};

const u8 gText_NumberItem_TMBerry[] = _("{JPN}{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{JPN}{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("{JPN}かいに きた");
const u8 gText_ShopSell[] = _("{JPN}うりに きた");
const u8 gText_ShopQuit[] = _("{JPN}なんでもないです");
const u8 gText_ThatItemIsSoldOut[] = _("{JPN}すみません それは うりきれです。{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("{JPN}うりきれ");
const u8 gText_InBagVar1[] = _("{JPN}もってるかず {STR_VAR_1}コ");
const u8 gText_QuitShopping[] = _("{JPN}かいもの を やめます");
const u8 gText_Var1CertainlyHowMany[] = _("{JPN}{STR_VAR_1} を\nいくつ おかいあげに なりますか?");
const u8 gText_Var1CertainlyHowMany2[] = _("{JPN}{STR_VAR_1} {STR_VAR_2} を\nいくつ おかいあげに なりますか?");
const u8 gText_Var1AndYouWantedVar2[] = _("{JPN}{STR_VAR_1}を {STR_VAR_2}コで\n{STR_VAR_3}円 おかいあげですか?");
const u8 gText_Var1IsItThatllBeVar2[] = _("{JPN}{STR_VAR_1} だね!\n{STR_VAR_2}円 だけど かうかい?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("{JPN}{STR_VAR_1} ですね!\n{STR_VAR_2}円 だけど かいますか?");
const u8 gText_HereYouGoThankYou[] = _("{JPN}はい まいど!\nありがとう ございます");
const u8 gText_ThankYouIllSendItHome[] = _("{JPN}どうも ありがとう!\nじたくの パソコンに おくって おきますね!");
const u8 gText_ThanksIllSendItHome[] = _("{JPN}どうも ありがとう!\nじたくの パソコンに おくって おくね!");
const u8 gText_YouDontHaveMoney[] = _("{JPN}おかねが たりないですよ!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("{JPN}それ いじょう\nもちきれない ですよ!{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("{JPN}{STR_VAR_1} を\nいれる ばしょが いっぱいです{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("{JPN}その ほかに わたしどもで\nなにか おちからに なれることは?");
const u8 gText_CanIHelpWithAnythingElse [] = _("{JPN}その ほかに\nなにか ちからに なれることは?");
const u8 gText_ThrowInPremierBall[] = _("{JPN}プレミアボール 1コ\nおまけ しておきますね!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("{JPN}プレミアボール {STR_VAR_1}コ\nおまけ しておきますね!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{JPN}{STR_VAR_2}を\nかいとるわけには いきません!{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{JPN}{STR_VAR_2}を\nいくつ うりますか?");
const u8 gText_ICanPayVar1[] = _("{JPN}{STR_VAR_1}円で ひきとらせて いただきます\nよろしいですか?");
const u8 gText_TurnedOverVar1ForVar2[] = _("{JPN}{STR_VAR_2} を わたして\n{STR_VAR_1}円 うけとった!");
const u8 gText_PokedollarVar1[] = _("{JPN}{STR_VAR_1}円");
const u8 gText_HP3[] = _("{JPN}たいりょく");
const u8 gText_SpAtk3[] = _("{JPN}とくこう");
const u8 gText_SpDef3[] = _("{JPN}とくぼう");
const u8 gText_WontHaveEffect[] = _("{JPN}つかっても こうかがないよ{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("{JPN}Choose ポケモン to fuse with.");
const u8 gText_CantBeUsedOnPkmn[] = _("{JPN}そのポケモンには\nつかえません{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{JPN}{STR_VAR_1}を もどすことが\nできない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{JPN}{STR_VAR_1}は すでに\nせんとうに でています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{JPN}{STR_VAR_1}は すでに\nせんたく されています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{JPN}{STR_VAR_1}は たたかうための\nげんきが のこっていません!!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("{JPN}{STR_VAR_1}の ポケモンは じぶんの\nポケモンと いれかえることは できません!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("{JPN}タマゴを\nせんとうに だすことは できません!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("{JPN}あたらしい バッジを てにするまで\nまだ つかえません{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("{JPN}さんか できる ポケモンは\n{STR_VAR_1}ひき まで です!{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("{JPN}とった メールを パソコンに\nてんそうしますか?");
const u8 gText_MailSentToPC[] = _("{JPN}メールを パソコンに\nてんそうしました{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("{JPN}パソコンの メールボックスが\nいっぱいです!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("{JPN}メールを とると メッセージが\nきえてしまいますが よろしいですか?");
const u8 gText_RemoveMailBeforeItem[] = _("{JPN}メールを はずさないと\nどうぐは もてません!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{JPN}{STR_VAR_1}に\n{STR_VAR_2}を もたせた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{JPN}{STR_VAR_1}は すでに\n{STR_VAR_2}を もっています\pもっている どうぐを\nとりかえますか?");
const u8 gText_PkmnNotHolding[] = _("{JPN}{STR_VAR_1}は なにも\nどうぐを もって いません!{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{JPN}{STR_VAR_1}から\n{STR_VAR_2}を あずかりました{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("{JPN}ポケモンから メールを\nとりました!{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{JPN}{STR_VAR_2}を あずかって\nあらたに {STR_VAR_1}を もたせました!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("{JPN}すでに どうぐを もっているので\nメールを もたせることが できません{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("{JPN}ボックスから メールを うつしました{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("{JPN}バッグが いっぱいで\nポケモンの どうぐを うけとれません!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{JPN}{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえた!");
const u8 gText_PkmnLearnedMove4[] = _("{JPN}{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{JPN}{STR_VAR_1}と {STR_VAR_2}は\nあいしょうが わるかった!\p{STR_VAR_2}は おぼえられない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{JPN}{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえたい……!\pしかし {STR_VAR_1}は わざを 4つ\nおぼえるので せいいっぱいだ!\p{STR_VAR_2}の かわりに\nほかの わざを わすれさせますか?");
const u8 gText_StopLearningMove2[] = _("{JPN}それでは…… {STR_VAR_2}を\nおぼえるのを あきらめますか?");
const u8 gText_MoveNotLearned[] = _("{JPN}{STR_VAR_1}は {STR_VAR_2}を\nおぼえずに おわった!{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("{JPN}どの わざを\nわすれさせたい?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("{JPN}1 {PAUSE 15}2の {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン!\p{STR_VAR_1}は {STR_VAR_2}の\nつかいかたを きれいに わすれた!\pそして……!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{JPN}{STR_VAR_1}は すでに\n{STR_VAR_2}を おぼえています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{JPN}{STR_VAR_1}の たいりょくが\nby {STR_VAR_2} かいふくした{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{JPN}{STR_VAR_1}の どくは\nきれい さっぱり なくなった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{JPN}{STR_VAR_1}の からだの\nしびれが とれた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{JPN}{STR_VAR_1}は\nめを さました{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{JPN}{STR_VAR_1}の\nやけどが なおった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{JPN}{STR_VAR_1}の からだの\nしもやけが なおった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{JPN}{STR_VAR_1}の からだの\nこおりが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("{JPN}わざポイントが\nかいふくした!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{JPN}{STR_VAR_1}は\nげんきを とりもどした!{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{JPN}{STR_VAR_1}は\nけんこうになった!{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{JPN}{STR_VAR_1}の\nわざポイントが ふえた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{JPN}{STR_VAR_1}の\nレベルが {STR_VAR_2}になった!");
const u8 gText_PkmnGainedExp[] = _("{JPN}{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{JPN}{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらい\nレベル {STR_VAR_3}に あがった!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{JPN}{STR_VAR_1}の {STR_VAR_2}の\nきそ ポイントが あがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{JPN}{STR_VAR_1}が ちょっと なついた!\n{STR_VAR_2}の きそポイントが さがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{JPN}{STR_VAR_1}は さいこうに なついている!\n{STR_VAR_2}の きそポイントが さがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{JPN}{STR_VAR_1}は ちょっと なついた\n{STR_VAR_2}の きそポイントは もうさがらない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{JPN}{STR_VAR_1}の\nこんらんが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{JPN}{STR_VAR_1}の\nメロメロが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{JPN}{STR_VAR_1}は へんしんした！{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{JPN}{STR_VAR_1}を\nすてても よろしいですか");
const u8 gText_ItemThrownAway[] = _("{JPN}{STR_VAR_1}を\nすてました{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("{JPN}どのポケモンに おぼえさせますか?"); // Unused
const u8 gText_ChoosePokemon[] = _("{JPN}ポケモンを えらんで ください");
const u8 gText_MoveToWhere[] = _("{JPN}どこに いどうしますか?");
const u8 gText_TeachWhichPokemon[] = _("{JPN}どのポケモンに おしえますか?");
const u8 gText_UseOnWhichPokemon[] = _("{JPN}どのポケモンに つかいますか?");
const u8 gText_GiveToWhichPokemon[] = _("{JPN}どのポケモンに もたせますか?");
const u8 gText_DoWhatWithPokemon[] = _("{JPN}{STR_VAR_1}を どうする?");
const u8 gText_NothingToCut[] = _("{JPN}きれるものが ありません!");
const u8 gText_CantSurfHere[] = _("{JPN}ここでは のれません");
const u8 gText_AlreadySurfing[] = _("{JPN}すでに なみのり しています");
const u8 gText_CantUseHere[] = _("{JPN}ここでは つかえません");
const u8 gText_RestoreWhichMove[] = _("{JPN}どれを かいふくする?");
const u8 gText_BoostPP[] = _("{JPN}どれを ふやす?");
const u8 gText_DoWhatWithItem[] = _("{JPN}もちものを どうしますか?");
const u8 gText_NoPokemonForBattle[] = _("{JPN}これでは たたかえません!");
const u8 gText_ChoosePokemon2[] = _("{JPN}どのポケモンを あずけますか?");
const u8 gText_NotEnoughHp[] = _("{JPN}たいりょくが たりません……");
const u8 gText_PokemonAreNeeded[] = _("{JPN}{STR_VAR_1}ひき そろっていません");
const u8 gText_PokemonCantBeSame[] = _("{JPN}おなじ ポケモンが います!");
const u8 gText_NoIdenticalHoldItems[] = _("{JPN}おなじ どうぐを もってます");
const u8 gText_CurrentIsTooFast[] = _("{JPN}ながれが はやくて ダメだ!");
const u8 gText_DoWhatWithMail[] = _("{JPN}メールを どうしますか?");
const u8 gText_ChoosePokemonCancel[] = _("{JPN}ポケモンか もどるを せんたく");
const u8 gText_ChoosePokemonConfirm[] = _("{JPN}ポケモンを えらんで けってい!");
const u8 gText_SendWhichMonToPC[] = _("{JPN}どの ポケモンを PCへ おくりますか？");
const u8 gText_MoveItemWhere[] = _("{JPN}どうぐを どこへ うごかしますか？");
const u8 gText_XsYAnd[] = _("{JPN}{STR_VAR_1}の {STR_VAR_2}と\n");
const u8 gText_XsYWereSwapped[] = _("{JPN}{STR_VAR_1}の {STR_VAR_2}を いれかえた！{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("{JPN}サイクリングを たのしもう!");
const u8 gText_InUseAlready_PM[] = _("{JPN}すでに つかっています!");
const u8 gText_AlreadyHoldingOne[] = _("{JPN}{STR_VAR_1}は\n{STR_VAR_2}を もっています");
const u8 gText_WhichAppliance[] = _("{JPN}どの かでんを\nちゅうもん しますか?");
const u8 gText_NoUse[] = _("{JPN}つかえません");
const u8 gText_Able[] = _("{JPN}さんかしない");
const u8 gText_First_PM[] = _("{JPN}いちばんめ");
const u8 gText_Second_PM[] = _("{JPN}にばんめ");
const u8 gText_Third_PM[] = _("{JPN}さんばんめ");
const u8 gText_Able2[] = _("{JPN}でられます");
const u8 gText_NotAble[] = _("{JPN}でられません");
const u8 gText_Able3[] = _("{JPN}おぼえられる!");
const u8 gText_NotAble2[] = _("{JPN}おぼえられない");
const u8 gText_Learned[] = _("{JPN}もうおぼえてる");
const u8 gText_Have[] = _("{JPN}もっている");
const u8 gText_DontHave[] = _("{JPN}もっていない");
const u8 gText_Fourth[] = _("{JPN}よんばんめ");
const u8 gText_PkmnCantParticipate[] = _("{JPN}その ポケモンは さんか できません{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("{JPN}さんかを やめますか?");
const u8 gText_CancelBattle[] = _("{JPN}たいせんを やめますか?");
const u8 gText_ReturnToWaitingRoom[] = _("{JPN}ひかえしつに もどりますか?");
const u8 gText_CancelChallenge[] = _("{JPN}ちょうせんを やめますか?");
const u8 gText_EscapeFromHere[] = _("{JPN}ここを だっしゅつ して\n{STR_VAR_1}に もどる?");
const u8 gText_ReturnToHealingSpot[] = _("{JPN}さいごに やすんだ\n{STR_VAR_1}に テレポートする?");
const u8 gText_PauseUntilPress[] = _("{JPN}{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{JPN}{STR_VAR_1}{JPN}を ぐるぐるこうかんに\nだして よろしいですか?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("{JPN}そのポケモンを こうかんすると\nせんとうできなくなっちゃうよ!");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("{JPN}その ポケモンは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("{JPN}その ポケモンは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("{JPN}タマゴは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("{JPN}あいての ポケモンとは\nいまは こうかん できません");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("{JPN}いまは そのポケモンを \nあいては うけとることが できません");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("{JPN}その あいてとは いまは\nこうかん できません");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("{JPN}あいての ほしがっている タイプの\nポケモンでは ありません");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("{JPN}それは タマゴでは ありません");
const u8 gText_Register[] = _("{JPN}とうろくする");
const u8 gText_Attack3[] = _("{JPN}こうげき");
const u8 gText_Defense3[] = _("{JPN}ぼうぎょ");
const u8 gText_SpAtk4[] = _("{JPN}とくこう");
const u8 gText_SpDef4[] = _("{JPN}とくぼう");
const u8 gText_Speed2[] = _("{JPN}すばやさ");
const u8 gText_HP4[] = _("{JPN}HP");
const u8 gText_EmptyString8[] = _("{JPN}あと"); // Unused
const u8 gText_OTSlash[] = _("{JPN}おや/");
const u8 gText_RentalPkmn[] = _("{JPN}レンタルポケモン");
const u8 gText_TypeSlash[] = _("{JPN}タイプ/");
const u8 gText_Power[] = _("{JPN}いりょく");
const u8 gText_Accuracy2[] = _("{JPN}めいちゅう");
const u8 gText_Appeal[] = _("{JPN}アピール");
const u8 gText_Jam[] = _("{JPN}ぼうがい");
const u8 gText_Status[] = _("{JPN}じょうたい");
const u8 gText_ExpPoints[] = _("{JPN}げんざいのけいけんち");
const u8 gText_NextLv[] = _("{JPN}レベルアップまで");
const u8 gText_RibbonsVar1[] = _("{JPN}げんざい {STR_VAR_1}コ");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("{JPN}イベント"); // Unused
const u8 gText_Switch[] = _("{JPN}いれかえ");
const u8 gText_PkmnInfo[] = _("{JPN}ポケモンじょうほう");
const u8 gText_PkmnSkills[] = _("{JPN}ポケモンのうりょく");
const u8 gText_BattleMoves[] = _("{JPN}たたかうわざ");
const u8 gText_ContestMoves[] = _("{JPN}コンテストわざ");
const u8 gText_Info[] = _("{JPN}きりかえ");
const u8 gText_EggWillTakeALongTime[] = _("{JPN}この タマゴは\nうまれるまで かなり かかりそう");
const u8 gText_EggWillTakeSomeTime[] = _("{JPN}なにが うまれて くるのかな?\nうまれる まで まだまだ かかりそう");
const u8 gText_EggWillHatchSoon[] = _("{JPN}ときどき うごいて いるようだ\nうまれる まで もうちょっと かな?");
const u8 gText_EggAboutToHatch[] = _("{JPN}なかから おとが きこえてくる\nもうすぐ うまれそう!");
const u8 gText_HMMovesCantBeForgotten2[] = _("{JPN}それは たいせつなわざです\nわすれさせることは できません!");
const u8 gText_XNatureMetAtYZ[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であった");
const u8 gText_XNatureHatchedAtYZ[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で かえった");
const u8 gText_XNatureObtainedInTrade[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \nつうしんこうかんに よって であった");
const u8 gText_XNatureFatefulEncounter[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nうんめいてきな であいを した");
const u8 gText_XNatureProbablyMetAt[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であったようだ");
const u8 gText_XNature[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく");
const u8 gText_XNatureMetSomewhereAt[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで であった");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{JPN}{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで かえった");
const u8 gText_OddEggFoundByCouple[] = _("{JPN}そだてや ふうふ から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_PeculiarEggNicePlace[] = _("{JPN}ステキな ばしょで てにいれた\nふしぎな ふしぎな ポケモンのタマゴ");
const u8 gText_PeculiarEggTrade[] = _("{JPN}つうしんこうかんで てにいれた\nふしぎな ポケモンのタマゴ");
const u8 gText_EggFromHotSprings[] = _("{JPN}おんせんばあさん から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_EggFromTraveler[] = _("{JPN}たびの おじさん から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_ApostropheSBase[] = _("{JPN} きち");
const u8 gText_OkayToDeleteFromRegistry[] = _("{JPN}{STR_VAR_1} の とうろくを\nかいじょ しても よろしい ですか?");
const u8 gText_RegisteredDataDeleted[] = _("{JPN}とうろくを かいじょ しました{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("{JPN}とうろく リストは ありません{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("{JPN}とうろく かいじょ");
const u8 gText_Var3Var1SlashVar2[] = _("{JPN}{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("{JPN}グッズを おく");
const u8 gText_PutAway[] = _("{JPN}グッズを もどす");
const u8 gText_Toss2[] = _("{JPN}グッズを すてる");
const u8 gText_Color161Shadow161[] = _("{JPN}{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("{JPN}えらんだ グッズを へやに おきます!");
const u8 gText_StoreChosenDecorInPC[] = _("{JPN}えらんだ グッズを パソコンに もどします!");
const u8 gText_ThrowAwayUnwantedDecors[] = _("{JPN}いらなくなった グッズを すてます!");
const u8 gText_NoDecorations[] = _("{JPN}グッズは ありません!{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("{JPN}つくえ");
const u8 gText_Chair[] = _("{JPN}いす");
const u8 gText_Plant[] = _("{JPN}うえき");
const u8 gText_Ornament[] = _("{JPN}おきもの");
const u8 gText_Mat[] = _("{JPN}マット");
const u8 gText_Poster[] = _("{JPN}ポスター");
const u8 gText_Doll[] = _("{JPN}ぬいぐるみ");
const u8 gText_Cushion[] = _("{JPN}クッション");
const u8 gText_Gold[] = _("{JPN}きん");
const u8 gText_Silver[] = _("{JPN}ぎん");
const u8 gText_PlaceItHere[] = _("{JPN}ここに おきますか?");
const u8 gText_CantBePlacedHere[] = _("{JPN}ここには おけません!");
const u8 gText_CancelDecorating[] = _("{JPN}おくのを やめますか?");
const u8 gText_InUseAlready[] = _("{JPN}すでに おかれて います!");
const u8 gText_NoMoreDecorations[] = _("{JPN}これいじょう おけません\nひみつきちに おけるのは {STR_VAR_1}こ までです");
const u8 gText_NoMoreDecorations2[] = _("{JPN}これいじょう おけません\nへやに おけるのは {STR_VAR_1}こ までです");
const u8 gText_MustBePlacedOnDesk[] = _("{JPN}ここには おけません!\nつくえの うえなどに おいてください!"); // Unused
const u8 gText_CantPlaceInRoom[] = _("{JPN}この グッズは\nじぶんの へやには おけません!");
const u8 gText_CantThrowAwayInUse[] = _("{JPN}このグッズは おかれて いるので\nすてる ことが できません!");
const u8 gText_DecorationWillBeDiscarded[] = _("{JPN}{STR_VAR_1} は なくなりますが\nよろしい ですか?");
const u8 gText_DecorationThrownAway[] = _("{JPN}グッズを すてました!");
const u8 gText_StopPuttingAwayDecorations[] = _("{JPN}もどすのを やめますか?");
const u8 gText_NoDecorationHere[] = _("{JPN}ここに グッズは ありません!");
const u8 gText_ReturnDecorationToPC[] = _("{JPN}このグッズを パソコンに もどしますか?");
const u8 gText_DecorationReturnedToPC[] = _("{JPN}グッズを パソコンに もどしました!");
const u8 gText_NoDecorationsInUse[] = _("{JPN}グッズは おかれて いません!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("{JPN}なにも ありません!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("{JPN}メールは 1つうも ありません{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("{JPN}{STR_VAR_1} の\nメールを どうしますか?");
const u8 gText_MessageWillBeLost[] = _("{JPN}ないようは きえてしまいますが\nよろしいですか?");
const u8 gText_BagIsFull[] = _("{JPN}バッグが いっぱいです!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("{JPN}ないようを けした メールを\nバッグに いれました{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("{JPN}パパ");
const u8 gText_Mom[] = _("{JPN}ママ");
const u8 gText_CoolnessContest[] = _("{JPN}かっこよさ コンテスト");
const u8 gText_BeautyContest[] = _("{JPN}うつくしさ コンテスト");
const u8 gText_CutenessContest[] = _("{JPN}かわいさ コンテスト");
const u8 gText_SmartnessContest[] = _("{JPN}かしこさ コンテスト");
const u8 gText_ToughnessContest[] = _("{JPN}たくましさ コンテスト");
const u8 gText_Information[] = _("{JPN}おしらせ");
const u8 gText_Yes[] = _("{JPN}はい");
const u8 gText_No[] = _("{JPN}いいえ");
const u8 gText_Lv50[] = _("{JPN}レベル50");
const u8 gText_OpenLevel[] = _("{JPN}オープンレベル");
const u8 gText_BattleFrontier[] = _("{JPN}バトルフロンティア");
const u8 gText_Cool[] = _("{JPN}かっこよさ");
const u8 gText_Beauty[] = _("{JPN}うつくしさ");
const u8 gText_Cute[] = _("{JPN}かわいさ");
const u8 gText_Smart[] = _("{JPN}かしこさ");
const u8 gText_Tough[] = _("{JPN}たくましさ");
const u8 gText_Normal[] = _("{JPN}ノーマル");
const u8 gText_Super[] = _("{JPN}スーパー");
const u8 gText_Hyper[] = _("{JPN}ハイパー");
const u8 gText_Master[] = _("{JPN}マスター");
const u8 gText_SomeonesPC[] = _("{JPN}だれかのパソコン");
const u8 gText_LanettesPC[] = _("{JPN}マユミのパソコン");
const u8 gText_BillsPc[] = _("{JPN}マサキのパソコン");
const u8 gText_PlayersPC[] = _("{JPN}{PLAYER}のパソコン");
const u8 gText_HallOfFame[] = _("{JPN}でんどういり");
const u8 gText_LogOff[] = _("{JPN}スイッチをきる");
const u8 gText_Single2[] = _("{JPN}シングル");
const u8 gText_Double2[] = _("{JPN}ダブル");
const u8 gText_Multi[] = _("{JPN}マルチ");
const u8 gText_MultiLink[] = _("{JPN}つうしん マルチ");
const u8 gText_MenuOptionPokedex[] = _("{JPN}ずかん");
const u8 gText_MenuOptionPokemon[] = _("{JPN}ポケモン");
const u8 gText_MenuOptionBag[] = _("{JPN}バッグ");
const u8 gText_MenuOptionPokenav[] = _("{JPN}ポケナビ");
const u8 gText_MenuOptionSave[] = _("{JPN}レポート");
const u8 gText_MenuOptionOption[] = _("{JPN}せってい");
const u8 gText_MenuOptionExit[] = _("{JPN}とじる");
const u8 gText_SouthernIsland[] = _("{JPN}みなみのことう");
const u8 gText_BirthIsland[] = _("{JPN}たんじょうのしま");
const u8 gText_FarawayIsland[] = _("{JPN}さいはてのことう");
const u8 gText_NavelRock[] = _("{JPN}へそのいわ");
const u8 gText_NormalTagMatch[] = _("{JPN}ふつうタッグ");
const u8 gText_VarietyTagMatch[] = _("{JPN}いろいろタッグ");
const u8 gText_UniqueTagMatch[] = _("{JPN}ユニークタッグ");
const u8 gText_ExpertTagMatch[] = _("{JPN}エキスパートタッグ");
const u8 gText_BattleBasics[] = _("{JPN}たたかいの きほん");
const u8 gText_PokemonNature[] = _("{JPN}ポケモンのせいかく");
const u8 gText_PokemonMoves[] = _("{JPN}ポケモンのわざ");
const u8 gText_Underpowered[] = _("{JPN}ちからをはっきできない");
const u8 gText_WhenInDanger[] = _("{JPN}ピンチになったら");
const u8 gText_BattlePokemon[] = _("{JPN}でてくるポケモン");
const u8 gText_BattleTrainers[] = _("{JPN}たたかう トレーナー");
const u8 gText_1F[] = _("{JPN}1かい");
const u8 gText_2F[] = _("{JPN}2かい");
const u8 gText_3F[] = _("{JPN}3かい");
const u8 gText_4F[] = _("{JPN}4かい");
const u8 gText_5F[] = _("{JPN}5かい");
const u8 gText_6F[] = _("{JPN}6かい");
const u8 gText_7F[] = _("{JPN}7かい");
const u8 gText_8F[] = _("{JPN}8かい");
const u8 gText_9F[] = _("{JPN}9かい");
const u8 gText_10F[] = _("{JPN}10かい");
const u8 gText_11F[] = _("{JPN}11かい");
const u8 gText_B1F[] = _("{JPN}ちか1かい");
const u8 gText_B2F[] = _("{JPN}ちか2かい");
const u8 gText_B3F[] = _("{JPN}ちか3かい");
const u8 gText_B4F[] = _("{JPN}ちか4かい");
const u8 gText_Rooftop[] = _("{JPN}おくじょう");
const u8 gText_ElevatorNowOn[] = _("{JPN}げんざいのフロア");
const u8 gText_BP[] = _("{JPN}BP");
const u8 gText_RankingHall[] = _("{JPN}ランキングホール");
const u8 gText_ExchangeService[] = _("{JPN}ひきかえサービス");
const u8 gText_SlateportCity[] = _("{JPN}カイナシティ");
const u8 gText_Exit[] = _("{JPN}やめる");
const u8 gText_YourPartysFull[] = _("{JPN}てもちが いっぱいです！{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("{JPN}てもち");
const u8 gText_PokemonMaleLv[] = _("{JPN}{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{JPN}{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{JPN}{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{JPN}{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{JPN}{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{JPN}{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("{JPN}4つの ことばを くみあわせて");
const u8 gText_AndMakeYourProfile[] = _("{JPN}プロフィールを つくろう!");
const u8 gText_CombineSixWordsOrPhrases[] = _("{JPN}6つの ことばで");
const u8 gText_AndMakeAMessage[] = _("{JPN}メッセージを つくろう!");
const u8 gText_FindWordsThatDescribeYour[] = _("{JPN}いまの きもちに ぴったりあう");
const u8 gText_FeelingsRightNow[] = _("{JPN}ことばを みつけよう!");
const u8 gText_WithFourPhrases[] = _("{JPN}4つの ことばで"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("{JPN}9つの ことばを くみあわせて");
const u8 gText_AndMakeAMessage2[] = _("{JPN}メッセージを つくろう!");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("{JPN}ことばを 1つだけ いれかえて");
const u8 gText_AndImproveTheBardsSong[] = _("{JPN}オヤジのうたを よくして あげよう!");
const u8 gText_YourProfile[] = _("{JPN}プロフィールは");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("{JPN}たいせんが はじまるときの きもちは");
const u8 gText_WhatYouSayIfYouWin[] = _("{JPN}たいせんに かったときの あいさつは");
const u8 gText_WhatYouSayIfYouLose[] = _("{JPN}たいせんに まけたときの あいさつは");
const u8 gText_TheAnswer[] = _("{JPN}こたえは");
const u8 gText_TheMailMessage[] = _("{JPN}メールに のせる メッセージは");
const u8 gText_TheMailSalutation[] = _("{JPN}はがきに のせる あいさつは"); // Unused
const u8 gText_TheBardsSong2[] = _("{JPN}あたらしい うたは");
const u8 gText_CombineTwoWordsOrPhrases[] = _("{JPN}2つの ことばを くみあわせて");
const u8 gText_AndMakeATrendySaying[] = _("{JPN}はやらせたい ことばを つくろう!");
const u8 gText_TheTrendySaying[] = _("{JPN}はやらせたい ことばは");
const u8 gText_IsAsShownOkay[] = _("{JPN}これで いいですか?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("{JPN}2つの ことばを くみあわせて");
const u8 gText_ToTeachHerAGoodSaying[] = _("{JPN}いい ことばを おしえてあげよう!");
const u8 gText_FindWordsWhichFit[] = _("{JPN}トレーナーの イメージに");
const u8 gText_TheTrainersImage[] = _("{JPN}ぴったりの ことばを みつけよう!");
const u8 gText_TheImage[] = _("{JPN}イメージは");
const u8 gText_OutOfTheListedChoices[] = _("{JPN}ことばの なかから");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("{JPN}クイズの こたえを えらぼう!");
const u8 gText_AndCreateAQuiz[] = _("{JPN}クイズを つくろう!");
const u8 gText_PickAWordOrPhraseAnd[] = _("{JPN}ことばの なかから ひとつを えらんで");
const u8 gText_SetTheQuizAnswer[] = _("{JPN}クイズの こたえを つくろう!");
const u8 gText_TheAnswerColon[] = _("{JPN}こたえは");
const u8 gText_TheQuizColon[] = _("{JPN}クイズは"); // Unused
const u8 gText_ApprenticePhrase[] = _("{JPN}でしの きめゼリフは");
const u8 gText_QuitEditing[] = _("{JPN}へんしゅうを やめますか？");
const u8 gText_StopGivingPkmnMail[] = _("{JPN}メールを もたせるのを やめますか?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("{JPN}ショップの アンケートに こたえよう!");
const u8 gText_LetsReplyToTheInterview[] = _("{JPN}インタビューに こたえよう！");
const u8 gText_AllTextBeingEditedWill[] = _("{JPN}へんしゅうちゅうの ことばを");
const u8 gText_BeDeletedThatOkay[] = _("{JPN}ぜんぶ けしても いいですか?");
const u8 gText_QuitEditing2[] = _("{JPN}へんしゅうを やめますか？"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("{JPN}へんしゅうした ことばは ほぞん"); // Unused
const u8 gText_IsThatOkay[] = _("{JPN}されませんが いいですか?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("{JPN}なにか ことばを いれてください!"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("{JPN}ことばを ぜんぶ けすことは できません!");
const u8 gText_OnlyOnePhrase[] = _("{JPN}かえられる ことばは 1つ までです!");
const u8 gText_OriginalSongWillBeUsed[] = _("{JPN}うたを もとに もどします!");
const u8 gText_ThatsTrendyAlready[] = _("{JPN}それは もう はやっています！"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("{JPN}2つの ことばを くみあわせてください!");
const u8 gText_QuitGivingInfo[] = _("{JPN}ことばを おしえるのを やめますか?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("{JPN}メールを もたせるのを やめますか?"); // Unused
const u8 gText_CreateAQuiz2[] = _("{JPN}もんだいを つくってください!"); // Unused
const u8 gText_SetTheAnswer[] = _("{JPN}こたえを えらんでください!"); // Unused
const u8 gText_CancelSelection[] = _("{JPN}もとにもどして いいですか?"); // Unused
const u8 gText_Profile[] = _("{JPN}プロフィール");
const u8 gText_AtTheBattlesStart[] = _("{JPN}たいせんが はじまるとき");
const u8 gText_UponWinningABattle[] = _("{JPN}たいせんに かったとき");
const u8 gText_UponLosingABattle[] = _("{JPN}たいせんに まけたとき");
const u8 gText_TheBardsSong[] = _("{JPN}オヤジのうた");
const u8 gText_WhatsHipAndHappening[] = _("{JPN}はやっている ものは?");
const u8 gText_Interview[] = _("{JPN}インタビュー");
const u8 gText_GoodSaying[] = _("{JPN}いい ことば");
const u8 gText_FansQuestion[] = _("{JPN}ファンのしつもん");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("{JPN}クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("{JPN}でしの きめゼリフ");
const u8 gText_Questionnaire[] = _("{JPN}アンケート");
const u8 gText_YouCannotQuitHere[] = _("{JPN}ここでは とちゅうで");
const u8 gText_SectionMustBeCompleted[] = _("{JPN}やめることは できません!");
const u8 gText_F700sQuiz[] = _("{JPN}{DYNAMIC 0} さんの クイズ");
const u8 gText_Lady[] = _("{JPN}おねえさん");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("{JPN}もんだいを よんだら");
const u8 gText_QuestionPressTheAButton[] = _("{JPN}Aボタンを おしてね!");
const u8 gText_TheQuizAnswerIs[] = _("{JPN}クイズの こたえは?");
const u8 gText_LikeToQuitQuiz[] = _("{JPN}クイズの チャレンジを");
const u8 gText_ChallengeQuestionMark[] = _("{JPN}あきらめますか?");
const u8 gText_IsThisQuizOK[] = _("{JPN}クイズは これで いいですか?");
const u8 gText_CreateAQuiz[] = _("{JPN}もんだいを つくってください!");
const u8 gText_SelectTheAnswer[] = _("{JPN}こたえを えらんでください!");
const u8 gText_LyricsCantBeDeleted[] = _("{JPN}かしを けすことは できません!");
const u8 gText_PokemonLeague[] = _("{JPN}ポケモンリーグ");
const u8 gText_PokemonCenter[] = _("{JPN}ポケモンセンター");
const u8 gText_Coolness[] = _("{JPN}かっこよさ ");
const u8 gText_Beauty3[] = _("{JPN}うつくしさ ");
const u8 gText_Cuteness[] = _("{JPN}かわいさ ");
const u8 gText_Smartness[] = _("{JPN}かしこさ ");
const u8 gText_Toughness[] = _("{JPN}たくましさ ");

const u8 gText_SaveFailedCheckingBackup[] = _("{JPN}レポートの かきこみに しっぱいしました\nバックアップカートリッジの けんさをします\nしばらくおまちください{COLOR RED}1ふんほど かかります");
const u8 gText_BackupMemoryDamaged[] = _("{JPN}バックアップきのうの こしょう または じゅみょうが\nきました。セーブすることは できませんがこのまま\nゲームを あそぶことはできます");
const u8 gText_GamePlayCannotBeContinued[] = _("{JPN}{COLOR RED}このまま ぼうけんをつづけることは できません\nタイトルに もどります");
const u8 gText_CheckCompleted[] = _("{JPN}けんさが しゅうりょうしました!\nもういちど レポートを かきこみます\nしばらくおまちください");
const u8 gText_SaveCompleteGameCannotContinue[] = _("{JPN}レポートの かきこみは しゅうりょうしました\n{COLOR RED}このまま ぼうけんをつづけることは できません\nタイトルに もどります");
const u8 gText_SaveCompletePressA[] = _("{JPN}レポートの かきこみは しゅうりょうしました\n{COLOR RED}Aボタンを おしてください");

const u8 gText_Ferry[] = _("{JPN}れんらくせん");
const u8 gText_SecretBase[] = _("{JPN}ひみつきち");
const u8 gText_Hideout[] = _("{JPN}アジト");
const u8 gText_ResetRTCConfirmCancel[] = _("{JPN}RTCをリセットします\nAで けってい Bで キャンセル");
const u8 gText_PresentTime[] = _("{JPN}げんざいの ゲームない じかん");
const u8 gText_PreviousTime[] = _("{JPN}ぜんかいの ゲームない じかん");
const u8 gText_PleaseResetTime[] = _("{JPN}じかんを さいせってい してください");
const u8 gText_ClockHasBeenReset[] = _("{JPN}じかんを さいせってい しました!\nレポートを かいています おまちください");
const u8 gText_SaveCompleted[] = _("{JPN}レポートを かきこみました!");
const u8 gText_SaveFailed[] = _("{JPN}レポートの かきこみに\nしっぱい しました…");
const u8 gText_NoSaveFileCantSetTime[] = _("{JPN}レポートが ないので\nじかんの せっていは できません!");
const u8 gText_InGameClockUsable[] = _("{JPN}ゲームない じかんの しゅうせい システムが\nつかえる ように なりました!");
const u8 gText_Spicy2[] = _("{JPN}から");
const u8 gText_Dry2[] = _("{JPN}しぶ");
const u8 gText_Sweet2[] = _("{JPN}あま");
const u8 gText_Bitter2[] = _("{JPN}にが");
const u8 gText_Sour2[] = _("{JPN}すっぱ");
const u8 gText_Single[] = _("{JPN}シングル");
const u8 gText_Double[] = _("{JPN}ダブル");
const u8 gText_Knockout[] = _("{JPN}ノックアウト");
const u8 gText_Mixed[] = _("{JPN}ミックス");
const u8 gText_First[] = _("{JPN}1ばんめ");
const u8 gText_Second[] = _("{JPN}2ばんめ");
const u8 gText_Third[] = _("{JPN}3ばんめ");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{JPN}{STR_VAR_1}は ちからつきた\p");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{JPN}{STR_VAR_1}は なんとか どくにたえた\nどくが きえさった!\p");
#endif
const u8 gText_Marco[] = _("{JPN}コウジ");
const u8 gText_TrainerCardName[] = _("{JPN}なまえ: ");
const u8 gText_TrainerCardIDNo[] = _("{JPN}IDNo．");
const u8 gText_TrainerCardMoney[] = _("{JPN}おこづかい");
const u8 gText_PokeDollar[] = _("{JPN}円"); // Unused
const u8 gText_TrainerCardPokedex[] = _("{JPN}ポケモンずかん");
const u8 gText_EmptyString6[] = _("{JPN}ひき");
const u8 gText_Colon2[] = _("{JPN}:");
const u8 gText_Points[] = _("{JPN}てん"); // Unused
const u8 gText_TrainerCardTime[] = _("{JPN}プレイじかん");
const u8 gJPText_BattlePoints[] = _("{JPN}ゲームポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{JPN}{STR_VAR_1}のトレーナーカード");
const u8 gText_HallOfFameDebut[] = _("{JPN}はじめてのでんどういり");
const u8 gText_LinkBattles[] = _("{JPN}つうしんたいせん");
const u8 gText_LinkCableBattles[] = _("{JPN}ケーブルたいせん");
const u8 gText_WinsLosses[] = _("{JPN}かち:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  まけ:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("{JPN}ポケモンつうしんこうかん");
const u8 gText_UnionTradesAndBattles[] = _("{JPN}ユニオンたいせんとこうかん");
const u8 gText_BerryCrush[] = _("{JPN}きのみクラッシュ");
const u8 gText_WaitingTrainerFinishReading[] = _("{JPN}あいてが カードを みおわるのを\nまっています");
const u8 gText_PokeblocksWithFriends[] = _("{JPN}ともだちと つくった ポロック");
const u8 gText_NumPokeblocks[] = _("{JPN}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("{JPN}ともだちとコンテスト ゆうしょう");
const u8 gText_BattlePtsWon[] = _("{JPN}かちとった バトルポイント");
const u8 gText_NumBP[] = _("{JPN}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("{JPN}バトルタワー");
const u8 gText_WinsStraight[] = _("{JPN}かち/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  れんしょう/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("{JPN}バトルタワー");
const u8 gText_BattleDome[] = _("{JPN}バトルドーム");
const u8 gText_BattlePalace[] = _("{JPN}バトルパレス");
const u8 gText_BattleFactory[] = _("{JPN}バトルファクトリー");
const u8 gText_BattleArena[] = _("{JPN}バトルアリーナ");
const u8 gText_BattlePike[] = _("{JPN}バトルチューブ");
const u8 gText_BattlePyramid[] = _("{JPN}バトルピラミッド");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{JPN}{STR_VAR_1} シングル");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{JPN}{STR_VAR_1} ダブル");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{JPN}{STR_VAR_1} マルチ");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{JPN}{STR_VAR_1} つうしん");
ALIGNED(4) const u8 gText_Facility[] = _("{JPN}{STR_VAR_1}");

const u8 gText_Give[] = _("{JPN}もたせるべき");
const u8 gText_NoNeed[] = _("{JPN}もたせない");
const u8 gText_AnnouncingResults[] = _("{JPN}けっか はっぴょう!");
const u8 gText_PreliminaryResults[] = _("{JPN}1じしんさの けっか!");
const u8 gText_Round2Results[] = _("{JPN}2じしんさの けっか!");
const u8 gText_ContestantsMonWon[] = _("{JPN}ゆうしょう! {STR_VAR_1}の {STR_VAR_2}!");
const u8 gText_CommunicationStandby[] = _("{JPN}つうしんたいきちゅう");
const u8 gText_ColorDarkGray[] = _("{JPN}{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{JPN}{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{JPN}{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _("{JPN} "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{JPN}{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{JPN}{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{JPN}{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("{JPN}おおもじ");
const u8 gText_Lower[] = _("{JPN}こもじ");
const u8 gText_Others[] = _("{JPN}そのほか");
const u8 gText_Symbols[] = _("{JPN}きごう");
const u8 gText_Register2[] = _("{JPN}とうろく");
const u8 gText_Exit2[] = _("{JPN}とじる");
const u8 gText_QuitChatting[] = _("{JPN}チャットを やめますか？");
const u8 gText_RegisterTextWhere[] = _("{JPN}どこに ことばを とうろくしますか？");
const u8 gText_RegisterTextHere[] = _("{JPN}ここに とうろくしますか?");
const u8 gText_InputText[] = _("{JPN}ことばを いれて ください!");
const u8 gText_F700JoinedChat[] = _("{JPN}{DYNAMIC 0} さんが さんかしました!");
const u8 gText_F700LeftChat[] = _("{JPN}{DYNAMIC 0}さんが ぬけました");
const u8 gJPText_PlayersXPokemon[] = _("{JPN}{DYNAMIC 0} の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{JPN}{DYNAMIC 0} の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("{JPN}さんかしゃが いなくなったので\nしゅうりょうします!");
const u8 gText_LeaderLeftEndingChat[] = _("{JPN}リーダーの {DYNAMIC 0}が\nぬけたので かいさんします!");
const u8 gText_RegisteredTextChangedOKToSave[] = _("{JPN}とうろくが かわりました\nポケモンレポートに かきこみますか?");
const u8 gText_AlreadySavedFile_Chat[] = _("{JPN}まえに かかれた レポートに\nうえから かいても いいですか?");
const u8 gText_SavingDontTurnOff_Chat[] = _("{JPN}ポケモンレポートに かきこんでいます\nでんげんを きらないで ください");
const u8 gText_PlayerSavedGame_Chat[] = _("{JPN}{DYNAMIC 0} は\nレポートに しっかり かきのこした!");
const u8 gText_IfLeaderLeavesChatEnds[] = _("{JPN}リーダーが やめると かいさん\nになりますが よろしいですか?");
const u8 gText_Hello[] = _("{JPN}こんにちは");
const u8 gText_Pokemon2[] = _("{JPN}ポケモン");
const u8 gText_Trade[] = _("{JPN}こうかん");
const u8 gText_Battle[] = _("{JPN}たいせん");
const u8 gText_Lets[] = _("{JPN}しよう!");
const u8 gText_Ok[] = _("{JPN}OK!");
const u8 gText_Sorry[] = _("{JPN}ごめん…");
const u8 gText_YaySmileEmoji[] = _("{JPN}わーい{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("{JPN}サンキュー");
const u8 gText_ByeBye[] = _("{JPN}バイバイ!");
const u8 gText_HatchedFromEgg[] = _("{JPN}タマゴが かえって\n{STR_VAR_1}が うまれた!");
const u8 gText_NicknameHatchPrompt[] = _("{JPN}うまれた {STR_VAR_1}に\nニックネームを つけますか？");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("{JPN}きのみクラッシュを はじめます\nつかう きのみを えらんでください\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("{JPN} ほかの メンバーが きのみを\nえらぶまで おまちください");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{JPN}{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}サラサラな こなが\n{STR_VAR_1}で できた!{RESUME_MUSIC}\pごうけいで こなの りょうが\n{STR_VAR_2}になった!\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("{JPN} ゲームの けっかを\nポケモンレポートに かきこんでいます\lしばらく おまちください");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("{JPN}  きのみクラッシュで もういちど\nあそびますか?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("{JPN}つかう きのみが ありません\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("{JPN}  ぬけた メンバーが いるので\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("{JPN}  じかんぎれ です\pよいこな が\nできあがり ませんでした\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("{JPN}  つうしんたいきちゅう");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("{JPN} 1.{COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("{JPN} 1.{DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("{JPN}   かい");
ALIGNED(4) const u8 gText_XDotY[] = _("{JPN} {STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{JPN}  {STR_VAR_1}のみ");
ALIGNED(4) const u8 gText_TimeColon[] = _("{JPN}   じかん");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("{JPN}おすはやさ");
ALIGNED(4) const u8 gText_Silkiness[] = _("{JPN}  サラサラぐあい");
ALIGNED(4) const u8 gText_StrVar1[] = _("{JPN}{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("{JPN} ふん");
ALIGNED(4) const u8 gText_XDotY2[] = _("{JPN} {STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("{JPN}  びょう");
ALIGNED(4) const u8 gText_XDotY3[] = _("{JPN}{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("{JPN}  かい/びょう");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{JPN} {STR_VAR_1}パーセント");
ALIGNED(4) const u8 gText_PressesRankings[] = _("{JPN}おした かいすう ランキング");
ALIGNED(4) const u8 gText_CrushingResults[] = _("{JPN} つぶした けっか");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("{JPN}   ていねいさ ランキング");
ALIGNED(4) const u8 gText_CoopRankings[] = _("{JPN}たすけあい ランキング");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("{JPN}おすつよさ ランキング");
const u8 gText_BerryCrush2[] = _("{JPN}きのみクラッシュ");
const u8 gText_PressingSpeedRankings[] = _("{JPN}   おすはやさ ランキング!");
const u8 gText_Var1Players[] = _("{JPN}   {STR_VAR_1}にんよう");
const u8 gText_SymbolsEarned[] = _("{JPN}てにいれた シンボル");
const u8 gText_BattleRecord[] = _("{JPN}たいせんの きろく");
const u8 gText_BattlePoints[] = _("{JPN}バトルポイント");
const u8 gText_UnusedCancel[] = _("{JPN}とじる"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("{JPN}バトルフロンティアの マップを みます");
const u8 gText_CheckTrainerCard[] = _("{JPN}トレーナーカードを みます");
const u8 gText_ViewRecordedBattle[] = _("{JPN}きろくした たいせんを みます");
const u8 gText_PutAwayFrontierPass[] = _("{JPN}フロンティアパスを とじます");
const u8 gText_CurrentBattlePoints[] = _("{JPN}いま たまっている バトルポイントです");
const u8 gText_CollectedSymbols[] = _("{JPN}ここに シンボルを あつめます");
const u8 gText_BattleTowerAbilitySymbol[] = _("{JPN}バトルタワー アビリティシンボル");
const u8 gText_BattleDomeTacticsSymbol[] = _("{JPN}バトルドーム タクティクスシンボル");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("{JPN}バトルパレス スピリットシンボル");
const u8 gText_BattleArenaGutsSymbol[] = _("{JPN}バトルアリーナ ガッツシンボル");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("{JPN}バトルファクトリー ノウレッジシンボル");
const u8 gText_BattlePikeLuckSymbol[] = _("{JPN}バトルチューブ ラックシンボル");
const u8 gText_BattlePyramidBraveSymbol[] = _("{JPN}バトルピラミッド ブレイブシンボル");
const u8 gText_ThereIsNoBattleRecord[] = _("{JPN}げんざい たいせんきろくは ありません");
const u8 gText_BattleTower3[] = _("{JPN}バトルタワー");
const u8 gText_BattleDome2[] = _("{JPN}バトルドーム");
const u8 gText_BattlePalace2[] = _("{JPN}バトルパレス");
const u8 gText_BattleArena2[] = _("{JPN}バトルアリーナ");
const u8 gText_BattleFactory2[] = _("{JPN}バトルファクトリー");
const u8 gText_BattlePike2[] = _("{JPN}バトルチューブ");
const u8 gText_BattlePyramid2[] = _("{JPN}バトルピラミッド");
const u8 gText_BattleTowerDesc[] = _("{JPN}かちぬき ひたすら うえを めざす。\nさいのうを ためされる。");
const u8 gText_BattleDomeDesc[] = _("{JPN}トーナメントを かちぬく。\nせんじゅつを ためされる。");
const u8 gText_BattlePalaceDesc[] = _("{JPN}しょうぶを みまもる。\nポケモンとの きずなを ためされる。");
const u8 gText_BattleArenaDesc[] = _("{JPN}つよい ポケモンの チームで しょうりする。\nとうしを ためされる。");
const u8 gText_BattleFactoryDesc[] = _("{JPN}レンタルポケモンで しょうりする。\nちしきを ためされる。");
const u8 gText_BattlePikeDesc[] = _("{JPN}3つの みちから 1つえらび かちすすむ。\nうんを ためされる。");
const u8 gText_BattlePyramidDesc[] = _("{JPN}ちょうじょうを めざし ぼうけんする。\nゆうきを ためされる。");
const u8 gText_Powder[] = _("{JPN}きのみのこな");
const u8 gText_BerryPickingRecords[] = _("{JPN}ドードリオのきのみどりの きろく");
const u8 gText_BerriesPicked[] = _("{JPN}きのみをとった かいすう");
const u8 gText_BestScore[] = _("{JPN}さいこう とくてん");
const u8 gText_BerriesInRowFivePlayers[] = _("{JPN}5にんで きのみを\nつづけてとった かいすう");
const u8 gText_BerryPickingResults[] = _("{JPN}きのみの けっか はっぴょう!!");
const u8 gText_10P30P50P50P[] = _("{JPN}{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("{JPN}じゅんいの はっぴょう!!");
const u8 gText_AnnouncingPrizes[] = _("{JPN}しょうひんの はっぴょう!!");
const u8 gText_1Colon[] = _("{JPN}1:");
const u8 gText_2Colon[] = _("{JPN}2:");
const u8 gText_3Colon[] = _("{JPN}3:");
const u8 gText_4Colon[] = _("{JPN}4:");
const u8 gText_5Colon[] = _("{JPN}5:");
const u8 gText_FirstPlacePrize[] = _("{JPN}1ばんに なった ひとに\n{DYNAMIC 0}を プレゼント!!");
const u8 gText_CantHoldAnyMore[] = _("{JPN}{DYNAMIC 0}はいっぱいです…");
const u8 gText_FilledStorageSpace[] = _("{JPN}{DYNAMIC 0} が いっぱいになってしまった!");
const u8 gText_WantToPlayAgain[] = _("{JPN}もういちど あそびますか？");
const u8 gText_SomeoneDroppedOut[] = _("{JPN}だれかが ぬけました\nつうしんを しゅうりょう します");
const u8 gText_SpacePoints[] = _("{JPN}てん");
const u8 gText_CommunicationStandby3[] = _("{JPN}つうしん たいきちゅうです");
const u8 gText_SpacePoints2[] = _("{JPN}てん");
const u8 gText_SpaceTimes3[] = _("{JPN}かい");
const u8 gText_PkmnJumpRecords[] = _("{JPN}ミニポケモンでジャンプの きろく");
const u8 gText_JumpsInARow[] = _("{JPN}さいこう ジャンプかいすう");
const u8 gText_BestScore2[] = _("{JPN}さいこう とくてん");
const u8 gText_ExcellentsInARow[] = _("{JPN}れんぞく EXCELLENT");
const u8 gText_AwesomeWonF701F700[] = _("{JPN}せいせきが よかったので\n{DYNAMIC 0}を {DYNAMIC 1}こ プレゼント!");
const u8 gText_FilledStorageSpace2[] = _("{JPN}{DYNAMIC 0} が いっぱいに\nなってしまった!");
const u8 gText_CantHoldMore[] = _("{JPN}{DYNAMIC 0} は いっぱいです…");
const u8 gText_WantToPlayAgain2[] = _("{JPN}もういちど あそびますか？");
const u8 gText_SomeoneDroppedOut2[] = _("{JPN}だれかがぬけました\nつうしんを しゅうりょうします");
const u8 gText_CommunicationStandby4[] = _("{JPN}つうしん たいきちゅう");
const u8 gText_LinkContestResults[] = _("{JPN}{PLAYER}の つうしん コンテスト せいせき");
const u8 gText_1st[] = _("{JPN}1い");
const u8 gText_2nd[] = _("{JPN}2い");
const u8 gText_3rd[] = _("{JPN}3い");
const u8 gText_4th[] = _("{JPN}4い");
const u8 gText_Friend[] = _("{JPN}ともだち");
const u8 gText_Pokemon3[] = _("{JPN}ポケモン"); // Unused
const u8 gJPText_MysteryGift[] = _("{JPN}ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{JPN}{A_BUTTON}けってい {B_BUTTON}{JPN}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("{JPN}カードeリーダー{PLUS} で\nふしぎなもらいものを よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("{JPN}カードeリーダー{PLUS}の メニューから\nつうしんを えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("{JPN}ゲームボーイアドバンスとつうしん\nを せんたく してください");
const u8 gJPText_SelectConnectAndPressA[] = _("{JPN}カードeリーダー{PLUS}の つうしんを\nえらんで Aボタンを おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("{JPN}せつぞくが まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("{JPN}カードの よみこみを\nちゅうし しました");
const u8 gJPText_UnableConnectWithEReader[] = _("{JPN}カードeリーダー{PLUS}と\nつうしん できません"); // Unused
const u8 gJPText_Connecting[] = _("{JPN}つうしん ちゅう です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("{JPN}つうしん エラーです\nせつぞくを たしかめて ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("{JPN}つうしん エラーです\nはじめから やりなおして ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("{JPN}カードeリーダー{PLUS} に\nカードを よみこませて ください");
const u8 gJPText_ConnectionComplete[] = _("{JPN}つうしんしゅうりょう!");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("{JPN}あらたな トレーナーが\nホウエンに やってきた!");
const u8 gJPText_PleaseWaitAMoment[] = _("{JPN}しばらく おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("{JPN}かきこみ エラー です\nデータが ほぞん できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{JPN}{PLAYER}の シングル バトルルーム せいせき");
const u8 gText_DoubleBattleRoomResults[] = _("{JPN}{PLAYER}の ダブル バトルルーム せいせき");
const u8 gText_MultiBattleRoomResults[] = _("{JPN}{PLAYER}の マルチ バトルルーム せいせき");
const u8 gText_LinkMultiBattleRoomResults[] = _("{JPN}{PLAYER}の  つうしんマルチ バトルルーム せいせき");
const u8 gText_SingleBattleTourneyResults[] = _("{JPN}{PLAYER}の シングル バトルトーナメント せいせき");
const u8 gText_DoubleBattleTourneyResults[] = _("{JPN}{PLAYER}の ダブル バトルトーナメント せいせき");
const u8 gText_SingleBattleHallResults[] = _("{JPN}{PLAYER}の シングル バトルホール せいせき");
const u8 gText_DoubleBattleHallResults[] = _("{JPN}{PLAYER}の ダブル バトルホール せいせき");
const u8 gText_BattleChoiceResults[] = _("{JPN}{PLAYER}の バトルゲーム せいせき");
const u8 gText_SetKOTourneyResults[] = _("{JPN}{PLAYER}の かちぬきチームバトル せいせき");
const u8 gText_BattleSwapSingleResults[] = _("{JPN}{PLAYER}の バトルトレード シングル せいせき");
const u8 gText_BattleSwapDoubleResults[] = _("{JPN}{PLAYER}の バトルトレード ダブル せいせき");
const u8 gText_BattleQuestResults[] = _("{JPN}{PLAYER}の バトルアドベンチャー せいせき");
const u8 gText_Lv502[] = _("{JPN}レベル 50");
const u8 gText_OpenLv[] = _("{JPN}オープンレベル");
const u8 gText_WinStreak[] = _("{JPN}{STR_VAR_1}れんしょう");
const u8 gText_Current[] = _("{JPN}げんざい");
const u8 gText_Record[] = _("{JPN}さいこう");
const u8 gText_Prev[] = _("{JPN}ぜんかい");
const u8 gText_RentalSwap[] = _("{JPN}レンタル/こうかん");
const u8 gText_Total[] = _("{JPN}つうさん");
const u8 gText_ClearStreak[] = _("{JPN}{STR_VAR_1}れんぱ");
const u8 gText_Championships[] = _("{JPN}{STR_VAR_1}かい ゆうしょう");
const u8 gText_RoomsCleared[] = _("{JPN}{STR_VAR_1}へや とっぱ");
const u8 gText_TimesCleared[] = _("{JPN}{CLEAR 5}{STR_VAR_1}かい クリア");
const u8 gText_KOsInARow[] = _("{JPN}{STR_VAR_1}にんぬき");
const u8 gText_TimesVar1[] = _("{JPN}{STR_VAR_1}かい");
const u8 gText_FloorsCleared[] = _("{JPN}{STR_VAR_1}だん せいは");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("{JPN}レベル 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("{JPN}オープンレベル");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("{JPN}{STR_VAR_2}れんぱ");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("{JPN}{STR_VAR_2}かい クリア");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("{JPN}{STR_VAR_2}へや とっぱ");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("{JPN}{STR_VAR_2}にんぬき");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("{JPN}{STR_VAR_2}だん せいは");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _("{JPN}と {STR_VAR_2}しゅの ポケモンは\nつかえません");
const u8 gText_FrontierFacilityIncluding[] = _("{JPN}。\pたとえば ");
const u8 gText_FrontierFacilityAreInelegible[] = _("{JPN} は つかえません");

const u8 gText_YesNo[] = _("{JPN}はい\nいいえ");
const u8 gText_SelectorArrow3[] = _("{JPN}▶");
const u8 gText_Peekaboo[] = _("{JPN}ばあ！");
const u8 gText_CommErrorCheckConnections[] = _("{JPN}つうしん エラー...\nせつぞくを たしかめてから\nでんげんを いれなおしてください。");
const u8 gText_CommErrorEllipsis[] = _("{JPN}つうしん エラー...");
const u8 gText_MoveCloserToLinkPartner[] = _("{JPN}つうしんあいてに ちかづいてください。\nあいだに ものを おかないでください。");
const u8 gText_ABtnRegistrationCounter[] = _("{JPN}Aボタン: とうろくカウンター");
const u8 gText_ABtnTitleScreen[] = _("{JPN}Aボタン: タイトル");
const u8 gText_NumPlayerLink[] = _("{JPN}{STR_VAR_1}にん せつぞく");
const u8 gText_BronzeCard[] = _("{JPN}ブロンズ");
const u8 gText_CopperCard[] = _("{JPN}カッパー");
const u8 gText_SilverCard[] = _("{JPN}シルバー");
const u8 gText_GoldCard[] = _("{JPN}ゴールド");
const u8 gText_Day[] = _("{JPN}にち");
const u8 gText_Colon3[] = _("{JPN}:");
const u8 gText_Confirm2[] = _("{JPN}けってい");
const u8 gText_Days[] = _("{JPN}にち"); // Unused
const u8 gText_TimeColon2[] = _("{JPN}じかん:"); // Unused
const u8 gText_GameTime[] = _("{JPN}ゲームじかん"); // Unused
const u8 gText_RTCTime[] = _("{JPN}RTCじかん"); // Unused
const u8 gText_UpdatedTime[] = _("{JPN}なおした じかん"); // Unused
const u8 gText_MenuPokedex[] = _("{JPN}ずかん");
const u8 gText_MenuPokemon[] = _("{JPN}ポケモン");
const u8 gText_MenuBag[] = _("{JPN}バッグ");
const u8 gText_MenuPokenav[] = _("{JPN}ポケナビ");
const u8 gText_MenuPlayer[] = _("{JPN}{PLAYER}");
const u8 gText_MenuSave[] = _("{JPN}レポート");
const u8 gText_MenuOption[] = _("{JPN}せってい");
const u8 gText_MenuExit[] = _("{JPN}とじる");
const u8 gText_MenuRetire[] = _("{JPN}リタイア");
const u8 gText_MenuRest[] = _("{JPN}やすむ");
const u8 gText_MenuDexNav[] = _("{JPN}ずかんナビ");
const u8 gText_SafariBallStock[] = _("{JPN}サファリボール\nのこり {STR_VAR_1}コ");
const u8 gText_MenuSafariStats[] = _("{JPN}{STR_VAR_1}/{STR_VAR_2}\nボール  {STR_VAR_3}コ");
const u8 gText_BattlePyramidFloor[] = _("{JPN}バトルピラミッド\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("{JPN}げんざい 1だんめ");
const u8 gText_Floor2[] = _("{JPN}げんざい 2だんめ");
const u8 gText_Floor3[] = _("{JPN}げんざい 3だんめ");
const u8 gText_Floor4[] = _("{JPN}げんざい 4だんめ");
const u8 gText_Floor5[] = _("{JPN}げんざい 5だんめ");
const u8 gText_Floor6[] = _("{JPN}げんざい 6だんめ");
const u8 gText_Floor7[] = _("{JPN}げんざい 7だんめ");
const u8 gText_Peak[] = _("{JPN}げんざい ちょうじょう");
const u8 gText_LinkStandby2[] = _("{JPN}つうしん たいきちゅう...\n... ... Bボタン: やめる");
const u8 gText_PressAToLoadEvent[] = _("{JPN}Aボタンで イベントを よみこむ。\n... ... Bボタン: やめる");
const u8 gText_LoadingEvent[] = _("{JPN}イベントを よみこみちゅう...");
const u8 gText_DontRemoveCableTurnOff[] = _("{JPN}ケーブルを ぬかないでください。\nでんげんを きらないでください。");
const u8 gText_EventSafelyLoaded[] = _("{JPN}イベントを よみこみました。");
const u8 gText_LoadErrorEndingSession[] = _("{JPN}よみこみ エラー。\nおわります。");
const u8 gJPText_Player[] = _("{JPN}プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("{JPN}さま"); // Unused
const u8 gText_DexHoenn[] = _("{JPN}ホウエン");
const u8 gText_DexNational[] = _("{JPN}ぜんこく");
const u8 gText_PokedexDiploma[] = _("{JPN}{CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}さま{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nあなたが {STR_VAR_1}ずかんを\nみごとかんせいさせた\nいだいなこうせきを たたえ\nここに しょうめい します\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}ゲームフリーク");
const u8 gJPText_GameFreak[] = _("{JPN}{COLOR RED}{SHADOW LIGHT_RED}ゲームフリーク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{JPN}{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("{JPN}ホウエンちほう");
const u8 gText_Kanto[] = _("{JPN}カントー");
const u8 gText_XWillBeSentToY[] = _("{JPN}{STR_VAR_2}を\n{STR_VAR_1}へ おくります。");
const u8 gText_ByeByeVar1[] = _("{JPN}バイバイ {STR_VAR_2}！");
const u8 gText_XSentOverY[] = _("{JPN}{STR_VAR_1}は {STR_VAR_3}を おくった。");
const u8 gText_TakeGoodCareOfX[] = _("{JPN}{STR_VAR_3}を たいせつに してね！");

const u8 gText_ThreeQuestionMarks[] = _("{JPN}？？？");
const u8 gText_MaxHP[] = _("{JPN}さいだいHP");
const u8 gText_Attack[] = _("{JPN}こうげき");
const u8 gText_Defense[] = _("{JPN}ぼうぎょ");
const u8 gText_Speed[] = _("{JPN}すばやさ");
const u8 gText_SpAtk[] = _("{JPN}とくこう");
const u8 gText_SpDef[] = _("{JPN}とくぼう");
const u8 gText_Plus[] = _("{JPN}{PLUS}");
const u8 gText_Dash[] = _("{JPN}ー");
const u8 gText_MixingRecords[] = _("{JPN}レコードを まぜています");
const u8 gText_RecordMixingComplete[] = _("{JPN}しゅうりょう しました\nおつかれさまでした");
const u8 gText_RentalPkmn2[] = _("{JPN}ポケモンレンタル");
const u8 gText_SelectFirstPkmn[] = _("{JPN}1ばんめのポケモンを えらんでください");
const u8 gText_SelectSecondPkmn[] = _("{JPN}2ばんめのポケモンを えらんでください");
const u8 gText_SelectThirdPkmn[] = _("{JPN}3ばんめのポケモンを えらんでください");
const u8 gText_Rent[] = _("{JPN}レンタルする");
const u8 gText_Summary[] = _("{JPN}つよさをみる");
const u8 gText_Others2[] = _("{JPN}べつのにする");
const u8 gText_Deselect[] = _("{JPN}はずす");
const u8 gText_TheseThreePkmnOkay[] = _("{JPN}いじょうの 3ひきで よろしいですか?");
const u8 gText_Yes2[] = _("{JPN}はい");
const u8 gText_No2[] = _("{JPN}いいえ");
const u8 gText_CantSelectSamePkmn[] = _("{JPN}おなじポケモンは えらべません");
const u8 gText_PkmnSwap[] = _("{JPN}ポケモンこうかん     ");
const u8 gText_SelectPkmnToSwap[] = _("{JPN}てばなすポケモンを えらんでください");
const u8 gText_SelectPkmnToAccept[] = _("{JPN}うけとるポケモンを えらんでください");
const u8 gText_Swap[] = _("{JPN}てばなす");
const u8 gText_Summary2[] = _("{JPN}つよさをみる");
const u8 gText_Rechoose[] = _("{JPN}べつのにする");
const u8 gText_QuitSwapping[] = _("{JPN}こうかんを ちゅうし しますか?");
const u8 gText_Yes3[] = _("{JPN}はい");
const u8 gText_No3[] = _("{JPN}いいえ");
const u8 gText_PkmnForSwap[] = _("{JPN}てばなすポケモン");
const u8 gText_Cancel3[] = _("{JPN}ちゅうし");
const u8 gText_Swap2[] = _("{JPN}てばなす"); // Unused
const u8 gText_Accept[] = _("{JPN}うけとる"); // Unused
const u8 gText_AcceptThisPkmn[] = _("{JPN}このポケモンを うけとりますか?");
const u8 gText_4Spaces[] = _("{JPN}    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("{JPN}てもちに おなじ ポケモンが います!");
const u8 gText_DecimalPoint[] = _("{JPN}.");
const u8 gText_SavingPlayer[] = _("{JPN}しゅじんこう");
const u8 gText_SavingBadges[] = _("{JPN}もっているバッジ");
const u8 gText_SavingPokedex[] = _("{JPN}ポケモンずかん");
const u8 gText_SavingTime[] = _("{JPN}プレイじかん");
const u8 gText_WirelessCommStatus[] = _("{JPN}ワイヤレス つうしん じょうきょう");
const u8 gText_PeopleTrading[] = _("{JPN}こうかん している ひと:");
const u8 gText_PeopleBattling[] = _("{JPN}たいせん している ひと:");
const u8 gText_PeopleInUnionRoom[] = _("{JPN}ユニオンルームに いる ひと:");
const u8 gText_PeopleCommunicating[] = _("{JPN}つうしん している ひと:");
const u8 gText_F700Players[] = _("{JPN}{DYNAMIC 0}にん");
const u8 gText_F701Players[] = _("{JPN}{DYNAMIC 1}にん");
const u8 gText_F702Players[] = _("{JPN}{DYNAMIC 2}にん");
const u8 gText_F703Players[] = _("{JPN}{DYNAMIC 3}にん");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("{JPN}ふしぎなカード");
ALIGNED(4) const u8 gText_WonderNews[] = _("{JPN}ふしぎなニュース");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("{JPN}ワイヤレスつうしん");
ALIGNED(4) const u8 gText_Friend2[] = _("{JPN}ともだち");
ALIGNED(4) const u8 gText_Exit3[] = _("{JPN}おわる");
ALIGNED(4) const u8 gText_Receive[] = _("{JPN}うけとる");
ALIGNED(4) const u8 gText_Send[] = _("{JPN}おくる");
ALIGNED(4) const u8 gText_Toss[] = _("{JPN}すてる");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("{JPN}ワイヤレスで いろいろな できごとを\nよみこみます");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("{JPN}  もっている ふしぎなカードを\nみることが できます");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("{JPN}  おくられてきた ニュースを\nみることが できます");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("{JPN}   タイトルに もどります");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("{JPN}ふしぎなカードを もっていないので\nあたらしく カードを よみこみます");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("{JPN}ふしぎなニュースを もっていないので\nあたらしく ニュースを よみこみます");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("{JPN}  どちらから ふしぎなカードを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("{JPN}   どちらから ふしぎなニュースを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("{JPN}  つうしん たいき ちゅう です\n...Bボタンで キャンセル します"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("{JPN} つうしん しています...");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("{JPN}  つうしんが しゅうりょう しました");
ALIGNED(4) const u8 gText_CommunicationError[] = _("{JPN}  つうしんに しっぱい しました");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("{JPN}つうしんを キャンセル しました");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("{JPN}   いまの ふしぎなカードを すてて\nあたらしい カードを よみこみますか?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("{JPN}   まだ カードの おくりものを もらって\nませんが ほんとうに よみこみますか?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("{JPN}{STR_VAR_1}から ふしぎなカードが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("{JPN}{STR_VAR_1}  から ニュースが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("{JPN} あたらしい ふしぎなカードが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("{JPN} あたらしい ニュースが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("{JPN} あたらしい スタンプが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("{JPN} あたらしい トレーナーが\nおくられて きました!");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("{JPN}   おなじふしぎなカードを\nすでにもっています");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("{JPN}おなじ ニュースを\nすでに もっています");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("{JPN}   おなじ スタンプを\nすでに もっています");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("{JPN}   スタンプが いっぱい なので\nもう おせません!");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("{JPN}   じぶんの きろくを\nジョイスポットに よみこませ ました!");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("{JPN}  この あいて からは ふしぎなカードを\nうけとれません!");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("{JPN}  この あいて からは ふしぎなニュースを\nうけとれません!");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("{JPN}  なにも おくられて\nきません でした");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("{JPN} カードを どうしますか?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("{JPN}   ニュースを どうしますか?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("{JPN}  ふしぎなカード を\nおくって います...");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("{JPN}  ニュースを\nおくって います...");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("{JPN}{STR_VAR_1}に ふしぎなカードを\nおくり ました!");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("{JPN}{STR_VAR_1}  に ニュース を\nおくり ました!");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{JPN}{STR_VAR_1}に スタンプ を\nおくり ました");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{JPN}{STR_VAR_1}に おくりものを しました!");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("{JPN}   あいてが おなじ\nふしぎなカードを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("{JPN}  あいてが おなじ\nニュースを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("{JPN} あいてが おなじ\nスタンプを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("{JPN} あいてが つうしんを \nキャンセル しました");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("{JPN} この あいて には\nふしぎなおくりものを わたせません");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("{JPN}カードをすてると できごとも\nなくなりますが よいですか?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("{JPN}  ほんとうに ニュースを\nすてても よいですか?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("{JPN}おくりものを もらってません\nが ほんとうに すてますか?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("{JPN}  レポートを かいています\nしばらく おまちください");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("{JPN}  レポートを かきこみました!\nAボタンを おしてください");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("{JPN}   ふしぎなカードを すてました");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("{JPN} ニュースを すてました");
ALIGNED(4) const u8 gText_MysteryGift[] = _("{JPN}ふしぎな おくりもの");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{JPN}{DPAD_UPDOWN}えらぶ {A_BUTTON}けってい {B_BUTTON}おわる");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{JPN}{DPAD_UPDOWN}えらぶ {A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gText_PlayersBattleResults[] = _("{JPN}{PLAYER} の たいせん せいせき");
const u8 gText_TotalRecordWLD[] = _("{JPN}{STR_VAR_1}しょう {STR_VAR_2}はい {STR_VAR_3}ひきわけ");
const u8 gText_WinLoseDraw[] = _("{JPN}{CLEAR_TO 83}かち{CLEAR_TO 128}まけ{CLEAR_TO 176}ひきわけ");
const u8 gText_CommunicationStandby5[] = _("{JPN}つうしん たいきちゅう...");
const u8 gDaycareText_GetAlongVeryWell[] = _("{JPN}2ひきの なかは\nとっても よい ようじゃ");
const u8 gDaycareText_GetAlong[] = _("{JPN}2ひきの なかは\nまずまずの ようじゃ");
const u8 gDaycareText_DontLikeOther[] = _("{JPN}2ひきの なかは\nそれほど よくないがなぁ");
const u8 gDaycareText_PlayOther[] = _("{JPN}2ひきは おたがいに\nちがう ポケモンたちと\lあそんでおるがなあ");
const u8 gText_NewLine2[] = _("{JPN}\n");
const u8 gText_Exit4[] = _("{JPN}おわる");
const u8 gText_Lv[] = _("{JPN}{ENG}{LV}{AUTO}");
const u8 gText_TimeBoard[] = _("{JPN}タイムボード");
const u8 gText_TimeCleared[] = _("{JPN}クリアタイム ");
const u8 gText_XMinYDotZSec[] = _("{JPN}{STR_VAR_1}ふん  {STR_VAR_2}びょう{STR_VAR_3}");
const u8 gText_TrainerHill1F[] = _("{JPN}1F");
const u8 gText_TrainerHill2F[] = _("{JPN}2F");
const u8 gText_TrainerHill3F[] = _("{JPN}3F");
const u8 gText_TrainerHill4F[] = _("{JPN}4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("{JPN}{STR_VAR_1}に どの {STR_VAR_3}を\nおしえますか？");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{JPN}{STR_VAR_2}を おしえますか？");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("{JPN}{STR_VAR_2}を おしえますか？\n{STR_VAR_3}を 1つ つかいます。");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{JPN}{STR_VAR_1}は\n{STR_VAR_2}を おぼえた！");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{JPN}{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえたい……!\pしかし {STR_VAR_1}は わざを 4つ\nおぼえるので せいいっぱいだ!\p{STR_VAR_2}の かわりに\nほかの わざを わすれさせますか?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{JPN}{STR_VAR_2}を おしえるのを\nやめますか？");
const u8 gText_MoveRelearnerAndPoof[] = _("{JPN}1 {PAUSE 15}2の {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{JPN}{STR_VAR_1}は {STR_VAR_3}の\nつかいかたを きれいに わすれた!\pそして...\p{STR_VAR_1}は あたらしく {STR_VAR_2}を おぼえた!\n");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{JPN}{STR_VAR_1}は\n{STR_VAR_2}を おぼえなかった。"); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("{JPN}{STR_VAR_1}に あたらしい わざを\nおしえるのを やめますか？");
const u8 gText_MoveRelearnerStop[] = _("{JPN}{STR_VAR_1}に あたらしい わざを\nおぼえさせるのを やめますか？");;
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("{JPN}どの わざを\nわすれさせたい?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("{JPN}たいせんの わざ");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("{JPN}コンテストわざ");
const u8 gText_MoveRelearnerType[] = _("{JPN}タイプ/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("{JPN}PP/");
const u8 gText_MoveRelearnerPower[] = _("{JPN}いりょく/");
const u8 gText_MoveRelearnerAccuracy[] = _("{JPN}めいちゅう/");
const u8 gText_MoveRelearnerAppeal[] = _("{JPN}アピール");
const u8 gText_MoveRelearnerJam[] = _("{JPN}ぼうがい");
const u8 gText_ClearAllSaveData[] = _("{JPN}すべての レポートを けしますか？");
const u8 gText_ClearingData[] = _("{JPN}データを けしています...\nおまちください。");
const u8 gText_IsThisTheCorrectTime[] = _("{JPN}この じかんで いいですか？");
const u8 gText_Confirm3[] = _("{JPN}けってい");
const u8 gText_Cancel4[] = _("{JPN}やめる");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("{JPN}つうしんたいきちゅう\nあいての せんたくを まっています…");
const u8 gText_BattleWasRefused[] = _("{JPN}たいせんを ことわられました{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("{JPN}たいせんを ことわりました{PAUSE 60}");
const u8 gText_NoWeather[] = _("{JPN}てんきなし"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("{JPN}はれ"); // Unused
const u8 gText_Sunny2[] = _("{JPN}はれ2"); // Unused
const u8 gText_Rain[] = _("{JPN}あめ"); // Unused
const u8 gText_Snow[] = _("{JPN}ゆき"); // Unused
const u8 gText_Lightning[] = _("{JPN}かみなり"); // Unused
const u8 gText_Fog[] = _("{JPN}きり"); // Unused
const u8 gText_VolcanoAsh[] = _("{JPN}かざんばい"); // Unused
const u8 gText_Sandstorm[] = _("{JPN}すなあらし"); // Unused
const u8 gText_Fog2[] = _("{JPN}きり2"); // Unused
const u8 gText_Seafloor[] = _("{JPN}かいてい"); // Unused
const u8 gText_Cloudy[] = _("{JPN}くもり"); // Unused
const u8 gText_Sunny3[] = _("{JPN}はれ3"); // Unused
const u8 gText_HeavyRain[] = _("{JPN}おおあめ"); // Unused
const u8 gText_Seafloor2[] = _("{JPN}かいてい2"); // Unused
const u8 gText_DelAll[] = _("{JPN}ぜんぶけす");
const u8 gText_Cancel5[] = _("{JPN}やめる");
const u8 gText_Ok2[] = _("{JPN}OK");
const u8 gText_Quiz[] = _("{JPN}クイズ");
const u8 gText_Answer[] = _("{JPN}こたえ");
const u8 gText_PokeBalls[] = _("{JPN}ボール");
const u8 gText_Berry[] = _("{JPN}きのみ");
const u8 gText_Berries[] = _("{JPN}きのみ");
const u8 gText_ExpShareOn[] = _("{JPN}けいけんちそうちを オンに しました。{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("{JPN}けいけんちそうちを オフに しました。{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("{JPN}ゴースト");
const u8 gText_Boulderbadge[] = _("{JPN}グレーバッジ");
const u8 gText_Cascadebadge[] = _("{JPN}ブルーバッジ");
const u8 gText_Thunderbadge[] = _("{JPN}オレンジバッジ");
const u8 gText_Rainbowbadge[] = _("{JPN}レインボーバッジ");
const u8 gText_Soulbadge[] = _("{JPN}ピンクバッジ");
const u8 gText_Marshbadge[] = _("{JPN}ゴールドバッジ");
const u8 gText_Volcanobadge[] = _("{JPN}クリムゾンバッジ");
const u8 gText_Earthbadge[] = _("{JPN}グリーンバッジ");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("{JPN}オーキド: ポケモンを よく しることは\nとても たいせつじゃ。\p");
const u8 gText_OakThisIsListOfPokemon[] = _("{JPN}これは あなたの ポケモンリストじゃ \n{PLAYER}。\pここでは ポケモンの のうりょくや\nわざを みられる。\pどうぐを つかう ポケモンを\nえらぶことも できるぞ。{PAUSE_UNTIL_PRESS}");
